"use client";

import { FormEvent, useEffect, useState } from "react";

type Link={productId:string;sku:string;name:string;type:string;sortOrder:number};
type CompanyPrice={tenantId:string;company:string;price:number;validFrom?:string;validTo?:string};
type Detail={id:string;sku:string;name:string;basePrice:number;costPrice:number;profitMargin:number;packageType?:string;unitsPerPackage:number;packagesPerCarton:number;cartonBarcode?:string;warranty?:string;seoTitle?:string;seoDescription?:string;seoKeywords?:string;status:string;links:Link[];companyPrices:CompanyPrice[];products:{id:string;sku:string;name:string;price:number}[];companies:{tenantId:string;name:string}[]};

export function ProductCommercialEditor({product,onClose,onError}:{product:{id:string;nameAr:string;sku:string};onClose:()=>void;onError:(message:string)=>void}){
  const [data,setData]=useState<Detail|null>(null);const [tab,setTab]=useState<"commercial"|"links"|"companies">("commercial");const [saving,setSaving]=useState(false);
  useEffect(()=>{const c=new AbortController();fetch(`/api/admin/catalog/products/${product.id}/commercial`,{signal:c.signal}).then(async r=>{if(!r.ok)throw new Error("تعذر تحميل البيانات التجارية");setData(await r.json())}).catch(e=>{if(e.name!=="AbortError")onError(e.message)});return()=>c.abort()},[product.id,onError]);
  async function put(path:string,body:unknown){setSaving(true);const r=await fetch(`/api/admin/catalog/products/${product.id}/${path}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){const value=await r.json().catch(()=>({}));onError(value.title||"تعذر حفظ البيانات");setSaving(false);return}setData(await r.json());setSaving(false)}
  function commercial(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);put("commercial",{costPrice:Number(f.get("costPrice")),packageType:f.get("packageType"),unitsPerPackage:Number(f.get("unitsPerPackage")),packagesPerCarton:Number(f.get("packagesPerCarton")),cartonBarcode:f.get("cartonBarcode"),warranty:f.get("warranty"),seoTitle:f.get("seoTitle"),seoDescription:f.get("seoDescription"),seoKeywords:f.get("seoKeywords")})}
  if(!data)return <div className="modal-backdrop"><section className="product-editor"><div className="admin-loading">جاري تحميل البيانات التجارية...</div></section></div>;
  const margin=data.basePrice?((data.basePrice-data.costPrice)/data.basePrice)*100:0;
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="product-editor commercial-editor"><header><div><h2>الإعدادات التجارية — {data.name}</h2><p>{data.sku} · التكلفة والعبوات والأسعار الخاصة والمنتجات المرتبطة</p></div><button onClick={onClose}>×</button></header><nav className="content-tabs"><button className={tab==="commercial"?"active":""} onClick={()=>setTab("commercial")}>التكلفة والـSEO</button><button className={tab==="links"?"active":""} onClick={()=>setTab("links")}>البدائل والمرتبطة</button><button className={tab==="companies"?"active":""} onClick={()=>setTab("companies")}>أسعار الشركات</button></nav><div className="content-editor-body">
    {tab==="commercial"&&<form className="commercial-form" onSubmit={commercial}><section className="commercial-kpis"><article><span>سعر البيع</span><b>{data.basePrice.toLocaleString("ar-EG")} ج.م</b></article><article><span>التكلفة</span><b>{data.costPrice.toLocaleString("ar-EG")} ج.م</b></article><article className={margin<10?"danger":""}><span>هامش الربح</span><b>{margin.toFixed(1)}%</b></article><article><span>وحدات الكرتونة</span><b>{data.unitsPerPackage*data.packagesPerCarton}</b></article></section><div className="form-grid"><label>تكلفة المنتج<input name="costPrice" type="number" min="0" step="0.01" defaultValue={data.costPrice}/></label><label>نوع العبوة<input name="packageType" defaultValue={data.packageType}/></label><label>وحدات داخل العبوة<input name="unitsPerPackage" type="number" min="1" defaultValue={data.unitsPerPackage}/></label><label>عبوات داخل الكرتونة<input name="packagesPerCarton" type="number" min="1" defaultValue={data.packagesPerCarton}/></label><label>باركود الكرتونة<input name="cartonBarcode" defaultValue={data.cartonBarcode}/></label><label className="full-field">الضمان<input name="warranty" defaultValue={data.warranty}/></label><label className="full-field">عنوان SEO<input name="seoTitle" maxLength={180} defaultValue={data.seoTitle}/></label><label className="full-field">وصف SEO<textarea name="seoDescription" maxLength={500} defaultValue={data.seoDescription}/></label><label className="full-field">الكلمات المفتاحية<input name="seoKeywords" defaultValue={data.seoKeywords}/></label></div><div className="content-actions"><button className="primary-button" disabled={saving}>حفظ البيانات التجارية</button></div></form>}
    {tab==="links"&&<><div className="editable-list">{data.links.map((link,index)=><div className="editable-row link-row" key={`${link.productId}-${link.type}`}><label>المنتج<select value={link.productId} onChange={e=>setData({...data,links:data.links.map((x,i)=>i===index?{...x,productId:e.target.value}:x)})}>{data.products.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select></label><label>النوع<select value={link.type} onChange={e=>setData({...data,links:data.links.map((x,i)=>i===index?{...x,type:e.target.value}:x)})}><option value="Alternative">منتج بديل</option><option value="Related">منتج مرتبط</option></select></label><button className="danger-outline" onClick={()=>setData({...data,links:data.links.filter((_,i)=>i!==index)})}>حذف</button></div>)}</div><button className="secondary-button list-add" onClick={()=>{const first=data.products.find(p=>!data.links.some(x=>x.productId===p.id&&x.type==="Related"));if(first)setData({...data,links:[...data.links,{productId:first.id,sku:first.sku,name:first.name,type:"Related",sortOrder:data.links.length}]})}}>+ إضافة منتج مرتبط</button><div className="content-actions"><button className="primary-button" disabled={saving} onClick={()=>put("links",{links:data.links.map((x,i)=>({productId:x.productId,type:x.type,sortOrder:i}))})}>حفظ الروابط</button></div></>}
    {tab==="companies"&&<><div className="editable-list">{data.companyPrices.map((price,index)=><div className="company-price-row" key={`${price.tenantId}-${index}`}><label>الشركة<select value={price.tenantId} onChange={e=>setData({...data,companyPrices:data.companyPrices.map((x,i)=>i===index?{...x,tenantId:e.target.value}:x)})}>{data.companies.map(c=><option key={c.tenantId} value={c.tenantId}>{c.name}</option>)}</select></label><label>السعر الخاص<input type="number" min="0.01" step="0.01" value={price.price} onChange={e=>setData({...data,companyPrices:data.companyPrices.map((x,i)=>i===index?{...x,price:Number(e.target.value)}:x)})}/></label><label>من<input type="date" value={price.validFrom?.slice(0,10)??""} onChange={e=>setData({...data,companyPrices:data.companyPrices.map((x,i)=>i===index?{...x,validFrom:e.target.value||undefined}:x)})}/></label><label>إلى<input type="date" value={price.validTo?.slice(0,10)??""} onChange={e=>setData({...data,companyPrices:data.companyPrices.map((x,i)=>i===index?{...x,validTo:e.target.value||undefined}:x)})}/></label><button className="danger-outline" onClick={()=>setData({...data,companyPrices:data.companyPrices.filter((_,i)=>i!==index)})}>حذف</button></div>)}</div><button className="secondary-button list-add" onClick={()=>{const first=data.companies.find(c=>!data.companyPrices.some(x=>x.tenantId===c.tenantId));if(first)setData({...data,companyPrices:[...data.companyPrices,{tenantId:first.tenantId,company:first.name,price:data.basePrice}]})}}>+ سعر شركة</button><div className="content-actions"><button className="primary-button" disabled={saving} onClick={()=>put("company-prices",{prices:data.companyPrices.map(x=>({tenantId:x.tenantId,price:x.price,validFrom:x.validFrom?new Date(x.validFrom).toISOString():null,validTo:x.validTo?new Date(x.validTo).toISOString():null}))})}>حفظ أسعار الشركات</button></div></>}
  </div></section></div>
}
