"use client";

import {type FormEvent,useEffect,useMemo,useState} from "react";
import type {Designer,PrintingDashboard,PrintingDetail,PrintingRow,PrintTemplate} from "./printing-types";

const date=(v?:string)=>v?new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium"}).format(new Date(v)):"—";
const money=new Intl.NumberFormat("ar-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0});
const labels:Record<string,string>={DesignInProgress:"قيد التصميم",AwaitingDesignApproval:"بانتظار العميل",DesignApproved:"التصميم معتمد",AwaitingSampleApproval:"بانتظار اعتماد العينة",InProduction:"قيد الإنتاج",QualityCheck:"فحص الجودة",Ready:"جاهز للشحن",Completed:"مكتمل",Rejected:"مرفوض",Cancelled:"ملغي",Pending:"قيد الانتظار",InProgress:"قيد التنفيذ",Approved:"معتمد",RevisionRequested:"تعديل مطلوب"};
const tr=(x:string)=>labels[x]||x;
async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,cache:"no-store"});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.title||e.message||"تعذر تنفيذ العملية")}return r.status===204?undefined as T:r.json()}
type MainView="requests"|"late"|"archive"|"logos"|"templates";
type DetailTab="overview"|"logos"|"designs"|"sample"|"production"|"history";

export function PrintingManager(){
 const[data,setData]=useState<PrintingDashboard|null>(null),[detail,setDetail]=useState<PrintingDetail|null>(null),[view,setView]=useState<MainView>("requests"),[tab,setTab]=useState<DetailTab>("overview"),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>setData(await api("/api/admin/printing"));
 const open=async(id:string)=>{setBusy(true);try{setDetail(await api(`/api/admin/printing/requests/${id}`));setTab("overview")}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const refresh=async()=>{await load();if(detail)await open(detail.request.id)};
 async function mutate(url:string,body:unknown,method="POST"){setBusy(true);setError("");try{await api(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{let active=true;api<PrintingDashboard>("/api/admin/printing").then(x=>active&&setData(x)).catch(e=>active&&setError((e as Error).message));return()=>{active=false}},[]);
 const rows=useMemo(()=>{let list=data?.requests||[];if(view==="late")list=list.filter(x=>x.isLate);if(view==="archive")list=list.filter(x=>["Ready","Completed","Rejected","Cancelled"].includes(x.status));return list.filter(x=>(!query||`${x.number} ${x.company} ${x.product}`.toLowerCase().includes(query.toLowerCase()))&&(!status||x.status===status))},[data,query,status,view]);
 if(!data)return <div className="printing-loading">{error||"جاري تحميل لوحة الطباعة..."}</div>;
 if(detail)return <><PrintingWorkspace detail={detail} designers={data.designers} tab={tab} setTab={setTab} back={()=>setDetail(null)} busy={busy} mutate={mutate} refresh={refresh} fail={setError}/>{error&&<Alert text={error}/>}</>;
 return <section className="printing-page"><header className="printing-heading"><div><span className="eyebrow">إدارة المنتجات المطبوعة</span><h1>لوحة طلبات الطباعة</h1><p>التصميم والعينات والإنتاج والجودة في مساحة تشغيل واحدة</p></div><nav><button className={view==="requests"?"active":""} onClick={()=>setView("requests")}>الطلبات</button><button className={view==="late"?"active":""} onClick={()=>setView("late")}>المتأخرة</button><button className={view==="archive"?"active":""} onClick={()=>setView("archive")}>الأرشيف</button><button className={view==="logos"?"active":""} onClick={()=>setView("logos")}>مكتبة الشعارات</button><button className={view==="templates"?"active":""} onClick={()=>setView("templates")}>القوالب</button></nav></header>{error&&<Alert text={error}/>}<div className="printing-kpis"><Kpi label="طلبات تصميم نشطة" value={data.kpis.activeDesigns} icon="✎"/><Kpi label="قيد الإنتاج" value={data.kpis.inProduction} icon="▣"/><Kpi label="بانتظار العميل" value={data.kpis.waitingCustomer} icon="◷"/><Kpi label="متأخرة" value={data.kpis.late} icon="△" danger/></div>{view==="templates"?<Templates rows={data.templates} busy={busy} save={(id,b)=>void mutate(`/api/admin/printing/templates/${id}`,b,"PUT")}/>:view==="logos"?<LogoLibrary data={data} open={open}/>:<><section className="printing-main-grid"><RequestTable rows={rows} query={query} status={status} setQuery={setQuery} setStatus={setStatus} open={open}/><DesignerLoad rows={data.designers}/></section></>}</section>
}

function Kpi({label,value,icon,danger}:{label:string;value:number;icon:string;danger?:boolean}){return <article className={`panel printing-kpi ${danger?"danger":""}`}><i>{icon}</i><span>{label}</span><b>{value}</b></article>}
function Alert({text}:{text:string}){return <div className="printing-alert">{text}</div>}
function RequestTable({rows,query,status,setQuery,setStatus,open}:{rows:PrintingRow[];query:string;status:string;setQuery:(x:string)=>void;setStatus:(x:string)=>void;open:(id:string)=>void}){return <section className="panel printing-list"><header><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث برقم الطلب أو الشركة..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل المراحل</option>{["DesignInProgress","AwaitingDesignApproval","AwaitingSampleApproval","InProduction","QualityCheck","Ready"].map(x=><option key={x} value={x}>{tr(x)}</option>)}</select><span>{rows.length} طلب</span></header><div className="printing-table"><div><b>الطلب</b><b>الشركة والمنتج</b><b>المصمم</b><b>المرحلة</b><b>التقدم</b><b>الموعد</b></div>{rows.map(x=><button key={x.id} onClick={()=>open(x.id)}><strong>{x.number}</strong><span><b>{x.company}</b><small>{x.product} × {x.quantity}</small></span><span>{x.designer||"غير مخصص"}</span><u className={`print-status ${x.status.toLowerCase()}`}>{tr(x.status)}</u><i><em style={{width:`${x.progressPercent}%`}}/><small>{x.progressPercent}%</small></i><span className={x.isLate?"late":""}>{date(x.dueAt)}</span></button>)}</div></section>}
function DesignerLoad({rows}:{rows:Designer[]}){return <aside className="panel designer-load"><h3>عبء المصممين</h3>{rows.map(x=><article key={x.id}><i>{x.name.slice(0,1)}</i><div><b>{x.name}</b><span>{x.specialty}</span><em><u style={{width:`${Math.min(100,x.activeWorkload*12)}%`}}/></em></div><strong>{x.activeWorkload}</strong></article>)}{rows.length===0&&<p>أضف مستخدمًا بدور مصمم جرافيك.</p>}</aside>}
function LogoLibrary({data,open}:{data:PrintingDashboard;open:(id:string)=>void}){return <section className="panel logo-library"><header><h3>مكتبة شعارات الشركات</h3><span>{data.logos.length} ملفًا محفوظًا</span></header><div>{data.logos.map(x=><article key={x.id}><i>{x.name.split(".").pop()?.toUpperCase()}</i><h4>{x.company}</h4><p>{x.name}</p><span className={`print-status ${x.qualityStatus.toLowerCase()}`}>{tr(x.qualityStatus)} {x.qualityScore?`· ${x.qualityScore}%`:""}</span><footer><a href={x.downloadUrl} target="_blank">فتح الملف</a><button onClick={()=>open(x.requestId)}>فتح الطلب</button></footer></article>)}</div></section>}
function Templates({rows,busy,save}:{rows:PrintTemplate[];busy:boolean;save:(id:string,body:unknown)=>void}){const[editing,setEditing]=useState<PrintTemplate|null>(null);return <><section className="template-grid">{rows.map(x=><article className="panel" key={x.id}><i>▱</i><h3>{x.name}</h3><p>{x.sku} · {x.printMethods} طرق طباعة · {x.placements} مواضع</p><strong>{money.format(x.startingPrice+x.setupFee)}+</strong><span>حد أدنى {x.minQuantity} · {x.leadTimeDays} أيام</span><button onClick={()=>setEditing(x)}>تعديل</button></article>)}</section>{editing&&<TemplateEditor row={editing} busy={busy} close={()=>setEditing(null)} save={b=>{save(editing.id,b);setEditing(null)}}/>}</>}
function TemplateEditor({row,busy,close,save}:{row:PrintTemplate;busy:boolean;close:()=>void;save:(b:unknown)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);save({name:f.get("name"),description:f.get("description"),setupFee:Number(f.get("setup")),minQuantity:Number(f.get("min")),leadTimeDays:Number(f.get("days")),isActive:f.get("active")==="on"})}return <div className="modal-backdrop"><section className="print-modal"><header><h2>تعديل قالب الطباعة</h2><button onClick={close}>×</button></header><form onSubmit={submit}><label>اسم القالب<input name="name" defaultValue={row.name} required/></label><label>الوصف<textarea name="description" defaultValue={row.description}/></label><div><label>رسوم التجهيز<input name="setup" type="number" defaultValue={row.setupFee}/></label><label>الحد الأدنى<input name="min" type="number" defaultValue={row.minQuantity}/></label><label>مدة التنفيذ<input name="days" type="number" defaultValue={row.leadTimeDays}/></label></div><label className="check"><input name="active" type="checkbox" defaultChecked={row.isActive}/> القالب نشط</label><footer><button type="button" onClick={close}>إلغاء</button><button className="primary-button" disabled={busy}>حفظ</button></footer></form></section></div>}

function PrintingWorkspace({detail,designers,tab,setTab,back,busy,mutate,refresh,fail}:{detail:PrintingDetail;designers:Designer[];tab:DetailTab;setTab:(x:DetailTab)=>void;back:()=>void;busy:boolean;mutate:(u:string,b:unknown,m?:string)=>Promise<void>;refresh:()=>Promise<void>;fail:(x:string)=>void}){const r=detail.request;return <section className="printing-page"><button className="back-link" onClick={back}>→ العودة إلى طلبات الطباعة</button><header className="panel print-request-head"><div><span className="eyebrow">{r.company}</span><h1>{r.number}</h1><p>{r.product} × {r.quantity} · {detail.printMethod}</p></div><u className={`print-status ${r.status.toLowerCase()}`}>{tr(r.status)}</u><Assign detail={detail} designers={designers} busy={busy} mutate={mutate}/></header><nav className="print-tabs">{([['overview','الملخص'],['logos','الشعارات'],['designs','التصاميم'],['sample','العينة'],['production','الإنتاج والجودة'],['history','السجل']] as [DetailTab,string][]).map(([x,l])=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{l}</button>)}</nav>{tab==="overview"&&<Overview d={detail}/>} {tab==="logos"&&<Logos d={detail} busy={busy} mutate={mutate}/>} {tab==="designs"&&<Designs d={detail} busy={busy} mutate={mutate} refresh={refresh} fail={fail}/>} {tab==="sample"&&<Samples d={detail} busy={busy} refresh={refresh} fail={fail}/>} {tab==="production"&&<Production d={detail} busy={busy} mutate={mutate}/>} {tab==="history"&&<History d={detail} busy={busy} mutate={mutate}/>}</section>}
function Assign({detail,designers,busy,mutate}:{detail:PrintingDetail;designers:Designer[];busy:boolean;mutate:(u:string,b:unknown,m?:string)=>Promise<void>}){const[designer,setDesigner]=useState(detail.request.designerId||""),[due,setDue]=useState(()=>(detail.request.dueAt||new Date(Date.now()+3*86400000).toISOString()).slice(0,10));return <div className="assign-box"><select value={designer} onChange={e=>setDesigner(e.target.value)}><option value="">اختر المصمم</option>{designers.map(x=><option key={x.id} value={x.id}>{x.name} · {x.activeWorkload} طلبات</option>)}</select><input type="date" value={due} onChange={e=>setDue(e.target.value)}/><button disabled={busy||!designer} onClick={()=>void mutate(`/api/admin/printing/requests/${detail.request.id}/designer`,{designerId:designer,dueAt:new Date(`${due}T18:00:00`).toISOString(),note:"تخصيص من لوحة الطباعة"},"PUT")}>تخصيص</button></div>}
function Overview({d}:{d:PrintingDetail}){return <div className="print-detail-grid"><section className="panel print-card"><Title text="تعليمات العميل"/><p className="customer-note">{d.customerNote||d.brief?.objective||"لا توجد تعليمات إضافية"}</p><dl><Pair k="الهدف" v={d.brief?.objective}/><Pair k="الجمهور" v={d.brief?.audience}/><Pair k="الألوان" v={d.brief?.preferredColors}/><Pair k="النص المطلوب" v={d.brief?.requiredText}/></dl></section><section className="panel print-card"><Title text="المواصفات"/><dl><Pair k="المنتج" v={d.request.product}/><Pair k="الكمية" v={String(d.request.quantity)}/><Pair k="الطباعة" v={d.printMethod}/><Pair k="الموضع" v={d.placement}/><Pair k="الخامة" v={d.material}/><Pair k="اللون والمقاس" v={`${d.color} · ${d.size}`}/><Pair k="أبعاد الطباعة" v={`${d.printWidthCm} × ${d.printHeightCm} سم`}/><Pair k="عدد الألوان" v={String(d.printColorCount)}/></dl></section></div>}
function Logos({d,busy,mutate}:{d:PrintingDetail;busy:boolean;mutate:(u:string,b:unknown,m?:string)=>Promise<void>}){const logos=d.assets.filter(x=>!x.isDesignFile);return <section className="panel print-card"><Title text="ملفات الشعار ومراجعة الجودة"/>{logos.map(x=><article className="logo-review" key={x.id}><i>{x.name.split(".").pop()?.toUpperCase()}</i><div><b>{x.name}</b><span>{(x.sizeBytes/1024/1024).toFixed(1)} MB · {tr(x.qualityStatus)}</span><small>{x.reviewNote||"لم تتم المراجعة بعد"}</small></div><a href={x.downloadUrl} target="_blank">فتح</a><button disabled={busy} onClick={()=>void mutate(`/api/admin/printing/requests/${d.request.id}/logos/${x.id}/quality`,{approve:true,score:95,isVector:x.contentType.includes("illustrator"),hasTransparentBackground:true,isCmykReady:true,hasSufficientResolution:true,hasSimpleEffects:true,note:"مراجعة ناجحة وجاهز للطباعة"},"PUT")}>اعتماد الجودة</button></article>)}</section>}
function Designs({d,busy,mutate,refresh,fail}:{d:PrintingDetail;busy:boolean;mutate:(u:string,b:unknown,m?:string)=>Promise<void>;refresh:()=>Promise<void>;fail:(x:string)=>void}){const latest=d.versions[0];async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const file=f.get("file") as File;if(!file?.size)return;try{const r=await fetch(`/api/admin/custom-products/requests/${d.request.id}/design-versions`,{method:"POST",body:f});if(!r.ok){const x=await r.json();throw new Error(x.title)}await refresh()}catch(e){fail((e as Error).message)}}return <div className="print-detail-grid"><section className="panel print-card"><Title text="نسخ التصميم"/>{d.versions.map(x=><article className="design-version" key={x.id}><div className="mockup">{x.mockups[0]?<a href={x.mockups[0].downloadUrl} target="_blank">معاينة v{x.number}</a>:"لا توجد معاينة"}</div><div><b>v{x.number} · {x.title}</b><span>{x.designer} · {date(x.createdAt)}</span><p>{x.changeSummary||"التصميم الأولي"}</p></div><u>{x.sentToCustomerAt?`أُرسل ${date(x.sentToCustomerAt)}`:"داخلي"}</u></article>)}{latest&&<button className="primary-button" disabled={busy||!!latest.sentToCustomerAt} onClick={()=>void mutate(`/api/admin/printing/requests/${d.request.id}/send-design`,{versionId:latest.id,message:"النسخة جاهزة للمراجعة والاعتماد"})}>إرسال أحدث نسخة للعميل</button>}</section><section className="panel print-card"><Title text={latest?"رفع نسخة معدلة":"رفع التصميم الأولي"}/><form className="upload-form" onSubmit={upload}><label>عنوان النسخة<input name="title" defaultValue={latest?`نسخة معدلة v${latest.number+1}`:"التصميم الأولي"} required/></label><label>ملخص التعديلات<textarea name="changeSummary"/></label><label className="file-drop">PDF أو PNG حتى 20MB<input name="file" type="file" accept="image/png,image/jpeg,application/pdf" required/></label><button className="primary-button" disabled={busy}>رفع التصميم</button></form></section></div>}
function Samples({d,busy,refresh,fail}:{d:PrintingDetail;busy:boolean;refresh:()=>Promise<void>;fail:(x:string)=>void}){async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await fetch(`/api/admin/custom-products/requests/${d.request.id}/samples`,{method:"POST",body:f});if(!r.ok){const x=await r.json();throw new Error(x.title)}await refresh()}catch(e){fail((e as Error).message)}}return <div className="print-detail-grid"><section className="panel print-card"><Title text="عينات الإنتاج"/>{d.production?.samples.map(x=><article className="sample-row" key={x.id}><a href={x.downloadUrl} target="_blank">SMP-v{x.version}</a><div><b>{x.name}</b><span>{tr(x.decision)} · {date(x.createdAt)}</span><p>{x.decisionNote||x.note}</p></div></article>)}{!d.production&&<p className="empty-state">أمر الإنتاج لم يُنشأ بعد</p>}</section><section className="panel print-card"><Title text="رفع صور العينة"/><form className="upload-form" onSubmit={upload}><label>ملاحظة<textarea name="note" defaultValue="عينة فعلية قبل بدء الإنتاج الكمي"/></label><label className="file-drop">صورة العينة<input name="file" type="file" accept="image/*" required/></label><button className="primary-button" disabled={busy||!d.production}>رفع وإرسال العينة</button></form></section></div>}
function Production({d,busy,mutate}:{d:PrintingDetail;busy:boolean;mutate:(u:string,b:unknown,m?:string)=>Promise<void>}){const p=d.production;if(!p)return <section className="panel print-card"><p className="empty-state">يبدأ أمر الإنتاج بعد اعتماد التصميم وإتمام الطلب التجاري.</p></section>;const canStart=p.samples[0]?.decision==="Approved"&&!p.actualStart;return <div className="print-detail-grid production-grid"><section className="panel print-card full"><header className="production-head"><div><Title text={`متابعة الإنتاج · ${p.number}`}/><p>{p.producedQuantity}/{p.targetQuantity} قطعة</p></div><i><em style={{width:`${Math.min(100,p.producedQuantity/p.targetQuantity*100)}%`}}/></i>{canStart&&<button className="primary-button" onClick={()=>void mutate(`/api/admin/printing/requests/${d.request.id}/start-production`,{scheduledStart:new Date().toISOString(),estimatedCompletion:new Date(Date.now()+4*86400000).toISOString()})}>بدء الإنتاج</button>}</header><div className="production-stages">{p.stages.map((x,i)=><article key={x.id}><i className={x.status.toLowerCase()}>{x.status==="Completed"?"✓":i+1}</i><div><b>{x.name}</b><span>{tr(x.status)} {x.completedAt?`· ${date(x.completedAt)}`:""}</span></div>{x.status!=="Completed"&&<button disabled={busy||!p.actualStart} onClick={()=>void mutate(`/api/admin/printing/requests/${d.request.id}/stages/${x.id}`,{status:"Completed",producedQuantity:p.targetQuantity,note:"تمت المرحلة بنجاح"},"PUT")}>إكمال</button>}</article>)}</div></section><Packaging d={d} busy={busy} mutate={mutate}/><Quality d={d} busy={busy} mutate={mutate}/></div>}
function Packaging({d,busy,mutate}:{d:PrintingDetail;busy:boolean;mutate:(u:string,b:unknown,m?:string)=>Promise<void>}){const p=d.production!;const[type,setType]=useState(p.packagingType||"علب كرتون محكمة"),[units,setUnits]=useState(p.unitsPerPackage||20),[count,setCount]=useState(p.packageCount||Math.ceil(p.targetQuantity/20));return <section className="panel print-card"><Title text="التغليف"/><label>نوع التغليف<input value={type} onChange={e=>setType(e.target.value)}/></label><div className="form-cols"><label>قطعة/عبوة<input type="number" value={units} onChange={e=>setUnits(Number(e.target.value))}/></label><label>عدد العبوات<input type="number" value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div><button className="secondary-button" disabled={busy} onClick={()=>void mutate(`/api/admin/printing/requests/${d.request.id}/packaging`,{packagingType:type,unitsPerPackage:units,packageCount:count},"PUT")}>حفظ التغليف</button>{p.stages.every(x=>x.status==="Completed")&&<button className="primary-button" onClick={()=>void mutate(`/api/admin/printing/requests/${d.request.id}/ready`,{dispatchReference:"SHP-PENDING"})}>جاهز للشحن</button>}</section>}
function Quality({d,busy,mutate}:{d:PrintingDetail;busy:boolean;mutate:(u:string,b:unknown,m?:string)=>Promise<void>}){const p=d.production!;return <section className="panel print-card"><Title text="مراقبة الجودة"/>{p.qualityChecks.map(x=><article className="quality-row" key={x.id}><i>{x.passed?"✓":"!"}</i><div><b>{x.name}</b><span>{x.inspector} · {date(x.checkedAt)}</span></div></article>)}<button className="secondary-button" disabled={busy} onClick={()=>void mutate(`/api/admin/custom-products/requests/${d.request.id}/quality-checks`,{nameAr:"مطابقة الألوان والطباعة والتشطيب",passed:true,note:"الفحص مطابق للمواصفات"})}>تسجيل فحص ناجح</button></section>}
function History({d,busy,mutate}:{d:PrintingDetail;busy:boolean;mutate:(u:string,b:unknown,m?:string)=>Promise<void>}){const[text,setText]=useState("");const events=[...d.comments.map(x=>({at:x.createdAt,title:x.isInternal?"ملاحظة داخلية":"رسالة للعميل",body:`${x.author}: ${x.body}`})),...d.approvals.map(x=>({at:x.createdAt,title:`قرار العميل على v${x.version}`,body:`${tr(x.decision)} · ${x.customer} · ${x.note||""}`}))].sort((a,b)=>+new Date(b.at)-+new Date(a.at));return <div className="print-detail-grid"><section className="panel print-card"><Title text="سجل الاعتمادات والتواصل"/>{events.map((x,i)=><article className="history-row" key={i}><i/><div><b>{x.title}</b><p>{x.body}</p><span>{date(x.at)}</span></div></article>)}</section><section className="panel print-card"><Title text="إضافة ملاحظة داخلية"/><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="لا تظهر للعميل"/><button className="primary-button" disabled={busy||!text.trim()} onClick={()=>{void mutate(`/api/admin/printing/requests/${d.request.id}/internal-comments`,{body:text});setText("")}}>إضافة للسجل</button></section></div>}
function Title({text}:{text:string}){return <header className="print-title"><h3>{text}</h3></header>}
function Pair({k,v}:{k:string;v?:string}){return <div><dt>{k}</dt><dd>{v||"—"}</dd></div>}
