"use client";

import {type FormEvent,useEffect,useState} from "react";
import base from "../operations.module.css";
import styles from "./integrations.module.css";
import type {ActionResult,IntegrationDashboard,IntegrationDetail,IntegrationOperation,OperationsPage} from "./integration-types";

type View="hub"|"detail"|"logs"|"failure"|"retry";
async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,cache:"no-store"});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.title||body.message||"تعذر تنفيذ العملية")}return response.status===204?undefined as T:response.json()}
const send=(method:string,body?:unknown):RequestInit=>({method,headers:body===undefined?undefined:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});
const date=new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium",timeStyle:"short"});

export function IntegrationsManager(){
 const[data,setData]=useState<IntegrationDashboard|null>(null),[view,setView]=useState<View>("hub"),[detail,setDetail]=useState<IntegrationDetail|null>(null),[operations,setOperations]=useState<OperationsPage|null>(null),[selected,setSelected]=useState<IntegrationOperation|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>setData(await api("/api/admin/integrations"));
 useEffect(()=>{let live=true;api<IntegrationDashboard>("/api/admin/integrations").then(x=>live&&setData(x)).catch(e=>live&&setError((e as Error).message));return()=>{live=false}},[]);
 async function run<T>(work:()=>Promise<T>,message?:string){setBusy(true);setError("");try{const result=await work();await load();if(message){setNotice(message);setTimeout(()=>setNotice(""),2600)}return result}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function openDetail(code:string){setBusy(true);try{setDetail(await api(`/api/admin/integrations/connections/${code}`));setView("detail")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function openLogs(){setBusy(true);try{setOperations(await api("/api/admin/integrations/operations?pageSize=50"));setView("logs")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function openRetry(){setBusy(true);try{setOperations(await api("/api/admin/integrations/operations?status=Failed&pageSize=100"));setView("retry")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function openFailure(row:IntegrationOperation){setSelected(await api(`/api/admin/integrations/operations/${row.id}`));setView("failure")}
 async function refreshDetail(code:string){setDetail(await api(`/api/admin/integrations/connections/${code}`))}
 if(!data)return <p className={base.empty}>{error||"جاري تحميل مركز التكاملات..."}</p>;
 return <section className={styles.page}>
  <Header view={view} detail={detail} back={()=>{setView("hub");setDetail(null);setSelected(null)}} logs={()=>void openLogs()} retry={()=>void openRetry()}/>
  {view==="hub"&&<Hub data={data} open={x=>void openDetail(x)} logs={()=>void openLogs()} retry={()=>void openRetry()}/>} 
  {view==="detail"&&detail&&<Detail detail={detail} busy={busy} save={async values=>{await run(()=>api(`/api/admin/integrations/connections/${detail.integration.code}`,send("PUT",{values})),"تم حفظ بيانات التكامل");await refreshDetail(detail.integration.code)}} test={async()=>{const result=await run(()=>api<ActionResult>(`/api/admin/integrations/connections/${detail.integration.code}/test`,send("POST")));if(result){setNotice(result.messageAr);await refreshDetail(detail.integration.code)}}} sync={async()=>{const result=await run(()=>api<ActionResult>(`/api/admin/integrations/connections/${detail.integration.code}/run`,send("POST",{})));if(result){setNotice(result.messageAr);await refreshDetail(detail.integration.code)}}} disable={async()=>{if(!confirm("تعطيل هذا التكامل مؤقتًا؟"))return;await run(()=>api(`/api/admin/integrations/connections/${detail.integration.code}/disable`,send("POST")),"تم تعطيل التكامل");await refreshDetail(detail.integration.code)}} failure={x=>void openFailure(x)}/>} 
  {view==="logs"&&operations&&<Logs page={operations} data={data} search={async query=>{setBusy(true);try{setOperations(await api(`/api/admin/integrations/operations?${query}`))}finally{setBusy(false)}}} open={x=>void openFailure(x)} exportCsv={()=>exportOperations(operations.items)}/>} 
  {view==="failure"&&selected&&<Failure row={selected} busy={busy} retry={async()=>{const result=await run(()=>api<ActionResult>(`/api/admin/integrations/operations/${selected.id}/retry`,send("POST")));if(result){setSelected(result.operation);setNotice(result.messageAr)}}} disable={async()=>{await run(()=>api(`/api/admin/integrations/connections/${selected.integrationCode}/disable`,send("POST")),"تم تعطيل التكامل مؤقتًا")}}/>} 
  {view==="retry"&&operations&&<Retry page={operations} busy={busy} open={x=>void openFailure(x)} retry={async x=>{const result=await run(()=>api<ActionResult>(`/api/admin/integrations/operations/${x.id}/retry`,send("POST")));if(result)setNotice(result.messageAr);await openRetry()}} all={async()=>{const count=await run(()=>api<number>("/api/admin/integrations/operations/retry-all",send("POST")));setNotice(`نجحت ${count??0} عملية من المحاولات القابلة للتنفيذ`);await openRetry()}}/>}
  {busy&&<div className={styles.busy}>جاري التنفيذ...</div>}{error&&<div className={base.alert} onClick={()=>setError("")}>{error}</div>}{notice&&<div className={styles.notice}>✓ {notice}</div>}
 </section>
}

function Header({view,detail,back,logs,retry}:{view:View;detail:IntegrationDetail|null;back:()=>void;logs:()=>void;retry:()=>void}){const titles:Record<View,[string,string]>={hub:["مركز التكاملات","Integrations Hub"],detail:[detail?.integration.nameAr||"تفاصيل التكامل",detail?.integration.nameEn||"Integration Details"],logs:["سجل عمليات التكامل","Integration Operations Log"],failure:["فشل عملية تكامل","Integration Failure"],retry:["إعادة محاولة التكاملات","Retry Integrations"]};return <header className={styles.hero}><div>{view!=="hub"&&<button onClick={back}>→ العودة للمركز</button>}<span>النظام / التكاملات</span><h1>{titles[view][0]}</h1><p>{titles[view][1]}</p></div><nav><button onClick={logs}>سجل العمليات</button><button onClick={retry}>المحاولات الفاشلة</button></nav></header>}
function Hub({data,open,logs,retry}:{data:IntegrationDashboard;open:(x:string)=>void;logs:()=>void;retry:()=>void}){return <><section className={styles.summary}><article><i>↗</i><span>إجمالي التكاملات</span><b>{data.summary.total}</b></article><article><i>✓</i><span>متصلة ونشطة</span><b>{data.summary.connected}</b></article><article><i>×</i><span>غير متصلة</span><b>{data.summary.disconnected}</b></article><article onClick={retry}><i>↻</i><span>قابلة لإعادة المحاولة</span><b>{data.summary.retryable}</b></article></section><div className={styles.hubHead}><div><h2>كل التكاملات</h2><p>إدارة الربط والحالة والأداء من مكان واحد</p></div><button className={base.secondary} onClick={logs}>عرض السجل الكامل</button></div><section className={styles.cards}>{data.integrations.map(x=><article key={x.code}><header><i className={styles[x.tone]}>{x.icon}</i><div><h3>{x.nameAr}</h3><small>{x.provider}</small></div><u className={x.isConnected&&x.isEnabled?styles.connected:styles.disconnected}>{x.status}</u></header><p>{x.descriptionAr}</p><div><span>{x.operationsToday} عملية اليوم</span><span>{x.successRate?`${x.successRate}% نجاح`:"لا توجد عمليات"}</span></div><footer><button className={base.primary} onClick={()=>open(x.code)}>إعداد</button><button className={base.secondary} onClick={logs}>سجل</button></footer></article>)}</section></>}
function Detail({detail,busy,save,test,sync,disable,failure}:{detail:IntegrationDetail;busy:boolean;save:(x:Record<string,string>)=>void;test:()=>void;sync:()=>void;disable:()=>void;failure:(x:IntegrationOperation)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),values:Record<string,string>={};detail.fields.forEach(x=>values[x.code]=x.type==="boolean"?String(f.get(x.code)==="on"):String(f.get(x.code)||""));save(values)}return <><section className={styles.detailTitle}><div className={`${styles.detailIcon} ${styles[detail.integration.tone]}`}>{detail.integration.icon}</div><div><h2>تكامل {detail.integration.nameAr}</h2><p>{detail.integration.descriptionAr}</p></div><u className={detail.integration.isConnected?styles.connected:styles.disconnected}>{detail.integration.status}</u></section><div className={styles.detailGrid}><section className={base.panel}><header className={base.panelHead}><div><h2>الإعداد</h2><span>بيانات الربط محفوظة بصورة مشفرة</span></div></header><form className={styles.form} onSubmit={submit}>{detail.fields.map(x=><label key={x.code}><span>{x.labelAr}{x.required&&" *"}</span>{x.type==="select"?<select name={x.code} defaultValue={detail.values[x.code]}>{x.options.map(o=><option key={o}>{o}</option>)}</select>:x.type==="boolean"?<input name={x.code} type="checkbox" defaultChecked={detail.values[x.code]==="true"}/>:<input name={x.code} dir={["url","email","password","number","date"].includes(x.type)?"ltr":undefined} type={x.type==="password"?"password":x.type==="url"?"url":x.type==="email"?"email":x.type==="number"?"number":x.type==="date"?"date":"text"} required={x.required} defaultValue={detail.values[x.code]}/>} {x.help&&<small>{x.help}</small>}</label>)}<footer><button className={base.secondary} type="button" disabled={busy} onClick={test}>اختبار الاتصال</button><button className={base.primary} disabled={busy}>حفظ الإعدادات</button></footer></form></section><aside className={styles.side}><section className={base.panel}><header className={base.panelHead}><div><h3>الحالة والأداء</h3><span>من البيانات التشغيلية الحالية</span></div></header><div className={styles.metrics}>{detail.metrics.map(x=><article key={x.labelAr}><span>{x.labelAr}</span><b>{x.value}</b><small>{x.hint}</small></article>)}</div></section><div className={styles.actionBox}><button className={base.primary} disabled={busy||!detail.integration.isConnected} onClick={sync}>مزامنة / تشغيل الآن</button><button className={base.danger} disabled={busy||!detail.integration.isEnabled} onClick={disable}>تعطيل مؤقت</button></div></aside></div><section className={base.panel}><header className={base.panelHead}><div><h2>أحدث العمليات</h2><span>آخر 20 عملية لهذا التكامل</span></div></header><OperationsTable rows={detail.recentOperations} open={failure}/></section></>}
function Logs({page,data,search,open,exportCsv}:{page:OperationsPage;data:IntegrationDashboard;search:(x:string)=>void;open:(x:IntegrationOperation)=>void;exportCsv:()=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),q=new URLSearchParams({pageSize:"50"});for(const key of ["search","integration","status","from","to"]){const value=String(f.get(key)||"");if(value)q.set(key,value)}search(q.toString())}return <section className={base.panel}><header className={base.panelHead}><div><h2>سجل عمليات التكامل</h2><span>{page.total.toLocaleString("ar-EG")} عملية مطابقة</span></div><button className={base.secondary} onClick={exportCsv}>تصدير CSV</button></header><form className={styles.filters} onSubmit={submit}><input name="search" placeholder="بحث بالعملية أو المرجع أو الخطأ..."/><select name="integration"><option value="">كل التكاملات</option>{data.integrations.map(x=><option value={x.code} key={x.code}>{x.nameAr}</option>)}</select><select name="status"><option value="">كل الحالات</option><option value="Succeeded">ناجح</option><option value="Failed">فشل</option><option value="Retrying">إعادة محاولة</option></select><input name="from" type="date"/><input name="to" type="date"/><button className={base.primary}>تطبيق الفلاتر</button></form><OperationsTable rows={page.items} open={open}/></section>}
function OperationsTable({rows,open}:{rows:IntegrationOperation[];open:(x:IntegrationOperation)=>void}){return <div className={base.table}><table><thead><tr><th>الوقت</th><th>التكامل</th><th>العملية</th><th>المرجع</th><th>المدة</th><th>المحاولة</th><th>الحالة</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} onClick={()=>open(x)}><td>{date.format(new Date(x.startedAt))}</td><td><b>{x.integrationName}</b><small>{x.number}</small></td><td>{x.operation}<small>{x.error}</small></td><td>{x.reference||"—"}</td><td>{x.durationMs} ms</td><td>{x.attempt}/{x.maxAttempts}</td><td><u className={x.status==="Succeeded"?styles.ok:styles.fail}>{x.status==="Succeeded"?"ناجح":x.status==="Failed"?"فشل":x.status}</u></td></tr>)}</tbody></table>{!rows.length&&<p className={base.empty}>لا توجد عمليات مطابقة.</p>}</div>}
function Failure({row,busy,retry,disable}:{row:IntegrationOperation;busy:boolean;retry:()=>void;disable:()=>void}){return <><section className={styles.failureTitle}><div><u>فشل</u><h2>{row.operation}</h2><p>{row.integrationName} · {row.number} · {row.reference}</p></div><span>{date.format(new Date(row.startedAt))}</span></section><div className={styles.failureGrid}><section className={base.panel}><header className={base.panelHead}><h2>تفاصيل الخطأ</h2></header><dl className={styles.errorFacts}><div><dt>التكامل</dt><dd>{row.integrationName}</dd></div><div><dt>العملية</dt><dd>{row.operation}</dd></div><div><dt>كود الخطأ</dt><dd dir="ltr">{row.errorCode||"ERR-INTEGRATION"}</dd></div><div><dt>المحاولات</dt><dd>{row.attempt}/{row.maxAttempts}</dd></div></dl><pre dir="ltr">{row.error}{row.endpoint&&`\nEndpoint: ${row.endpoint}`}{row.nextRetryAt&&`\nRetry scheduled: ${date.format(new Date(row.nextRetryAt))}`}</pre></section><aside className={base.panel}><header className={base.panelHead}><h2>الإجراء</h2></header><div className={styles.failureActions}>{row.resolvedAt&&<p>✓ تمت معالجة العملية في {date.format(new Date(row.resolvedAt))}</p>}<button className={base.primary} disabled={busy||!row.isRetryable} onClick={retry}>إعادة يدوية</button><button className={base.secondary} disabled={busy} onClick={disable}>تعطيل مؤقت</button></div></aside></div></>}
function Retry({page,busy,retry,all,open}:{page:OperationsPage;busy:boolean;retry:(x:IntegrationOperation)=>void;all:()=>void;open:(x:IntegrationOperation)=>void}){const rows=page.items.filter(x=>x.status==="Failed");return <section className={base.panel}><header className={base.panelHead}><div><h2>إعادة محاولة التكاملات</h2><span>{rows.filter(x=>x.isRetryable).length} عمليات فاشلة قابلة للإعادة</span></div><button className={base.primary} disabled={busy||!rows.some(x=>x.isRetryable)} onClick={all}>↻ إعادة الكل</button></header><div className={base.table}><table><thead><tr><th>العملية</th><th>التكامل</th><th>وقت الفشل</th><th>السبب</th><th>المحاولات</th><th>الإجراء</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} onClick={()=>open(x)}><td>{x.operation}<small>{x.number}</small></td><td>{x.integrationName}</td><td>{date.format(new Date(x.startedAt))}</td><td>{x.errorCode}<small>{x.error}</small></td><td>{x.attempt}/{x.maxAttempts}</td><td onClick={e=>e.stopPropagation()}>{x.isRetryable?<button className={base.primary} disabled={busy} onClick={()=>retry(x)}>إعادة</button>:<button className={base.secondary} onClick={()=>open(x)}>مراجعة</button>}</td></tr>)}</tbody></table>{!rows.length&&<p className={base.empty}>لا توجد عمليات فاشلة.</p>}</div></section>}
function exportOperations(rows:IntegrationOperation[]){const head=["الوقت","رقم العملية","التكامل","العملية","المرجع","المدة ms","المحاولة","الحالة","الخطأ"],body=rows.map(x=>[x.startedAt,x.number,x.integrationName,x.operation,x.reference||"",String(x.durationMs),`${x.attempt}/${x.maxAttempts}`,x.status,x.error||""]);const csv="\uFEFF"+[head,...body].map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="integration-operations.csv";a.click();URL.revokeObjectURL(url)}
