"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Warehouse = { id: string; code: string; nameAr: string; nameEn?: string; governorate: string; address: string; isActive: boolean; productCount: number; totalUnits: number; stockValue: number };
type Stock = { id: string; warehouseId: string; warehouse: string; productId: string; sku: string; product: string; onHandQty: number; reservedQty: number; availableQty: number; reorderLevel: number; shelfLocation?: string; barcode?: string; unitCost: number; value: number; state: string };
type Movement = { id: string; number: string; type: string; warehouse: string; destinationWarehouse?: string; sku: string; product: string; quantity: number; balanceAfter: number; reason: string; referenceType?: string; createdAt: string };
type Batch = { id: string; warehouse: string; sku: string; product: string; batchNumber: string; quantity: number; manufacturedAt?: string; expiryAt?: string; state: string };
type Serial = { id: string; warehouse: string; sku: string; product: string; serialNumber: string; status: string; batchNumber?: string };
type CountItem = { productId: string; sku: string; product: string; systemQty: number; countedQty: number; difference: number; reason?: string };
type Count = { id: string; number: string; warehouseId: string; warehouse: string; status: string; createdAt: string; countedAt?: string; reconciledAt?: string; items: CountItem[] };
type ReceiptItem = { productId: string; sku: string; product: string; receivedQty: number; acceptedQty: number; damagedQty: number; unitCost: number; batchNumber?: string; expiryAt?: string };
type Receipt = { id: string; number: string; warehouseId: string; warehouse: string; supplierId?: string; supplier?: string; supplierReference: string; status: string; receivedAt: string; inspectedAt?: string; inspectionNotes?: string; items: ReceiptItem[] };
type Product = { id: string; sku: string; name: string; costPrice: number }; type Supplier = { id: string; code: string; name: string };
type Dashboard = { totalValue: number; totalUnits: number; reservedUnits: number; lowStockCount: number; outOfStockCount: number; warehouses: Warehouse[]; stocks: Stock[]; movements: Movement[]; batches: Batch[]; serials: Serial[]; counts: Count[]; receipts: Receipt[]; products: Product[]; suppliers: Supplier[] };
type Tab = "overview" | "warehouses" | "stock" | "movements" | "tracking" | "counts" | "receiving";
type Editor = { kind: "warehouse"; item?: Warehouse } | { kind: "adjust"; action: "Add" | "Deduct"; stock?: Stock } | { kind: "transfer"; stock?: Stock } | { kind: "reserve"; action: "Reserve" | "Release"; stock: Stock } | { kind: "metadata"; stock: Stock } | { kind: "count" } | { kind: "reconcile"; count: Count } | { kind: "receipt" } | { kind: "inspect"; receipt: Receipt };

const money = (value: number) => new Intl.NumberFormat("ar-EG", { style: "currency", currency: "EGP", maximumFractionDigits: 0 }).format(value);
const date = (value?: string) => value ? new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const labels: Record<string, string> = { Healthy: "جيد", Low: "منخفض", Out: "نافد", Add: "إضافة", Deduct: "خصم", TransferOut: "تحويل صادر", TransferIn: "تحويل وارد", Reconcile: "تسوية", Reserve: "حجز", Release: "تحرير", Receive: "استلام", RejectDamaged: "تالف مرفوض", Valid: "صالح", Expiring: "قرب انتهاء", Expired: "منتهي", NoExpiry: "بدون صلاحية", Inspection: "بانتظار الفحص", Accepted: "مقبول", PartiallyAccepted: "قبول جزئي", Rejected: "مرفوض", InProgress: "قيد الجرد", Reconciled: "تمت التسوية" };

export function InventoryManager() {
  const [data, setData] = useState<Dashboard | null>(null); const [tab, setTab] = useState<Tab>("overview"); const [editor, setEditor] = useState<Editor | null>(null); const [filter, setFilter] = useState("all");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/inventory"); if (!response.ok) throw new Error("تعذر تحميل بيانات المخزون"); return response.json() as Promise<Dashboard>; }, []);
  useEffect(() => { let active = true; load().then((result) => { if (active) { setData(result); setLoading(false); } }).catch((reason) => { if (active) { setError(reason.message); setLoading(false); } }); return () => { active = false; }; }, [load]);
  async function api(path: string, body: unknown, method = "POST") { const response = await fetch(`/api/admin/inventory/${path}`, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) { const result = await response.json().catch(() => ({})); throw new Error(result.title || "تعذر تنفيذ عملية المخزون"); } }
  async function refresh(message: string) { setData(await load()); setNotice(message); setTimeout(() => setNotice(""), 3500); }
  const filteredStocks = useMemo(() => data?.stocks.filter((x) => filter === "all" || x.state.toLowerCase() === filter) ?? [], [data, filter]);

  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editor) return; setSaving(true); setError(""); const form = new FormData(event.currentTarget);
    try {
      if (editor.kind === "warehouse") await api(editor.item ? `warehouses/${editor.item.id}` : "warehouses", { code: form.get("code"), nameAr: form.get("nameAr"), nameEn: form.get("nameEn") || null, governorate: form.get("governorate"), address: form.get("address"), isActive: form.get("isActive") === "on" }, editor.item ? "PUT" : "POST");
      if (editor.kind === "adjust") await api("adjust", { warehouseId: form.get("warehouseId"), productId: form.get("productId"), quantity: Number(form.get("quantity")), type: editor.action, reason: form.get("reason"), batchNumber: form.get("batchNumber") || null, manufacturedAt: form.get("manufacturedAt") ? new Date(String(form.get("manufacturedAt"))).toISOString() : null, expiryAt: form.get("expiryAt") ? new Date(String(form.get("expiryAt"))).toISOString() : null, serialNumbers: String(form.get("serialNumbers") || "").split(/[,\n]/).map((x) => x.trim()).filter(Boolean) });
      if (editor.kind === "transfer") await api("transfer", { fromWarehouseId: form.get("fromWarehouseId"), toWarehouseId: form.get("toWarehouseId"), productId: form.get("productId"), quantity: Number(form.get("quantity")), reason: form.get("reason") });
      if (editor.kind === "reserve") await api("reserve", { warehouseId: editor.stock.warehouseId, productId: editor.stock.productId, quantity: Number(form.get("quantity")), action: editor.action, reason: form.get("reason"), referenceType: form.get("referenceType") || null, referenceId: null });
      if (editor.kind === "metadata") await api(`stocks/${editor.stock.id}/metadata`, { reorderLevel: Number(form.get("reorderLevel")), shelfLocation: form.get("shelfLocation") || null, barcode: form.get("barcode") || null }, "PUT");
      if (editor.kind === "count") await api("counts", { warehouseId: form.get("warehouseId") });
      if (editor.kind === "reconcile") await api(`counts/${editor.count.id}/reconcile`, { items: editor.count.items.map((x) => ({ productId: x.productId, countedQty: Number(form.get(`qty-${x.productId}`)), reason: form.get(`reason-${x.productId}`) || null })) });
      if (editor.kind === "receipt") await api("receipts", { warehouseId: form.get("warehouseId"), supplierId: form.get("supplierId") || null, supplierReference: form.get("supplierReference"), items: [{ productId: form.get("productId"), receivedQty: Number(form.get("receivedQty")), unitCost: Number(form.get("unitCost")), batchNumber: form.get("batchNumber") || null, expiryAt: form.get("expiryAt") ? new Date(String(form.get("expiryAt"))).toISOString() : null }] });
      if (editor.kind === "inspect") await api(`receipts/${editor.receipt.id}/inspect`, { items: editor.receipt.items.map((x) => ({ productId: x.productId, acceptedQty: Number(form.get(`accepted-${x.productId}`)), damagedQty: Number(form.get(`damaged-${x.productId}`)) })), notes: form.get("notes") || null });
      setEditor(null); await refresh("تم تسجيل عملية المخزون بنجاح");
    } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر الحفظ"); } finally { setSaving(false); }
  }
  function printBarcodes() { window.print(); }
  if (loading) return <div className="admin-loading">جاري تحميل المخزون...</div>; if (!data) return <div className="admin-alert">{error || "لا توجد بيانات"}</div>;
  const tabs: [Tab, string][] = [["overview", "لوحة المخزون"], ["warehouses", "المخازن"], ["stock", "الرصيد"], ["movements", "الحركات"], ["tracking", "التتبع والباركود"], ["counts", "الجرد والتسوية"], ["receiving", "الاستلام والفحص"]];
  return <>
    <div className="page-heading catalog-heading"><div><p>العمليات</p><h1>المخزون والمستودعات</h1><span>أرصدة دقيقة ودفتر حركات قابل للتدقيق من الاستلام حتى الصرف</span></div><div className="content-heading-actions"><button className="secondary-button" onClick={() => setEditor({ kind: "transfer" })}>تحويل مخزني</button><button className="secondary-button" onClick={() => setEditor({ kind: "adjust", action: "Deduct" })}>خصم مخزون</button><button className="primary-button" onClick={() => setEditor({ kind: "adjust", action: "Add" })}>+ إضافة مخزون</button></div></div>
    {error && <div className="admin-alert">{error}<button onClick={() => setError("")}>×</button></div>}{notice && <div className="admin-success">✓ {notice}</div>}
    <div className="catalog-tabs content-tabs">{tabs.map(([key, label]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label}</button>)}</div>
    {tab === "overview" && <><section className="inventory-kpis"><article><span>قيمة المخزون</span><b>{money(data.totalValue)}</b><small>بالتكلفة الحالية</small></article><article><span>إجمالي الوحدات</span><b>{data.totalUnits.toLocaleString("ar-EG")}</b><small>{data.reservedUnits} وحدة محجوزة</small></article><article className="warning"><span>مخزون منخفض</span><b>{data.lowStockCount}</b><small>يحتاج إعادة طلب</small></article><article className="danger"><span>منتجات نافدة</span><b>{data.outOfStockCount}</b><small>تدخل عاجل</small></article></section><section className="inventory-overview-grid"><div className="panel"><header className="inventory-panel-head"><div><h2>المخازن</h2><p>التوزيع الحالي لقيمة المخزون</p></div><button onClick={() => { setTab("warehouses"); setEditor({ kind: "warehouse" }); }}>+ مخزن</button></header><div className="warehouse-mini-grid">{data.warehouses.map((x) => <article key={x.id}><span>▣</span><div><b>{x.nameAr}</b><small>{x.code} · {x.governorate}</small></div><strong>{x.totalUnits.toLocaleString("ar-EG")} وحدة</strong><em>{money(x.stockValue)}</em></article>)}</div></div><div className="panel"><header className="inventory-panel-head"><div><h2>تنبيهات الرصيد</h2><p>الأصناف التي تحتاج متابعة</p></div></header><div className="inventory-alert-list">{data.stocks.filter((x) => x.state !== "Healthy").slice(0, 7).map((x) => <article key={x.id}><i className={x.state === "Out" ? "out" : "low"}>!</i><div><b>{x.product}</b><small>{x.sku} · {x.warehouse}</small></div><strong>{x.availableQty} متاح</strong></article>)}</div></div></section><section className="panel content-table-panel inventory-value"><header className="inventory-panel-head"><div><h2>تقييم المخزون</h2><p>أعلى الأصناف قيمة بالتكلفة</p></div></header><InventoryTable stocks={[...data.stocks].sort((a,b) => b.value-a.value).slice(0,8)} onEditor={setEditor} /></section></>}
    {tab === "warehouses" && <section className="warehouse-admin-grid">{data.warehouses.map((x) => <article className="panel warehouse-admin-card" key={x.id}><header><span>▣</span><em className={x.isActive ? "status-live" : "status-off"}>{x.isActive ? "نشط" : "معطل"}</em></header><h2>{x.nameAr}</h2><p>{x.nameEn} · {x.code}</p><address>{x.governorate} — {x.address}</address><dl><div><dt>الأصناف</dt><dd>{x.productCount}</dd></div><div><dt>الوحدات</dt><dd>{x.totalUnits}</dd></div><div><dt>القيمة</dt><dd>{money(x.stockValue)}</dd></div></dl><button onClick={() => setEditor({ kind: "warehouse", item: x })}>تعديل التفاصيل</button></article>)}<button className="warehouse-add-card" onClick={() => setEditor({ kind: "warehouse" })}>＋<b>إضافة مخزن جديد</b></button></section>}
    {tab === "stock" && <section className="panel content-table-panel"><div className="inventory-table-tools"><div>{[["all","الكل"],["healthy","جيد"],["low","منخفض"],["out","نافد"]].map(([key,label]) => <button key={key} className={filter === key ? "active" : ""} onClick={() => setFilter(key)}>{label}</button>)}</div><span>{filteredStocks.length} سجل رصيد</span></div><InventoryTable stocks={filteredStocks} onEditor={setEditor} /></section>}
    {tab === "movements" && <section className="panel content-table-panel"><table className="content-table inventory-wide"><thead><tr><th>رقم الحركة</th><th>النوع</th><th>المنتج</th><th>المخزن</th><th>الكمية</th><th>الرصيد بعدها</th><th>السبب</th><th>التاريخ</th></tr></thead><tbody>{data.movements.map((x) => <tr key={x.id}><td dir="ltr">{x.number}</td><td><em className={`movement movement-${x.type.toLowerCase()}`}>{labels[x.type] || x.type}</em></td><td><b>{x.product}</b><small>{x.sku}</small></td><td>{x.warehouse}{x.destinationWarehouse && <small> ← {x.destinationWarehouse}</small>}</td><td>{x.quantity}</td><td>{x.balanceAfter}</td><td>{x.reason}</td><td>{date(x.createdAt)}</td></tr>)}</tbody></table></section>}
    {tab === "tracking" && <section className="tracking-layout"><div className="panel content-table-panel"><header className="inventory-panel-head"><div><h2>التشغيلات وتواريخ الصلاحية</h2><p>{data.batches.length} تشغيلة مسجلة</p></div></header><table className="content-table"><thead><tr><th>التشغيلة</th><th>المنتج</th><th>المخزن</th><th>الكمية</th><th>الصلاحية</th><th>الحالة</th></tr></thead><tbody>{data.batches.map((x) => <tr key={x.id}><td dir="ltr">{x.batchNumber}</td><td><b>{x.product}</b><small>{x.sku}</small></td><td>{x.warehouse}</td><td>{x.quantity}</td><td>{date(x.expiryAt)}</td><td><em className={x.state === "Expired" ? "status-off" : x.state === "Expiring" ? "status-wait" : "status-live"}>{labels[x.state]}</em></td></tr>)}</tbody></table></div><div className="panel content-table-panel"><header className="inventory-panel-head"><div><h2>الأرقام التسلسلية</h2><p>{data.serials.length} جهاز متتبع</p></div></header><table className="content-table"><thead><tr><th>Serial</th><th>المنتج</th><th>المخزن</th><th>التشغيلة</th><th>الحالة</th></tr></thead><tbody>{data.serials.map((x) => <tr key={x.id}><td dir="ltr">{x.serialNumber}</td><td>{x.product}</td><td>{x.warehouse}</td><td>{x.batchNumber || "—"}</td><td>{x.status}</td></tr>)}</tbody></table></div><div className="panel barcode-sheet"><header className="inventory-panel-head"><div><h2>إدارة الباركود والرفوف</h2><p>اطبع ملصقات الرصيد المحدد</p></div><button onClick={printBarcodes}>طباعة الباركود</button></header><div>{data.stocks.slice(0,12).map((x) => <article key={x.id}><span className="barcode-bars">|||| ||| || ||||</span><b>{x.barcode || x.sku}</b><small>{x.product} · {x.shelfLocation || "بدون رف"}</small></article>)}</div></div></section>}
    {tab === "counts" && <section className="panel content-table-panel"><header className="inventory-panel-head"><div><h2>جلسات الجرد والتسوية</h2><p>تثبيت الرصيد الفعلي مع تسجيل الفروق</p></div><button className="primary-button" onClick={() => setEditor({ kind: "count" })}>+ بدء جرد</button></header><table className="content-table"><thead><tr><th>الجلسة</th><th>المخزن</th><th>الحالة</th><th>الأصناف</th><th>الفروق</th><th>التاريخ</th><th /></tr></thead><tbody>{data.counts.map((x) => <tr key={x.id}><td dir="ltr">{x.number}</td><td>{x.warehouse}</td><td><em className={x.status === "Reconciled" ? "status-live" : "status-wait"}>{labels[x.status] || x.status}</em></td><td>{x.items.length}</td><td>{x.items.reduce((sum,item) => sum + Math.abs(item.difference),0)}</td><td>{date(x.reconciledAt || x.createdAt)}</td><td>{x.status !== "Reconciled" && <button onClick={() => setEditor({ kind: "reconcile", count: x })}>إدخال العد والتسوية</button>}</td></tr>)}</tbody></table></section>}
    {tab === "receiving" && <section className="panel content-table-panel"><header className="inventory-panel-head"><div><h2>استلام مشتريات الموردين</h2><p>الفحص والقبول ورفض الكميات التالفة</p></div><button className="primary-button" onClick={() => setEditor({ kind: "receipt" })}>+ إذن استلام</button></header><table className="content-table"><thead><tr><th>الإذن</th><th>المورد / المرجع</th><th>المخزن</th><th>الكمية</th><th>مقبول</th><th>تالف</th><th>الحالة</th><th /></tr></thead><tbody>{data.receipts.map((x) => <tr key={x.id}><td><b>{x.number}</b><small>{date(x.receivedAt)}</small></td><td><b>{x.supplier || "بدون مورد"}</b><small>{x.supplierReference}</small></td><td>{x.warehouse}</td><td>{x.items.reduce((s,i) => s+i.receivedQty,0)}</td><td>{x.items.reduce((s,i) => s+i.acceptedQty,0)}</td><td>{x.items.reduce((s,i) => s+i.damagedQty,0)}</td><td><em className={x.status === "Inspection" ? "status-wait" : x.status === "Rejected" ? "status-off" : "status-live"}>{labels[x.status] || x.status}</em></td><td>{x.status === "Inspection" && <button onClick={() => setEditor({ kind: "inspect", receipt: x })}>فحص الاستلام</button>}</td></tr>)}</tbody></table></section>}
    {editor && <InventoryEditor editor={editor} data={data} saving={saving} onClose={() => setEditor(null)} onSubmit={save} />}
  </>;
}

function InventoryTable({ stocks, onEditor }: { stocks: Stock[]; onEditor: (editor: Editor) => void }) { return <table className="content-table inventory-wide"><thead><tr><th>المنتج</th><th>المخزن</th><th>الموقع</th><th>الحالي</th><th>المحجوز</th><th>المتاح</th><th>حد الطلب</th><th>القيمة</th><th>الحالة</th><th /></tr></thead><tbody>{stocks.map((x) => <tr key={x.id}><td><b>{x.product}</b><small>{x.sku} · {x.barcode}</small></td><td>{x.warehouse}</td><td>{x.shelfLocation || "—"}</td><td>{x.onHandQty}</td><td>{x.reservedQty}</td><td><b>{x.availableQty}</b></td><td>{x.reorderLevel}</td><td>{money(x.value)}</td><td><em className={x.state === "Healthy" ? "status-live" : x.state === "Low" ? "status-wait" : "status-off"}>{labels[x.state]}</em></td><td><button onClick={() => onEditor({ kind: "reserve", action: "Reserve", stock: x })}>حجز</button>{x.reservedQty > 0 && <button onClick={() => onEditor({ kind: "reserve", action: "Release", stock: x })}>تحرير</button>}<button onClick={() => onEditor({ kind: "metadata", stock: x })}>ضبط</button></td></tr>)}</tbody></table>; }

function InventoryEditor({ editor, data, saving, onClose, onSubmit }: { editor: Editor; data: Dashboard; saving: boolean; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const titles: Record<Editor["kind"], string> = { warehouse: "بيانات المخزن", adjust: editor.kind === "adjust" && editor.action === "Add" ? "إضافة مخزون" : "خصم مخزون", transfer: "تحويل بين المخازن", reserve: editor.kind === "reserve" && editor.action === "Reserve" ? "حجز مخزون لطلب" : "تحرير المخزون المحجوز", metadata: "الموقع والباركود", count: "بدء جرد مخزني", reconcile: "إدخال العد والتسوية", receipt: "استلام مشتريات مورد", inspect: "فحص الاستلام" };
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="mini-editor content-editor inventory-editor"><header><h2>{titles[editor.kind]}</h2><button onClick={onClose}>×</button></header><form onSubmit={onSubmit}>
    {editor.kind === "warehouse" && <><div className="editor-columns"><label>كود المخزن<input name="code" dir="ltr" defaultValue={editor.item?.code || ""} required /></label><label>المحافظة<input name="governorate" defaultValue={editor.item?.governorate || ""} required /></label></div><label>الاسم بالعربية<input name="nameAr" defaultValue={editor.item?.nameAr || ""} required /></label><label>الاسم بالإنجليزية<input name="nameEn" dir="ltr" defaultValue={editor.item?.nameEn || ""} /></label><label>العنوان<input name="address" defaultValue={editor.item?.address || ""} required /></label><label className="check-label"><input name="isActive" type="checkbox" defaultChecked={editor.item?.isActive !== false} /> مخزن نشط</label></>}
    {editor.kind === "adjust" && <><div className="editor-columns"><WarehouseSelect data={data} name="warehouseId" value={editor.stock?.warehouseId} /><ProductSelect data={data} value={editor.stock?.productId} /></div><label>الكمية<input name="quantity" type="number" min="1" required /></label><label>السبب<input name="reason" required /></label>{editor.action === "Add" && <><div className="editor-columns"><label>رقم التشغيلة<input name="batchNumber" dir="ltr" /></label><label>تاريخ الصلاحية<input name="expiryAt" type="date" /></label></div><label>الأرقام التسلسلية<textarea name="serialNumbers" dir="ltr" placeholder="رقم في كل سطر أو مفصولة بفاصلة" /></label></>}</>}
    {editor.kind === "transfer" && <><div className="editor-columns"><WarehouseSelect data={data} name="fromWarehouseId" label="من مخزن" value={editor.stock?.warehouseId} /><WarehouseSelect data={data} name="toWarehouseId" label="إلى مخزن" /></div><ProductSelect data={data} value={editor.stock?.productId} /><label>الكمية<input name="quantity" type="number" min="1" required /></label><label>السبب<input name="reason" required /></label></>}
    {editor.kind === "reserve" && <><div className="selected-stock"><b>{editor.stock.product}</b><span>{editor.stock.warehouse} · متاح {editor.stock.availableQty} · محجوز {editor.stock.reservedQty}</span></div><label>الكمية<input name="quantity" type="number" min="1" max={editor.action === "Reserve" ? editor.stock.availableQty : editor.stock.reservedQty} required /></label><label>مرجع العملية<input name="referenceType" placeholder="رقم الطلب أو القسم" /></label><label>السبب<input name="reason" required /></label>{editor.stock.reservedQty > 0 && editor.action === "Reserve" && <button type="button" className="secondary-button" onClick={() => onClose()}>استخدم تحرير من قائمة الحركات</button>}</>}
    {editor.kind === "metadata" && <><div className="selected-stock"><b>{editor.stock.product}</b><span>{editor.stock.warehouse}</span></div><label>حد إعادة الطلب<input name="reorderLevel" type="number" min="0" defaultValue={editor.stock.reorderLevel} /></label><label>موقع الرف<input name="shelfLocation" dir="ltr" defaultValue={editor.stock.shelfLocation || ""} /></label><label>الباركود<input name="barcode" dir="ltr" defaultValue={editor.stock.barcode || ""} /></label></>}
    {editor.kind === "count" && <WarehouseSelect data={data} name="warehouseId" />}
    {editor.kind === "reconcile" && <div className="count-input-list">{editor.count.items.map((x) => <article key={x.productId}><div><b>{x.product}</b><small>{x.sku} · النظام: {x.systemQty}</small></div><input name={`qty-${x.productId}`} type="number" min="0" defaultValue={x.countedQty} required /><input name={`reason-${x.productId}`} placeholder="سبب الفرق" /></article>)}</div>}
    {editor.kind === "receipt" && <><div className="editor-columns"><WarehouseSelect data={data} name="warehouseId" /><label>المورد<select name="supplierId"><option value="">بدون مورد</option>{data.suppliers.map((x) => <option value={x.id} key={x.id}>{x.name} · {x.code}</option>)}</select></label></div><label>مرجع المورد / أمر الشراء<input name="supplierReference" dir="ltr" required /></label><ProductSelect data={data} /><div className="editor-columns"><label>الكمية المستلمة<input name="receivedQty" type="number" min="1" required /></label><label>تكلفة الوحدة<input name="unitCost" type="number" min="0" step="0.01" required /></label></div><div className="editor-columns"><label>رقم التشغيلة<input name="batchNumber" dir="ltr" /></label><label>الصلاحية<input name="expiryAt" type="date" /></label></div></>}
    {editor.kind === "inspect" && <><div className="selected-stock"><b>{editor.receipt.number}</b><span>{editor.receipt.supplier || "بدون مورد"} · {editor.receipt.warehouse}</span></div><div className="inspection-input-list">{editor.receipt.items.map((x) => <article key={x.productId}><div><b>{x.product}</b><small>مستلم: {x.receivedQty}</small></div><label>مقبول<input name={`accepted-${x.productId}`} type="number" min="0" max={x.receivedQty} defaultValue={x.receivedQty} required /></label><label>تالف<input name={`damaged-${x.productId}`} type="number" min="0" max={x.receivedQty} defaultValue="0" required /></label></article>)}</div><label>ملاحظات الفحص<textarea name="notes" /></label></>}
    <footer><button type="button" className="secondary-button" onClick={onClose}>إلغاء</button><button className="primary-button" disabled={saving}>{saving ? "جاري التسجيل..." : "تأكيد العملية"}</button></footer>
  </form></section></div>;
}
function WarehouseSelect({ data, name, label = "المخزن", value }: { data: Dashboard; name: string; label?: string; value?: string }) { return <label>{label}<select name={name} defaultValue={value || ""} required><option value="" disabled>اختر المخزن</option>{data.warehouses.filter((x) => x.isActive).map((x) => <option key={x.id} value={x.id}>{x.nameAr}</option>)}</select></label>; }
function ProductSelect({ data, value }: { data: Dashboard; value?: string }) { return <label>المنتج<select name="productId" defaultValue={value || ""} required><option value="" disabled>اختر المنتج</option>{data.products.map((x) => <option key={x.id} value={x.id}>{x.sku} · {x.name}</option>)}</select></label>; }
