namespace Mohandseto.Api.Application.Account;

public record AccountOverviewDto(ProfileDto Profile, CompanyDto Company, int Users, int Branches, int PendingInvites, decimal CreditLimit, decimal CreditUsed, DateTime? ContractEndsAt);
public record ProfileDto(Guid Id, string FullName, string Phone, string? Email, string? AvatarPath, string Language, string? JobTitle, string? Department, decimal? PurchaseLimit, Guid? DefaultBranchId, IReadOnlyList<string> Roles);
public record UpdateProfileDto(string FullName, string? Email, string Language, string? JobTitle, string? Department, Guid? DefaultBranchId);
public record CompanyDto(Guid Id, string LegalName, string? LegalNameEn, string? CommercialRegistrationNo, string? TaxCardNo, string Phone, string? Email, string? Governorate, string? City, string? AddressLine, string? Industry, int EmployeeCountRange, string Status);
public record UpdateCompanyDto(string LegalName, string? LegalNameEn, string Phone, string? Email, string? Governorate, string? City, string? AddressLine, string? Industry, int EmployeeCountRange);
public record BranchDto(Guid Id, string Name, string? Governorate, string? City, string? AddressLine, string? Phone, double? Latitude, double? Longitude, bool IsMain);
public record UpsertBranchDto(string Name, string? Governorate, string? City, string? AddressLine, string? Phone, double? Latitude, double? Longitude, bool IsMain);
public record CompanyDocumentDto(Guid Id, string Type, string FileName, long SizeBytes, string ReviewStatus, string? RejectionReason, DateTime CreatedAt);
public record CompanyUserDto(Guid Id, string FullName, string Phone, string? Email, bool IsActive, string? JobTitle, string? Department, decimal? PurchaseLimit, Guid? DefaultBranchId, IReadOnlyList<RoleBriefDto> Roles, DateTime CreatedAt);
public record RoleBriefDto(Guid Id, string Code, string Name);
public record CreateCompanyUserDto(string FullName, string Phone, string? Email, string Password, string? JobTitle, string? Department, decimal? PurchaseLimit, Guid? DefaultBranchId, IReadOnlyList<Guid> RoleIds);
public record UpdateCompanyUserDto(string FullName, string? Email, bool IsActive, string? JobTitle, string? Department, decimal? PurchaseLimit, Guid? DefaultBranchId, IReadOnlyList<Guid> RoleIds);
public record InviteCompanyUserDto(string FullName, string? Email, string? Phone, Guid RoleId, Guid? BranchId);
public record InviteResultDto(Guid Id, string Status, DateTime ExpiresAt, string InvitationToken);
public record AcceptInviteDto(string Token, string Password);
public record PermissionDto(int Id, string Code, string Module, string Description);
public record CompanyRoleDto(Guid Id, string Code, string NameAr, string NameEn, bool IsSystem, int UsersCount, IReadOnlyList<string> Permissions);
public record CreateCompanyRoleDto(string NameAr, string NameEn, IReadOnlyList<int> PermissionIds);
public record UpdateRolePermissionsDto(IReadOnlyList<int> PermissionIds);
public record ApprovalLevelAccountDto(Guid? Id, int Sequence, string Name, decimal? AuthorityLimit, int SlaHours, IReadOnlyList<Guid> ApproverUserIds);
public record ApprovalPolicyAccountDto(Guid Id, string Name, decimal MinimumAmount, bool AppliesOnBudgetConflict, bool IsActive, IReadOnlyList<ApprovalLevelAccountDto> Levels);
public record UpdateApprovalPolicyDto(string Name, decimal MinimumAmount, bool AppliesOnBudgetConflict, bool IsActive, IReadOnlyList<ApprovalLevelAccountDto> Levels);
public record CostCenterAccountDto(Guid Id, string Code, string Name, decimal Budget, decimal Used, decimal Reserved, decimal? ApprovalThreshold, bool IsActive);
public record UpsertCostCenterDto(string Code, string Name, decimal Budget, decimal? ApprovalThreshold, bool IsActive);
public record AccountAuditDto(long Id, DateTime At, Guid? UserId, string? UserName, string Action, string EntityType, string? EntityId, string? Data);
public record BrandProfileDto(string? LogoPath, string PrimaryColor, string SecondaryColor, string? BrandNameAr, string? BrandNameEn);
public record UpdateBrandProfileDto(string PrimaryColor, string SecondaryColor, string? BrandNameAr, string? BrandNameEn);
public record BillingProfileDto(string InvoiceLegalName, string? BillingEmail, string? TaxRegistrationNo, string? TaxAddress, int PaymentTermsDays, bool PurchaseOrderRequired);
public record UpdateBillingProfileDto(string InvoiceLegalName, string? BillingEmail, string? TaxRegistrationNo, string? TaxAddress, int PaymentTermsDays, bool PurchaseOrderRequired);
public record CompanyContractDto(Guid Id, string Number, DateTime StartsAt, DateTime EndsAt, string Status, int PaymentTermsDays, decimal CreditLimit, bool AutoRenew, string? TermsSummary, string? DocumentPath, int DaysRemaining);
public record CreateRenewalRequestDto(int RequestedMonths, string? Note);
public record RenewalRequestDto(Guid Id, Guid ContractId, int RequestedMonths, string Status, DateTime CreatedAt, string? Note);
