"use client";

import {type FormEvent,useEffect,useMemo,useState} from "react";
import base from "../operations.module.css";
import styles from "./marketing.module.css";
import type {Campaign,Coupon,MarketingDashboard,Tenant} from "./marketing-types";

type View="campaigns"|"coupons"|"opens"|"conversion";
type Modal="campaign"|"coupon"|null;
type CampaignDraft={name:string;channel:string;audienceType:string;sector:string;behaviorDays:number;tenantIds:string[];title:string;body:string;actionUrl:string;imageUrl:string;couponCode:string;scheduleType:string;scheduledAt:string;cost:number};
const initialDraft:CampaignDraft={name:"",channel:"Push",audienceType:"AllCompanies",sector:"",behaviorDays:30,tenantIds:[],title:"",body:"",actionUrl:"",imageUrl:"",couponCode:"",scheduleType:"Immediate",scheduledAt:"",cost:0};
const labels:Record<string,string>={Push:"إشعار Push",Email:"بريد إلكتروني",WhatsApp:"واتساب",InApp:"داخل التطبيق",AllCompanies:"كل الشركات",SelectedCompanies:"شركات محددة",Sector:"قطاع محدد",Behavior:"حسب السلوك",Immediate:"إرسال فوري",Optimal:"أفضل وقت تلقائياً",Draft:"مسودة",Scheduled:"مجدولة",Processing:"قيد الإرسال",Sent:"مكتملة",Cancelled:"ملغاة",Percentage:"نسبة مئوية",Fixed:"قيمة ثابتة"};
const channelIcons:Record<string,string>={Push:"⌁",Email:"✉",WhatsApp:"◉",InApp:"ⓘ"};
const tr=(v:string)=>labels[v]||v;
const money=new Intl.NumberFormat("ar-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0});
const number=new Intl.NumberFormat("ar-EG");
const date=(v?:string)=>v?new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,cache:"no-store"});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.title||error.message||"تعذر تنفيذ العملية")}return response.status===204?undefined as T:response.json()}

export function MarketingManager(){
 const[data,setData]=useState<MarketingDashboard|null>(null),[view,setView]=useState<View>("campaigns"),[modal,setModal]=useState<Modal>(null),[selected,setSelected]=useState<Campaign|null>(null),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>setData(await api("/api/admin/marketing"));
 useEffect(()=>{let active=true;api<MarketingDashboard>("/api/admin/marketing").then(x=>active&&setData(x)).catch(e=>active&&setError((e as Error).message));return()=>{active=false}},[]);
 const campaigns=useMemo(()=>data?.campaigns.filter(x=>!query||`${x.name} ${x.number} ${x.title}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]);
 async function action(url:string,method="POST"){setBusy(true);setError("");try{await api(url,{method});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!data)return <p className={base.empty}>{error||"جاري تحميل الحملات التسويقية..."}</p>;
 if(selected)return <CampaignDetail campaign={selected} back={()=>setSelected(null)}/>;
 const tabs:[View,string][]=[["campaigns","الحملات"],["coupons","أكواد الخصم"],["opens","تقارير الفتح"],["conversion","التحويل والمبيعات"]];
 return <section className={base.page}><header className={styles.hero}><div><span className={base.eyebrow}>الحملات والإشعارات</span><h1>الحملات التسويقية</h1><p>إدارة الجمهور والمحتوى والجدولة والقنوات وقياس أثر كل حملة من مكان واحد</p></div><div className={styles.heroActions}><button className={base.secondary} onClick={()=>setView("coupons")}>أكواد الخصم</button><button className={base.primary} onClick={()=>setModal("campaign")}>+ حملة جديدة</button></div></header>
 <nav className={base.tabs}>{tabs.map(([id,label])=><button key={id} className={view===id?base.active:""} onClick={()=>setView(id)}>{label}</button>)}</nav>
 {view==="campaigns"&&<Campaigns data={data} rows={campaigns} query={query} setQuery={setQuery} open={setSelected} send={id=>void action(`/api/admin/marketing/campaigns/${id}/send`)} cancel={id=>void action(`/api/admin/marketing/campaigns/${id}/cancel`)}/>} 
 {view==="coupons"&&<Coupons rows={data.coupons} create={()=>setModal("coupon")} toggle={(x)=>void action(`/api/admin/marketing/coupons/${x.groupId}/state?active=${!x.isActive}`,"PUT")}/>} 
 {view==="opens"&&<OpenReports data={data}/>} {view==="conversion"&&<ConversionReports data={data}/>} 
 {modal==="campaign"&&<CampaignWizard data={data} busy={busy} close={()=>setModal(null)} saved={async()=>{setModal(null);await load()}} fail={setError}/>} 
 {modal==="coupon"&&<CouponModal data={data} busy={busy} close={()=>setModal(null)} saved={async()=>{setModal(null);await load()}} fail={setError}/>} 
 {error&&<div className={base.alert}>{error}</div>}</section>;
}

function Kpi({icon,label,value,note}:{icon:string;label:string;value:string;note:string}){return <article className={base.kpi}><i>{icon}</i><span>{label}</span><b>{value}</b><small>{note}</small></article>}
function Campaigns({data,rows,query,setQuery,open,send,cancel}:{data:MarketingDashboard;rows:Campaign[];query:string;setQuery:(x:string)=>void;open:(x:Campaign)=>void;send:(id:string)=>void;cancel:(id:string)=>void}){const active=data.campaigns.filter(x=>x.status==="Scheduled"||x.status==="Processing").length;return <><div className={styles.summary}><Kpi icon="⌁" label="حملات نشطة" value={number.format(active)} note={`${data.campaigns.length} حملة إجمالاً`}/><Kpi icon="◉" label="معدل الفتح" value={`${data.reports.openRate}%`} note={`${number.format(data.reports.opened)} فتحة`}/><Kpi icon="↗" label="معدل التحويل" value={`${data.reports.conversionRate}%`} note={`${number.format(data.reports.conversions)} تحويل`}/><Kpi icon="▣" label="مبيعات الحملات" value={money.format(data.reports.revenue)} note={`ROI ×${data.reports.roi}`}/></div><section className={base.panel}><div className={base.panelHead}><div><h2>كل الحملات</h2><span>{rows.length} حملة مطابقة</span></div><input className={styles.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم أو رقم الحملة..."/></div><div className={base.table}><table><thead><tr><th>الحملة</th><th>النوع</th><th>الجمهور</th><th>الإرسال</th><th>الفتح</th><th>التحويل</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} onClick={()=>open(x)}><td className={styles.campaignName}><b>{x.name}</b><small>{x.number} · {x.title}</small></td><td><span className={styles.channel}><i>{channelIcons[x.channel]}</i>{tr(x.channel)}</span></td><td>{x.tenantIds.length} شركة<small>{tr(x.audienceType)}</small></td><td>{number.format(x.recipients)}</td><td className={styles.metric}>{x.openRate}%<small>{x.opened} فتحة</small></td><td className={styles.metric}>{x.conversionRate}%<small>{x.conversions} عملية</small></td><td><u className={`${base.status} ${base[x.status.toLowerCase()]||""}`}>{tr(x.status)}</u></td><td onClick={e=>e.stopPropagation()}><div className={base.actions}>{x.status!=="Sent"&&x.status!=="Cancelled"&&<button disabled={false} className={base.primary} onClick={()=>send(x.id)}>إرسال</button>}{x.status==="Scheduled"&&<button className={base.danger} onClick={()=>cancel(x.id)}>إلغاء</button>}</div></td></tr>)}</tbody></table>{!rows.length&&<div className={styles.emptyState}><i>⌁</i>لا توجد حملات مطابقة.</div>}</div></section></>}

function CampaignDetail({campaign,back}:{campaign:Campaign;back:()=>void}){const max=Math.max(campaign.recipients,campaign.delivered,campaign.opened,campaign.clicked,campaign.conversions,1);return <section className={base.page}><button className={base.back} onClick={back}>→ العودة إلى الحملات</button><header className={`${base.panel} ${styles.detailHero}`}><div><span className={base.eyebrow}>{tr(campaign.channel)} · {campaign.number}</span><h2>{campaign.name}</h2><p>{campaign.title} · {tr(campaign.audienceType)} · أرسلت {date(campaign.sentAt||campaign.scheduledAt)}</p></div><u className={`${base.status} ${base[campaign.status.toLowerCase()]||""}`}>{tr(campaign.status)}</u></header><div className={styles.detailCards}><Kpi icon={channelIcons[campaign.channel]} label="أرسلت" value={number.format(campaign.recipients)} note={`${campaign.tenantIds.length} شركة`}/><Kpi icon="✓" label="وصلت" value={number.format(campaign.delivered)} note={`${campaign.recipients?Math.round(campaign.delivered/campaign.recipients*100):0}%`}/><Kpi icon="◉" label="فُتحت" value={number.format(campaign.opened)} note={`${campaign.openRate}%`}/><Kpi icon="↗" label="تحويلات" value={number.format(campaign.conversions)} note={`${campaign.conversionRate}% · ${money.format(campaign.revenue)}`}/></div><div className={base.grid}><section className={base.panel}><div className={base.panelHead}><div><h2>أداء الحملة</h2><span>قمع التسليم والتفاعل</span></div></div><div className={styles.chart}>{[["أرسلت",campaign.recipients],["وصلت",campaign.delivered],["فُتحت",campaign.opened],["نقرات",campaign.clicked],["تحويلات",campaign.conversions]].map(([label,value])=><article key={String(label)}><b>{number.format(Number(value))}</b><i style={{height:`${Math.max(4,Number(value)/max*120)}px`}}/><span>{label}</span></article>)}</div></section><aside className={base.panel}><div className={base.panelHead}><h3>محتوى الرسالة</h3><span>{tr(campaign.channel)}</span></div><div className={styles.notification}><i>{channelIcons[campaign.channel]}</i><div><b>{campaign.title}</b><small>{campaign.body}</small>{campaign.actionUrl&&<small>{campaign.actionUrl}</small>}</div></div></aside></div></section>}

function Coupons({rows,create,toggle}:{rows:Coupon[];create:()=>void;toggle:(x:Coupon)=>void}){return <section className={base.panel}><div className={base.panelHead}><div><h2>أكواد الخصم</h2><span>{rows.filter(x=>x.isActive).length} نشط من {rows.length}</span></div><button className={base.primary} onClick={create}>+ كوبون جديد</button></div><div className={base.table}><table><thead><tr><th>الكود</th><th>الخصم</th><th>الشروط</th><th>الشركات</th><th>الاستخدام</th><th>ينتهي</th><th>الحالة</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.groupId}><td><b className={styles.couponCode}>{x.code}</b><small>{x.nameAr}</small></td><td>{x.discountType==="Percentage"?`${x.discountValue}%`:money.format(x.discountValue)}</td><td>{x.minimumSubtotal?`طلب فوق ${money.format(x.minimumSubtotal)}`:"بدون حد أدنى"}<small>{x.oncePerCompany?"مرة لكل شركة":"استخدام متكرر"}</small></td><td>{x.companyCount}</td><td>{x.usedCount}/{x.usageLimit||"∞"}</td><td>{date(x.expiresAt)}</td><td><u className={`${base.status} ${x.isActive?base.completed:base.draft}`}>{x.isActive?"نشط":"متوقف"}</u></td><td><button className={x.isActive?base.danger:base.secondary} onClick={()=>toggle(x)}>{x.isActive?"إيقاف":"تفعيل"}</button></td></tr>)}</tbody></table>{!rows.length&&<div className={styles.emptyState}>لا توجد أكواد خصم مُدارة مركزياً.</div>}</div></section>}

function OpenReports({data}:{data:MarketingDashboard}){const max=Math.max(...data.reports.channelRates.map(x=>x.openRate),1);return <><div className={styles.summary}><Kpi icon="◉" label="إجمالي الفتح" value={number.format(data.reports.opened)} note={`${data.reports.openRate}% من المستلمين`}/><Kpi icon="⌁" label="إجمالي النقرات" value={number.format(data.reports.clicked)} note="تفاعل قابل للقياس"/><Kpi icon="✓" label="تم التسليم" value={number.format(data.reports.delivered)} note="كل القنوات"/><Kpi icon="↗" label="أفضل قناة" value={tr([...data.reports.channelRates].sort((a,b)=>b.openRate-a.openRate)[0]?.channel||"—")} note="حسب معدل الفتح"/></div><div className={styles.reportGrid}><section className={base.panel}><div className={base.panelHead}><h2>معدل الفتح حسب القناة</h2><button className={base.secondary} onClick={()=>exportCsv("open-rates.csv",data.reports.channelRates)}>تصدير CSV</button></div><div className={styles.chart}>{data.reports.channelRates.map(x=><article key={x.channel}><b>{x.openRate}%</b><i style={{height:`${Math.max(5,x.openRate/max*125)}px`}}/><span>{tr(x.channel)}</span></article>)}</div></section><aside className={base.panel}><div className={base.panelHead}><h3>أفضل أوقات التفاعل</h3><span>حسب السجلات الفعلية</span></div><div className={styles.reportList}>{data.reports.bestTimes.map(x=><article key={x.hour}><span>{hour(x.hour)}</span><b>{x.openRate}%</b></article>)}{!data.reports.bestTimes.length&&<p className={base.empty}>تظهر الأوقات بعد أول فتح.</p>}</div></aside></div></>}
function ConversionReports({data}:{data:MarketingDashboard}){return <><div className={styles.summary}><Kpi icon="▣" label="مبيعات الحملات" value={money.format(data.reports.revenue)} note={`${data.reports.conversions} تحويل`}/><Kpi icon="↓" label="تكلفة الحملات" value={money.format(data.reports.cost)} note="الميزانية المسجلة"/><Kpi icon="↗" label="العائد ROI" value={`×${data.reports.roi}`} note="(المبيعات - التكلفة) ÷ التكلفة"/><Kpi icon="◎" label="معدل التحويل" value={`${data.reports.conversionRate}%`} note="من المستلمين"/></div><section className={base.panel}><div className={base.panelHead}><div><h2>التحويل والمبيعات حسب الحملة</h2><span>الطلبات المرتبطة بالكوبون أو أحداث التحويل</span></div><button className={base.secondary} onClick={()=>exportCsv("campaign-sales.csv",data.campaigns)}>تصدير CSV</button></div><div className={base.table}><table><thead><tr><th>الحملة</th><th>الجمهور</th><th>التحويلات</th><th>المبيعات</th><th>التكلفة</th><th>ROI</th></tr></thead><tbody>{data.campaigns.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.couponCode||"تتبع مباشر"}</small></td><td>{x.recipients}</td><td>{x.conversions} ({x.conversionRate}%)</td><td>{money.format(x.revenue)}</td><td>{money.format(x.cost)}</td><td><b>×{x.cost?((x.revenue-x.cost)/x.cost).toFixed(1):"0"}</b></td></tr>)}</tbody></table></div></section></>}

function CampaignWizard({data,busy,close,saved,fail}:{data:MarketingDashboard;busy:boolean;close:()=>void;saved:()=>Promise<void>;fail:(x:string)=>void}){const[step,setStep]=useState(1),[draft,setDraft]=useState(initialDraft),[saving,setSaving]=useState(false);const set=<K extends keyof CampaignDraft>(key:K,value:CampaignDraft[K])=>setDraft(x=>({...x,[key]:value}));const canNext=step===1?draft.name&&draft.channel&&(draft.audienceType!=="SelectedCompanies"||draft.tenantIds.length>0)&&(draft.audienceType!=="Sector"||draft.sector):step===2?draft.title&&draft.body:step===3?draft.scheduleType!=="Scheduled"||draft.scheduledAt:true;async function submit(){setSaving(true);try{await api("/api/admin/marketing/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,scheduledAt:draft.scheduledAt?new Date(draft.scheduledAt).toISOString():null,sendNow:draft.scheduleType==="Immediate"})});await saved()}catch(e){fail((e as Error).message)}finally{setSaving(false)}}return <div className={base.modalBack}><section className={`${base.modal} ${styles.wizard}`}><header><div><h2>حملة جديدة</h2><small>إنشاء حملة تسويقية متكاملة</small></div><button onClick={close}>×</button></header><div className={styles.steps}>{["النوع والجمهور","المحتوى","الجدولة","المراجعة"].map((x,i)=><div key={x} className={`${styles.step} ${step===i+1?styles.active:""} ${step>i+1?styles.done:""}`}><i>{step>i+1?"✓":i+1}</i><span>{x}</span></div>)}</div>{step===1&&<StepAudience data={data} draft={draft} set={set}/>} {step===2&&<StepContent draft={draft} set={set}/>} {step===3&&<StepSchedule draft={draft} set={set}/>} {step===4&&<StepReview data={data} draft={draft}/>}<footer><button className={base.secondary} onClick={step===1?close:()=>setStep(x=>x-1)}>{step===1?"إلغاء":"السابق"}</button>{step<4?<button className={base.primary} disabled={!canNext} onClick={()=>setStep(x=>x+1)}>التالي</button>:<button className={base.primary} disabled={saving||busy} onClick={()=>void submit()}>{saving?"جاري الحفظ...":draft.scheduleType==="Immediate"?"حفظ وإرسال":"حفظ وجدولة"}</button>}</footer></section></div>}
function StepAudience({data,draft,set}:{data:MarketingDashboard;draft:CampaignDraft;set:<K extends keyof CampaignDraft>(k:K,v:CampaignDraft[K])=>void}){return <div className={base.form}><label>اسم الحملة<input value={draft.name} onChange={e=>set("name",e.target.value)} placeholder="مثال: عروض يوليو للمطبوعات" required/></label><div><b>نوع الحملة</b><div className={styles.choiceGrid}>{["Push","Email","WhatsApp","InApp"].map(x=><button type="button" key={x} className={`${styles.choice} ${draft.channel===x?styles.selected:""}`} onClick={()=>set("channel",x)}><i>{channelIcons[x]}</i><b>{tr(x)}</b><small>{x}</small></button>)}</div></div><div><b>نوع الجمهور</b><div className={styles.audiences}>{[["AllCompanies","كل الشركات","كل الشركات النشطة"],["Sector","قطاع محدد","استهداف قطاع كامل"],["SelectedCompanies","شركات محددة","اختيار يدوي"],["Behavior","حسب السلوك","شركات طلبت مؤخراً"]].map(([id,title,note])=><button type="button" key={id} className={`${styles.audience} ${draft.audienceType===id?styles.selected:""}`} onClick={()=>set("audienceType",id)}><input type="radio" readOnly checked={draft.audienceType===id}/><span><b>{title}</b><small>{note}</small></span></button>)}</div></div>{draft.audienceType==="Sector"&&<label>القطاع<select value={draft.sector} onChange={e=>set("sector",e.target.value)}><option value="">اختر القطاع</option>{data.sectors.map(x=><option key={x}>{x}</option>)}</select></label>}{draft.audienceType==="Behavior"&&<label>طلب خلال آخر<input type="number" min="1" max="365" value={draft.behaviorDays} onChange={e=>set("behaviorDays",Number(e.target.value))}/><small>يومًا</small></label>}{draft.audienceType==="SelectedCompanies"&&<TenantPicker tenants={data.tenants} selected={draft.tenantIds} set={x=>set("tenantIds",x)}/>}</div>}
function TenantPicker({tenants,selected,set}:{tenants:Tenant[];selected:string[];set:(x:string[])=>void}){return <div className={styles.tenantList}>{tenants.map(x=><label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>set(selected.includes(x.id)?selected.filter(id=>id!==x.id):[...selected,x.id])}/><b>{x.name}</b><small>{x.sector||"غير مصنف"} · آخر طلب {date(x.lastOrderAt)}</small></label>)}</div>}
function StepContent({draft,set}:{draft:CampaignDraft;set:<K extends keyof CampaignDraft>(k:K,v:CampaignDraft[K])=>void}){
 return <div className={styles.preview}><div className={base.form}>
  <label>العنوان<input value={draft.title} onChange={e=>set("title",e.target.value)} maxLength={120} placeholder="خصم 15% على المطبوعات"/></label>
  <label>النص<textarea value={draft.body} onChange={e=>set("body",e.target.value)} rows={5} maxLength={700} placeholder="اكتب رسالة الحملة بوضوح..."/></label>
  <div className={base.cols}><label>رابط الإجراء<input dir="ltr" value={draft.actionUrl} onChange={e=>set("actionUrl",e.target.value)} placeholder="/offers"/></label><label>رابط الصورة<input dir="ltr" value={draft.imageUrl} onChange={e=>set("imageUrl",e.target.value)}/></label></div>
  <label>كود كوبون للقياس<input dir="ltr" value={draft.couponCode} onChange={e=>set("couponCode",e.target.value.toUpperCase())} placeholder="اختياري: SUMMER20"/><small>يربط مبيعات الكود بالحملة تلقائياً، مع بقاء التتبع المباشر متاحاً.</small></label>
 </div><aside className={base.panel}><div className={base.panelHead}><b>معاينة</b><span>{tr(draft.channel)}</span></div><div className={styles.notification}><i>{channelIcons[draft.channel]}</i><div><b>{draft.title||"عنوان الإشعار"}</b><small>{draft.body||"سيظهر نص رسالتك هنا."}</small></div></div></aside></div>
}
function StepSchedule({draft,set}:{draft:CampaignDraft;set:<K extends keyof CampaignDraft>(k:K,v:CampaignDraft[K])=>void}){return <div className={base.form}><b>التوقيت</b><div className={styles.audiences}>{[["Immediate","إرسال فوري","يبدأ الإرسال بمجرد الحفظ"],["Scheduled","جدولة لوقت محدد","اختر التاريخ والوقت"],["Optimal","أفضل وقت تلقائياً","يستخدم أفضل توقيت متاح ويُحفظ كحملة مجدولة"]].map(([id,title,note])=><button type="button" key={id} className={`${styles.audience} ${draft.scheduleType===id?styles.selected:""}`} onClick={()=>set("scheduleType",id)}><input type="radio" readOnly checked={draft.scheduleType===id}/><span><b>{title}</b><small>{note}</small></span></button>)}</div>{draft.scheduleType==="Scheduled"&&<label>موعد الإرسال<input type="datetime-local" value={draft.scheduledAt} onChange={e=>set("scheduledAt",e.target.value)} required/></label>}<label>تكلفة الحملة المتوقعة<input type="number" min="0" step="0.01" value={draft.cost} onChange={e=>set("cost",Number(e.target.value))}/></label></div>}
function StepReview({data,draft}:{data:MarketingDashboard;draft:CampaignDraft}){
 const reference=Math.max(0,...data.tenants.map(x=>x.lastOrderAt?new Date(x.lastOrderAt).getTime():0));
 const count=draft.audienceType==="AllCompanies"?data.tenants.length:draft.audienceType==="Sector"?data.tenants.filter(x=>x.sector===draft.sector).length:draft.audienceType==="SelectedCompanies"?draft.tenantIds.length:data.tenants.filter(x=>x.lastOrderAt&&new Date(x.lastOrderAt).getTime()>=reference-draft.behaviorDays*86400000).length;
 return <div><div className={styles.review}><div><span>الحملة</span><b>{draft.name}</b></div><div><span>القناة</span><b>{tr(draft.channel)}</b></div><div><span>الجمهور</span><b>{tr(draft.audienceType)} · {count} شركة</b></div><div><span>الجدولة</span><b>{tr(draft.scheduleType)} {draft.scheduledAt&&date(draft.scheduledAt)}</b></div><div><span>التكلفة</span><b>{money.format(draft.cost)}</b></div><div><span>الكوبون</span><b>{draft.couponCode||"بدون"}</b></div></div><div className={styles.notification}><i>{channelIcons[draft.channel]}</i><div><b>{draft.title}</b><small>{draft.body}</small></div></div></div>
}

function CouponModal({data,busy,close,saved,fail}:{data:MarketingDashboard;busy:boolean;close:()=>void;saved:()=>Promise<void>;fail:(x:string)=>void}){
 const[audience,setAudience]=useState("AllCompanies"),[sector,setSector]=useState(""),[tenantIds,setTenantIds]=useState<string[]>([]),[saving,setSaving]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{await api("/api/admin/marketing/coupons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({groupId:null,code:f.get("code"),nameAr:f.get("nameAr"),discountType:f.get("discountType"),discountValue:Number(f.get("discountValue")),minimumSubtotal:Number(f.get("minimumSubtotal")),maximumDiscount:f.get("maximumDiscount")?Number(f.get("maximumDiscount")):null,startsAt:f.get("startsAt")?new Date(String(f.get("startsAt"))).toISOString():null,expiresAt:f.get("expiresAt")?new Date(String(f.get("expiresAt"))).toISOString():null,usageLimit:f.get("usageLimit")?Number(f.get("usageLimit")):null,oncePerCompany:f.get("oncePerCompany")==="on",newCustomersOnly:f.get("newCustomersOnly")==="on",excludeDiscountedProducts:f.get("excludeDiscountedProducts")==="on",canCombine:f.get("canCombine")==="on",categoryIds:f.getAll("categoryIds"),audienceType:audience,sector:sector||null,tenantIds,isActive:true})});await saved()}catch(e){fail((e as Error).message)}finally{setSaving(false)}}
 return <div className={base.modalBack}><section className={base.modal}><header><div><h2>كوبون جديد</h2><small>إنشاء كود خصم بشروط وجمهور محدد</small></div><button onClick={close}>×</button></header><form className={base.form} onSubmit={submit}>
  <div className={base.cols}><label>الكود<input name="code" dir="ltr" required placeholder="SUMMER20"/></label><label>اسم العرض<input name="nameAr" required placeholder="خصم الصيف"/></label></div>
  <div className={base.cols}><label>نوع الخصم<select name="discountType"><option value="Percentage">نسبة مئوية</option><option value="Fixed">قيمة ثابتة</option></select></label><label>قيمة الخصم<input name="discountValue" type="number" min="0.01" step="0.01" required/></label></div>
  <div className={base.cols}><label>الحد الأدنى للطلب<input name="minimumSubtotal" type="number" min="0" defaultValue="0"/></label><label>الحد الأقصى للخصم<input name="maximumDiscount" type="number" min="0"/></label></div>
  <div className={base.cols}><label>بداية الصلاحية<input name="startsAt" type="datetime-local"/></label><label>تاريخ الانتهاء<input name="expiresAt" type="datetime-local"/></label></div>
  <label>عدد الاستخدامات<input name="usageLimit" type="number" min="1"/></label>
  <label>الجمهور<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="AllCompanies">كل الشركات</option><option value="Sector">قطاع محدد</option><option value="SelectedCompanies">شركات محددة</option></select></label>
  {audience==="Sector"&&<label>القطاع<select value={sector} onChange={e=>setSector(e.target.value)} required><option value="">اختر القطاع</option>{data.sectors.map(x=><option key={x}>{x}</option>)}</select></label>}
  {audience==="SelectedCompanies"&&<TenantPicker tenants={data.tenants} selected={tenantIds} set={setTenantIds}/>} 
  {data.categories.length>0&&<div><b>الأقسام التي ينطبق عليها</b><div className={styles.conditionList}>{data.categories.map(x=><label key={x.id}><span>{x.name}</span><input name="categoryIds" value={x.id} type="checkbox"/></label>)}</div></div>}
  <div className={styles.conditionList}><label><span>مرة واحدة لكل شركة</span><input name="oncePerCompany" type="checkbox"/></label><label><span>للعملاء الجدد فقط</span><input name="newCustomersOnly" type="checkbox"/></label><label><span>استبعاد المنتجات المخفضة</span><input name="excludeDiscountedProducts" type="checkbox"/></label><label><span>يمكن جمعه مع خصم آخر</span><input name="canCombine" type="checkbox" defaultChecked/></label></div>
  <footer><button type="button" className={base.secondary} onClick={close}>إلغاء</button><button className={base.primary} disabled={busy||saving}>{saving?"جاري الحفظ...":"حفظ الكوبون"}</button></footer>
 </form></section></div>
}
function hour(value:number){const suffix=value<12?"ص":"م",hour=value%12||12;return `${hour}:00 ${suffix}`}
function exportCsv(name:string,rows:unknown[]){if(!rows.length)return;const objects=rows as Record<string,unknown>[],keys=Object.keys(objects[0]);const cell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const csv="\uFEFF"+[keys.join(","),...objects.map(x=>keys.map(k=>cell(x[k])).join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
