"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { money, OrderPage, RecurringOrder, statusName } from "./order-types";

type View = "active"|"late"|"archived"|"recurring";
const statuses=["PendingApproval","Confirmed","Processing","Picking","Packing","Shipped","OutForDelivery","Delivered","Delayed","Cancelled"];

export function OrderManager(){
  const [view,setView]=useState<View>("active"); const [data,setData]=useState<OrderPage|null>(null); const [recurring,setRecurring]=useState<RecurringOrder[]>([]);
  const [query,setQuery]=useState(""); const [status,setStatus]=useState(""); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [filters,setFilters]=useState(false);
  const load=useCallback(async(signal?:AbortSignal)=>{
    if(view==="recurring"){const response=await fetch("/api/admin/orders/recurring",{signal});if(!response.ok)throw new Error("تعذر تحميل الطلبات المتكررة");setRecurring(await response.json());return;}
    const params=new URLSearchParams({search:query,statuses:status,page:String(page),pageSize:"20",archived:String(view==="archived"),overdue:String(view==="late")});
    const response=await fetch(`/api/admin/orders?${params}`,{signal});if(!response.ok)throw new Error("تعذر تحميل الطلبات");setData(await response.json());
  },[view,query,status,page]);
  useEffect(()=>{const controller=new AbortController();if(view==="recurring"){fetch("/api/admin/orders/recurring",{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("تعذر تحميل الطلبات المتكررة");setRecurring(await response.json());setLoading(false)}).catch(reason=>{if(reason.name!=="AbortError"){setError(reason.message);setLoading(false)}})}else{const params=new URLSearchParams({search:query,statuses:status,page:String(page),pageSize:"20",archived:String(view==="archived"),overdue:String(view==="late")});fetch(`/api/admin/orders?${params}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("تعذر تحميل الطلبات");setData(await response.json());setLoading(false)}).catch(reason=>{if(reason.name!=="AbortError"){setError(reason.message);setLoading(false)}})}return()=>controller.abort()},[view,query,status,page]);
  async function refresh(){setLoading(true);setError("");try{await load()}catch(reason){setError(reason instanceof Error?reason.message:"تعذر التحميل")}finally{setLoading(false)}}
  function changeView(next:View){setView(next);setPage(1);setLoading(true);setError("")}
  function search(event:FormEvent){event.preventDefault();setPage(1);setLoading(true);refresh()}
  function exportRows(){if(!data)return;const rows=[["الطلب","الشركة","العميل","الحالة","الإجمالي","موعد التسليم"],...data.items.map(x=>[x.number,x.company,x.customer,statusName[x.status]??x.status,String(x.total),x.requiredDate])];const csv="\uFEFF"+rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="orders.csv";a.click();URL.revokeObjectURL(url)}
  async function toggleSchedule(item:RecurringOrder){const response=await fetch(`/api/admin/orders/recurring/${item.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({isActive:!item.isActive,nextRunAt:null})});if(response.ok)refresh()}
  const summary=data?.summary;
  return <>
    <div className="page-heading order-heading"><div><p>المبيعات / الطلبات</p><h1>{view==="late"?"الطلبات المتأخرة":view==="archived"?"الطلبات المؤرشفة":view==="recurring"?"الطلبات المجدولة والمتكررة":"الطلبات"}</h1><span>{view==="recurring"?"إدارة القوالب الدورية لكل الشركات":`${data?.total??0} طلب مطابق`}</span></div><div className="heading-actions"><button className="secondary-button" onClick={exportRows} disabled={view==="recurring"}>تصدير</button><button className="primary-button" onClick={()=>setFilters(true)}>فلترة متقدمة</button></div></div>
    <div className="order-view-tabs">{([["active","كل الطلبات"],["late","المتأخرة"],["archived","الأرشيف"],["recurring","المجدولة والمتكررة"]] as const).map(([key,label])=><button key={key} className={view===key?"active":""} onClick={()=>changeView(key)}>{label}{key==="late"&&summary?<em>{summary.late}</em>:null}</button>)}</div>
    {view!=="recurring"&&summary&&<section className="order-kpis"><article><span>إجمالي الطلبات</span><b>{summary.total}</b></article><article><span>جديدة اليوم</span><b>{summary.newToday}</b></article><article><span>قيد التجهيز</span><b>{summary.processing}</b></article><article><span>خرجت للتوصيل</span><b>{summary.outForDelivery}</b></article><article className="danger"><span>متأخرة</span><b>{summary.late}</b></article></section>}
    {view!=="recurring"&&<form className="panel order-toolbar" onSubmit={search}><div className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث برقم الطلب، الشركة أو PO"/></div><select value={status} onChange={e=>{setStatus(e.target.value);setLoading(true)}}><option value="">كل الحالات</option>{statuses.map(x=><option key={x} value={x}>{statusName[x]??x}</option>)}</select><button className="secondary-button">بحث</button><span>{data?.total??0} نتيجة</span></form>}
    {error&&<div className="admin-alert"><span>{error}</span><button onClick={refresh}>إعادة المحاولة</button></div>}
    {loading?<div className="admin-loading"><span className="loading-ring"/>جاري تحميل الطلبات...</div>:view==="recurring"?<section className="panel recurring-panel"><div className="recurring-summary"><article><span>قوالب نشطة</span><b>{recurring.filter(x=>x.isActive).length}</b></article><article><span>إيراد متكرر متوقع</span><b>{money.format(recurring.filter(x=>x.isActive).reduce((s,x)=>s+x.estimatedValue,0))}</b></article><article><span>موقوفة مؤقتًا</span><b>{recurring.filter(x=>!x.isActive).length}</b></article></div><div className="table-wrap"><table><thead><tr><th>الطلب</th><th>الشركة</th><th>التكرار</th><th>التنفيذ القادم</th><th>القيمة</th><th>الحالة</th><th/></tr></thead><tbody>{recurring.map(item=><tr key={item.id}><td>{item.orderNumber}</td><td>{item.company}</td><td>{item.frequency} × {item.interval}</td><td>{new Date(item.nextRunAt).toLocaleDateString("ar-EG")}</td><td>{money.format(item.estimatedValue)}</td><td><span className="status-chip">{item.isActive?"نشط":"موقوف"}</span></td><td><button onClick={()=>toggleSchedule(item)}>{item.isActive?"إيقاف":"تفعيل"}</button></td></tr>)}</tbody></table></div>{!recurring.length&&<div className="admin-empty compact">لا توجد قوالب دورية</div>}</section>:<section className="panel orders-admin-panel"><div className="table-wrap"><table className="orders-admin-table"><thead><tr><th>رقم الطلب</th><th>الشركة / العميل</th><th>التاريخ</th><th>المطلوب</th><th>الإجمالي</th><th>الحالة</th><th>المسؤول</th><th/></tr></thead><tbody>{data?.items.map(order=><tr key={order.id} className={order.isLate?"late-row":""}><td><Link href={`/dashboard/orders/${order.id}`}><b>{order.number}</b><small>{order.purchaseOrderNumber??`${order.itemCount} أصناف`}</small></Link></td><td><b>{order.company}</b><small>{order.customer}</small></td><td>{new Date(order.createdAt).toLocaleDateString("ar-EG")}</td><td className={order.isLate?"late-date":""}>{new Date(order.requiredDate).toLocaleDateString("ar-EG")}</td><td>{money.format(order.total)}</td><td><span className={`status-chip status-${order.status.toLowerCase()}`}>{statusName[order.status]??order.status}</span></td><td>{order.assignedStaff??"غير مخصص"}</td><td><Link className="row-open" href={`/dashboard/orders/${order.id}`}>عرض ←</Link></td></tr>)}</tbody></table></div>{!data?.items.length&&<div className="admin-empty compact">لا توجد طلبات مطابقة</div>}<div className="admin-pagination"><button disabled={page<=1} onClick={()=>{setPage(page-1);setLoading(true)}}>السابق</button><span>صفحة {page}</span><button disabled={page*20>=(data?.total??0)} onClick={()=>{setPage(page+1);setLoading(true)}}>التالي</button></div></section>}
    {filters&&<div className="modal-backdrop"><section className="mini-editor order-filter-modal"><header><div><h2>فلترة الطلبات المتقدمة</h2><p>حدد المعايير ثم اعرض النتائج</p></div><button onClick={()=>setFilters(false)}>×</button></header><form onSubmit={event=>{event.preventDefault();setFilters(false);setLoading(true);refresh()}}><label>الحالة<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option>{statuses.map(x=><option key={x} value={x}>{statusName[x]??x}</option>)}</select></label><label>بحث عام<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="رقم الطلب أو الشركة أو PO"/></label><div className="filter-shortcuts"><button type="button" onClick={()=>changeView("late")}>عرض المتأخرة</button><button type="button" onClick={()=>changeView("archived")}>عرض الأرشيف</button></div><footer><button type="button" className="secondary-button" onClick={()=>{setQuery("");setStatus("")}}>مسح</button><button className="primary-button">تطبيق الفلاتر</button></footer></form></section></div>}
  </>;
}
