using Microsoft.EntityFrameworkCore;
using Mohandseto.Api.Application.AdminInventory;
using Mohandseto.Api.Application.Common;
using Mohandseto.Api.Domain.Entities;
using Mohandseto.Api.Infrastructure;

namespace Mohandseto.Api.Application.AdminProcurement;

public sealed class AdminProcurementService(AppDbContext db, AdminInventoryService inventory)
{
    public async Task<ProcurementDashboardDto> DashboardAsync(CancellationToken ct = default)
    {
        var suppliers = await db.Suppliers.AsNoTracking().OrderBy(x => x.NameAr).ToListAsync(ct); var products = await db.Products.AsNoTracking().OrderBy(x => x.NameAr).ToListAsync(ct); var warehouses = await db.Warehouses.AsNoTracking().OrderBy(x => x.NameAr).ToListAsync(ct);
        var supplierProducts = await db.SupplierProducts.AsNoTracking().ToListAsync(ct); var documents = await db.SupplierDocuments.AsNoTracking().ToListAsync(ct); var orders = await db.PurchaseOrders.AsNoTracking().Include(x => x.Items).OrderByDescending(x => x.CreatedAt).ToListAsync(ct); var invoices = await db.SupplierInvoices.AsNoTracking().OrderByDescending(x => x.IssuedAt).ToListAsync(ct); var receipts = await db.GoodsReceipts.AsNoTracking().Include(x => x.Items).Where(x => x.PurchaseOrderId != null).ToListAsync(ct);
        var productMap = products.ToDictionary(x => x.Id); var supplierMap = suppliers.ToDictionary(x => x.Id); var warehouseMap = warehouses.ToDictionary(x => x.Id); var orderMap = orders.ToDictionary(x => x.Id);
        var supplierDtos = suppliers.Select(s => new SupplierAdminDto(s.Id, s.Code, s.NameAr, s.NameEn, s.ContactName, s.Phone, s.Email, s.Address, s.CommercialRegistrationNo, s.TaxRegistrationNo, s.TypicalLeadDays, s.PaymentTermsDays, s.CreditLimit, s.Rating, s.IsActive, s.Notes,
            supplierProducts.Where(x => x.SupplierId == s.Id && productMap.ContainsKey(x.ProductId)).Select(x => new SupplierProductDto(x.ProductId, productMap[x.ProductId].Sku, productMap[x.ProductId].NameAr, x.SupplierSku, x.UnitPrice, x.MinimumQuantity, x.LeadDays, x.ValidFrom, x.ValidUntil, x.IsPreferred)).ToList(),
            documents.Where(x => x.SupplierId == s.Id).Select(x => new SupplierDocumentDto(x.Id, x.NameAr, x.Type, x.Path, x.ExpiresAt)).ToList(), orders.Count(x => x.SupplierId == s.Id), invoices.Where(x => x.SupplierId == s.Id).Sum(x => x.Amount - x.PaidAmount))).ToList();
        var orderDtos = orders.Where(x => supplierMap.ContainsKey(x.SupplierId) && warehouseMap.ContainsKey(x.WarehouseId)).Select(x => new PurchaseOrderDto(x.Id, x.Number, x.SupplierId, supplierMap[x.SupplierId].NameAr, x.WarehouseId, warehouseMap[x.WarehouseId].NameAr, x.Status.ToString(), x.ExpectedAt, x.SentAt, x.Subtotal, x.Tax, x.Shipping, x.Total, x.Notes, x.CreatedAt, x.Items.Where(i => productMap.ContainsKey(i.ProductId)).Select(i => new PurchaseOrderItemDto(i.ProductId, productMap[i.ProductId].Sku, productMap[i.ProductId].NameAr, i.OrderedQty, i.ReceivedQty, i.UnitPrice, i.LineTotal)).ToList())).ToList();
        var invoiceDtos = invoices.Where(x => supplierMap.ContainsKey(x.SupplierId) && orderMap.ContainsKey(x.PurchaseOrderId)).Select(x => new SupplierInvoiceDto(x.Id, x.Number, supplierMap[x.SupplierId].NameAr, orderMap[x.PurchaseOrderId].Number, x.SupplierInvoiceNumber, x.Amount, x.PaidAmount, x.Amount - x.PaidAmount, x.IssuedAt, x.DueAt, x.Status.ToString(), x.VarianceAmount)).ToList();
        var performance = suppliers.Select(s => { var supplierOrders = orders.Where(x => x.SupplierId == s.Id).ToList(); var supplierReceipts = receipts.Where(x => x.SupplierId == s.Id).ToList(); var received = supplierReceipts.SelectMany(x => x.Items).Sum(x => x.ReceivedQty); var accepted = supplierReceipts.SelectMany(x => x.Items).Sum(x => x.AcceptedQty); return new SupplierPerformanceDto(s.Id, s.NameAr, s.Rating, supplierOrders.Count == 0 ? 100 : Math.Round(100m * supplierOrders.Count(x => x.Status == PurchaseOrderStatus.Received && x.ExpectedAt >= x.UpdatedAt) / supplierOrders.Count, 1), received == 0 ? 100 : Math.Round(100m * accepted / received, 1), supplierOrders.Count, supplierOrders.Sum(x => x.Total), invoices.Where(x => x.SupplierId == s.Id).Sum(x => x.Amount - x.PaidAmount)); }).ToList();
        return new(supplierDtos, orderDtos, invoiceDtos, performance, products.Select(x => new ProcurementProductOptionDto(x.Id, x.Sku, x.NameAr, x.CostPrice)).ToList(), warehouses.Select(x => new ProcurementWarehouseOptionDto(x.Id, x.NameAr)).ToList());
    }

    public async Task SaveSupplierAsync(Guid? id, SaveSupplierDto dto, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(dto.Code) || string.IsNullOrWhiteSpace(dto.NameAr)) throw ApiException.BadRequest("كود واسم المورد مطلوبان"); var code = dto.Code.Trim().ToUpperInvariant(); if (await db.Suppliers.AnyAsync(x => x.Id != id && x.Code == code, ct)) throw ApiException.Conflict("كود المورد مستخدم بالفعل");
        var s = id is null ? new Supplier() : await db.Suppliers.FirstOrDefaultAsync(x => x.Id == id, ct) ?? throw ApiException.NotFound("المورد غير موجود"); s.Code = code; s.NameAr = dto.NameAr.Trim(); s.NameEn = Empty(dto.NameEn); s.ContactName = Empty(dto.ContactName); s.Phone = Empty(dto.Phone); s.Email = Empty(dto.Email); s.Address = Empty(dto.Address); s.CommercialRegistrationNo = Empty(dto.CommercialRegistrationNo); s.TaxRegistrationNo = Empty(dto.TaxRegistrationNo); s.TypicalLeadDays = Math.Max(0, dto.TypicalLeadDays); s.PaymentTermsDays = Math.Max(0, dto.PaymentTermsDays); s.CreditLimit = Math.Max(0, dto.CreditLimit); s.IsActive = dto.IsActive; s.Notes = Empty(dto.Notes); if (id is null) db.Suppliers.Add(s); await db.SaveChangesAsync(ct);
    }
    public async Task ReplaceProductsAsync(Guid id, ReplaceSupplierProductsDto dto, CancellationToken ct = default) { if (!await db.Suppliers.AnyAsync(x => x.Id == id, ct)) throw ApiException.NotFound("المورد غير موجود"); if (dto.Products.Select(x => x.ProductId).Distinct().Count() != dto.Products.Count || dto.Products.Any(x => x.UnitPrice <= 0 || x.MinimumQuantity <= 0)) throw ApiException.BadRequest("قائمة أسعار المورد غير صالحة"); var ids = dto.Products.Select(x => x.ProductId).ToList(); if (await db.Products.CountAsync(x => ids.Contains(x.Id), ct) != ids.Count) throw ApiException.BadRequest("أحد المنتجات غير موجود"); db.SupplierProducts.RemoveRange(await db.SupplierProducts.Where(x => x.SupplierId == id).ToListAsync(ct)); db.SupplierProducts.AddRange(dto.Products.Select(x => new SupplierProduct { SupplierId = id, ProductId = x.ProductId, SupplierSku = Empty(x.SupplierSku), UnitPrice = x.UnitPrice, MinimumQuantity = x.MinimumQuantity, LeadDays = x.LeadDays, ValidFrom = x.ValidFrom, ValidUntil = x.ValidUntil, IsPreferred = x.IsPreferred })); await db.SaveChangesAsync(ct); }
    public async Task RateAsync(Guid actor, Guid id, RateSupplierDto dto, CancellationToken ct = default) { if (new[] { dto.Quality, dto.Delivery, dto.Price, dto.Communication }.Any(x => x is < 1 or > 5)) throw ApiException.BadRequest("التقييم يجب أن يكون من 1 إلى 5"); var supplier = await db.Suppliers.FirstOrDefaultAsync(x => x.Id == id, ct) ?? throw ApiException.NotFound("المورد غير موجود"); db.SupplierRatingRecords.Add(new SupplierRatingRecord { SupplierId = id, RatedByUserId = actor, Quality = dto.Quality, Delivery = dto.Delivery, Price = dto.Price, Communication = dto.Communication, Comment = Empty(dto.Comment) }); var existing = await db.SupplierRatingRecords.Where(x => x.SupplierId == id).Select(x => (decimal)(x.Quality + x.Delivery + x.Price + x.Communication) / 4).ToListAsync(ct); existing.Add((dto.Quality + dto.Delivery + dto.Price + dto.Communication) / 4m); supplier.Rating = Math.Round(existing.Average(), 2); await db.SaveChangesAsync(ct); }
    public async Task AddDocumentAsync(Guid id, AddSupplierDocumentDto dto, CancellationToken ct = default) { if (!await db.Suppliers.AnyAsync(x => x.Id == id, ct)) throw ApiException.NotFound("المورد غير موجود"); if (string.IsNullOrWhiteSpace(dto.NameAr) || string.IsNullOrWhiteSpace(dto.Type) || string.IsNullOrWhiteSpace(dto.Path)) throw ApiException.BadRequest("بيانات المستند مطلوبة"); db.SupplierDocuments.Add(new SupplierDocument { SupplierId = id, NameAr = dto.NameAr.Trim(), Type = dto.Type.Trim(), Path = dto.Path.Trim(), ExpiresAt = dto.ExpiresAt }); await db.SaveChangesAsync(ct); }
    public async Task<Guid> CreateOrderAsync(Guid actor, CreatePurchaseOrderDto dto, CancellationToken ct = default) { if (dto.Items.Count == 0 || dto.Items.Select(x => x.ProductId).Distinct().Count() != dto.Items.Count || dto.Items.Any(x => x.Quantity <= 0 || x.UnitPrice <= 0)) throw ApiException.BadRequest("أصناف أمر الشراء غير صالحة"); if (!await db.Suppliers.AnyAsync(x => x.Id == dto.SupplierId && x.IsActive, ct) || !await db.Warehouses.AnyAsync(x => x.Id == dto.WarehouseId && x.IsActive, ct)) throw ApiException.BadRequest("المورد أو المخزن غير صالح"); var subtotal = dto.Items.Sum(x => x.Quantity * x.UnitPrice); var order = new PurchaseOrder { Number = Number("PO"), SupplierId = dto.SupplierId, WarehouseId = dto.WarehouseId, ExpectedAt = dto.ExpectedAt, Subtotal = subtotal, Tax = Math.Max(0, dto.Tax), Shipping = Math.Max(0, dto.Shipping), Total = subtotal + Math.Max(0, dto.Tax) + Math.Max(0, dto.Shipping), Notes = Empty(dto.Notes), CreatedByUserId = actor, Items = dto.Items.Select(x => new PurchaseOrderItem { ProductId = x.ProductId, OrderedQty = x.Quantity, UnitPrice = x.UnitPrice, LineTotal = x.Quantity * x.UnitPrice }).ToList() }; db.PurchaseOrders.Add(order); await db.SaveChangesAsync(ct); return order.Id; }
    public async Task SendOrderAsync(Guid id, CancellationToken ct = default) { var order = await db.PurchaseOrders.FirstOrDefaultAsync(x => x.Id == id, ct) ?? throw ApiException.NotFound("أمر الشراء غير موجود"); if (order.Status != PurchaseOrderStatus.Draft) throw ApiException.Conflict("لا يمكن إرسال أمر الشراء في حالته الحالية"); order.Status = PurchaseOrderStatus.Sent; order.SentAt = DateTime.UtcNow; await db.SaveChangesAsync(ct); }
    public async Task ReceiveAsync(Guid actor, Guid id, ReceivePurchaseOrderDto dto, CancellationToken ct = default) { var order = await db.PurchaseOrders.Include(x => x.Items).FirstOrDefaultAsync(x => x.Id == id, ct) ?? throw ApiException.NotFound("أمر الشراء غير موجود"); if (order.Status is PurchaseOrderStatus.Draft or PurchaseOrderStatus.Cancelled or PurchaseOrderStatus.Received) throw ApiException.Conflict("لا يمكن الاستلام على أمر الشراء في حالته الحالية"); var inputs = dto.Items.ToDictionary(x => x.ProductId); foreach (var input in dto.Items) { var item = order.Items.FirstOrDefault(x => x.ProductId == input.ProductId) ?? throw ApiException.BadRequest("الصنف غير موجود بأمر الشراء"); if (input.Quantity <= 0 || item.ReceivedQty + input.Quantity > item.OrderedQty) throw ApiException.Conflict("كمية الاستلام تتجاوز المتبقي"); } var receiptItems = dto.Items.Select(x => { var poItem = order.Items.Single(i => i.ProductId == x.ProductId); poItem.ReceivedQty += x.Quantity; return new CreateGoodsReceiptItemDto(x.ProductId, x.Quantity, poItem.UnitPrice, x.BatchNumber, x.ExpiryAt); }).ToList(); await inventory.CreateReceiptAsync(actor, new(order.WarehouseId, order.SupplierId, dto.SupplierReference, receiptItems, order.Id), ct); order.Status = order.Items.All(x => x.ReceivedQty == x.OrderedQty) ? PurchaseOrderStatus.Received : PurchaseOrderStatus.PartiallyReceived; await db.SaveChangesAsync(ct); }
    public async Task CreateInvoiceAsync(CreateSupplierInvoiceDto dto, CancellationToken ct = default) { var order = await db.PurchaseOrders.Include(x => x.Items).FirstOrDefaultAsync(x => x.Id == dto.PurchaseOrderId, ct) ?? throw ApiException.NotFound("أمر الشراء غير موجود"); if (await db.SupplierInvoices.AnyAsync(x => x.SupplierId == order.SupplierId && x.SupplierInvoiceNumber == dto.SupplierInvoiceNumber, ct)) throw ApiException.Conflict("فاتورة المورد مسجلة بالفعل"); var receipts = await db.GoodsReceipts.AsNoTracking().Include(x => x.Items).Where(x => x.PurchaseOrderId == order.Id && x.Status != GoodsReceiptStatus.Inspection && x.Status != GoodsReceiptStatus.Rejected).ToListAsync(ct); var quantitiesMatch = order.Items.All(item => receipts.SelectMany(x => x.Items).Where(x => x.ProductId == item.ProductId).Sum(x => x.AcceptedQty) == item.OrderedQty); var variance = dto.Amount - order.Total; db.SupplierInvoices.Add(new SupplierInvoice { Number = Number("SINV"), SupplierId = order.SupplierId, PurchaseOrderId = order.Id, SupplierInvoiceNumber = dto.SupplierInvoiceNumber.Trim(), Amount = dto.Amount, IssuedAt = dto.IssuedAt, DueAt = dto.DueAt, VarianceAmount = variance, Status = Math.Abs(variance) < .01m && quantitiesMatch ? SupplierInvoiceStatus.Matched : SupplierInvoiceStatus.Variance }); await db.SaveChangesAsync(ct); }
    public async Task CreateReturnAsync(Guid actor, CreateSupplierReturnDto dto, CancellationToken ct = default) { var order = await db.PurchaseOrders.Include(x => x.Items).FirstOrDefaultAsync(x => x.Id == dto.PurchaseOrderId, ct) ?? throw ApiException.NotFound("أمر الشراء غير موجود"); var item = order.Items.FirstOrDefault(x => x.ProductId == dto.ProductId) ?? throw ApiException.BadRequest("الصنف غير موجود بأمر الشراء"); if (dto.Quantity <= 0 || dto.Quantity > item.ReceivedQty) throw ApiException.BadRequest("كمية المرتجع غير صالحة"); await inventory.AdjustAsync(actor, new(order.WarehouseId, dto.ProductId, dto.Quantity, "Deduct", $"مرتجع مورد: {dto.Reason}", null, null, null, null), ct); db.SupplierReturns.Add(new SupplierReturn { Number = Number("SRET"), SupplierId = order.SupplierId, PurchaseOrderId = order.Id, ProductId = dto.ProductId, Quantity = dto.Quantity, Reason = dto.Reason.Trim(), Amount = dto.Quantity * item.UnitPrice, Status = SupplierReturnStatus.Sent }); await db.SaveChangesAsync(ct); }
    private static string Number(string prefix) => $"{prefix}-{DateTime.UtcNow:yyMMddHHmmss}-{Guid.NewGuid().ToString("N")[..5].ToUpperInvariant()}";
    private static string? Empty(string? value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim();
}
