"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Section = { id: string; key: string; nameAr: string; sortOrder: number; isActive: boolean; settingsJson?: string };
type Banner = { id: string; titleAr: string; subtitleAr?: string; imageUrl: string; actionUrl?: string; targetTenantId?: string; targetTenantName?: string; startsAt: string; endsAt?: string; sortOrder: number; isActive: boolean; state: string };
type Page = { id: string; slug: string; titleAr: string; bodyAr: string; contactPhone?: string; whatsAppPhone?: string; contactEmail?: string; address?: string; isPublished: boolean; updatedAt?: string };
type Faq = { id: string; slug: string; category: string; questionAr: string; answerAr: string; sortOrder: number; isPublished: boolean };
type Dispatch = { id: string; channel: string; titleAr: string; bodyAr: string; actionUrl?: string; targetTenantId?: string; targetTenantName?: string; scheduledAt?: string; sentAt?: string; status: string; recipientCount: number; createdAt: string };
type Tenant = { id: string; name: string };
type Dashboard = { sections: Section[]; banners: Banner[]; pages: Page[]; faq: Faq[]; dispatches: Dispatch[]; tenants: Tenant[] };
type Tab = "home" | "banners" | "pages" | "faq" | "messages";
type Editor = { kind: "section"; item?: Section } | { kind: "banner"; item?: Banner } | { kind: "page"; item?: Page } | { kind: "faq"; item?: Faq } | { kind: "dispatch"; channel: "AppNotification" | "InAppMessage" };

const stateLabels: Record<string, string> = { Active: "نشط", Scheduled: "مجدول", Expired: "منتهي", Inactive: "معطل", Draft: "مسودة", Sent: "تم الإرسال", Cancelled: "ملغي" };
const inputDate = (value?: string) => value ? new Date(value).toISOString().slice(0, 16) : "";
const displayDate = (value?: string) => value ? new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

export function ContentManager() {
  const [data, setData] = useState<Dashboard | null>(null); const [tab, setTab] = useState<Tab>("home"); const [editor, setEditor] = useState<Editor | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [dragged, setDragged] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/admin/content"); if (!response.ok) throw new Error("تعذر تحميل إدارة المحتوى"); return response.json() as Promise<Dashboard>; }, []);
  useEffect(() => { let active = true; load().then((result) => { if (active) { setData(result); setLoading(false); } }).catch((reason) => { if (active) { setError(reason.message); setLoading(false); } }); return () => { active = false; }; }, [load]);
  async function api(url: string, method: string, body?: unknown) { const response = await fetch(url, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); if (!response.ok) { const result = await response.json().catch(() => ({})); throw new Error(result.title || "تعذر تنفيذ العملية"); } return response.status === 204 ? null : response.json(); }
  async function refresh(message?: string) { setData(await load()); if (message) { setNotice(message); setTimeout(() => setNotice(""), 3500); } }
  const policies = useMemo(() => data?.pages.filter((item) => ["terms", "privacy", "returns-policy", "shipping-policy"].includes(item.slug)) ?? [], [data]);

  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editor) return; setSaving(true); setError(""); const form = new FormData(event.currentTarget);
    try {
      if (editor.kind === "section") await api(editor.item ? `/api/admin/content/sections/${editor.item.id}` : "/api/admin/content/sections", editor.item ? "PUT" : "POST", { key: form.get("key"), nameAr: form.get("nameAr"), sortOrder: Number(form.get("sortOrder")), isActive: form.get("isActive") === "on", settingsJson: form.get("settingsJson") || null });
      if (editor.kind === "banner") await api(editor.item ? `/api/admin/content/banners/${editor.item.id}` : "/api/admin/content/banners", editor.item ? "PUT" : "POST", { titleAr: form.get("titleAr"), subtitleAr: form.get("subtitleAr") || null, imageUrl: form.get("imageUrl"), actionUrl: form.get("actionUrl") || null, targetTenantId: form.get("targetTenantId") || null, startsAt: new Date(String(form.get("startsAt"))).toISOString(), endsAt: form.get("endsAt") ? new Date(String(form.get("endsAt"))).toISOString() : null, sortOrder: Number(form.get("sortOrder")), isActive: form.get("isActive") === "on" });
      if (editor.kind === "page") await api(editor.item ? `/api/admin/content/pages/${editor.item.id}` : "/api/admin/content/pages", editor.item ? "PUT" : "POST", { slug: form.get("slug"), titleAr: form.get("titleAr"), bodyAr: form.get("bodyAr"), contactPhone: form.get("contactPhone") || null, whatsAppPhone: form.get("whatsAppPhone") || null, contactEmail: form.get("contactEmail") || null, address: form.get("address") || null, isPublished: form.get("isPublished") === "on" });
      if (editor.kind === "faq") await api(editor.item ? `/api/admin/content/faq/${editor.item.id}` : "/api/admin/content/faq", editor.item ? "PUT" : "POST", { slug: form.get("slug"), category: form.get("category"), questionAr: form.get("questionAr"), answerAr: form.get("answerAr"), sortOrder: Number(form.get("sortOrder")), isPublished: form.get("isPublished") === "on" });
      if (editor.kind === "dispatch") await api("/api/admin/content/dispatches", "POST", { channel: editor.channel, titleAr: form.get("titleAr"), bodyAr: form.get("bodyAr"), actionUrl: form.get("actionUrl") || null, targetTenantId: form.get("targetTenantId") || null, scheduledAt: form.get("scheduledAt") ? new Date(String(form.get("scheduledAt"))).toISOString() : null, sendNow: form.get("sendNow") === "on" });
      setEditor(null); await refresh(editor.kind === "dispatch" ? "تم حفظ الحملة بنجاح" : "تم حفظ المحتوى بنجاح");
    } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر الحفظ"); } finally { setSaving(false); }
  }
  async function remove(kind: "sections" | "banners" | "pages" | "faq", id: string, name: string) { if (!confirm(`حذف «${name}»؟`)) return; try { await api(`/api/admin/content/${kind}/${id}`, "DELETE"); await refresh("تم الحذف"); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر الحذف"); } }
  async function send(id: string) { if (!confirm("إرسال الرسالة الآن إلى الجمهور المحدد؟")) return; try { await api(`/api/admin/content/dispatches/${id}/send`, "POST"); await refresh("تم إرسال الرسالة"); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر الإرسال"); } }
  async function dropSection(target: string) { if (!data || !dragged || target === dragged) return; const sections = [...data.sections]; const from = sections.findIndex((x) => x.id === dragged); const to = sections.findIndex((x) => x.id === target); const [moved] = sections.splice(from, 1); sections.splice(to, 0, moved); const ordered = sections.map((x, index) => ({ ...x, sortOrder: index })); setData({ ...data, sections: ordered }); setDragged(null); try { await api("/api/admin/content/sections/reorder", "PUT", { items: ordered.map((x) => ({ id: x.id, sortOrder: x.sortOrder })) }); setNotice("تم حفظ ترتيب الصفحة الرئيسية"); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر حفظ الترتيب"); setData(await load()); } }

  if (loading) return <div className="admin-loading">جاري تحميل إدارة المحتوى...</div>; if (!data) return <div className="admin-alert">{error || "لا توجد بيانات"}</div>;
  return <>
    <div className="page-heading catalog-heading"><div><p>المحتوى والتواصل</p><h1>إدارة تجربة التطبيق</h1><span>تحكم في الصفحة الرئيسية والبنرات والسياسات والرسائل من مكان واحد</span></div><div className="content-heading-actions">{tab === "home" && <button className="primary-button" onClick={() => setEditor({ kind: "section" })}>+ قسم رئيسي</button>}{tab === "banners" && <button className="primary-button" onClick={() => setEditor({ kind: "banner" })}>+ بنر جديد</button>}{tab === "pages" && <button className="primary-button" onClick={() => setEditor({ kind: "page" })}>+ صفحة محتوى</button>}{tab === "faq" && <button className="primary-button" onClick={() => setEditor({ kind: "faq" })}>+ سؤال شائع</button>}{tab === "messages" && <><button className="secondary-button" onClick={() => setEditor({ kind: "dispatch", channel: "InAppMessage" })}>رسالة داخل التطبيق</button><button className="primary-button" onClick={() => setEditor({ kind: "dispatch", channel: "AppNotification" })}>+ إشعار تطبيق</button></>}</div></div>
    {error && <div className="admin-alert">{error}<button onClick={() => setError("")}>×</button></div>}{notice && <div className="admin-success">✓ {notice}</div>}
    <div className="catalog-tabs content-tabs">{([ ["home", "الصفحة الرئيسية"], ["banners", "البنرات"], ["pages", "الصفحات والسياسات"], ["faq", "الأسئلة الشائعة"], ["messages", "الإشعارات والرسائل"] ] as [Tab, string][]).map(([key, label]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label}</button>)}</div>
    {tab === "home" && <section className="content-layout"><div className="panel content-list-panel"><header><div><h2>أقسام الصفحة الرئيسية</h2><p>اسحب البطاقات لترتيب ظهورها في التطبيق</p></div><span>{data.sections.filter((x) => x.isActive).length} نشط</span></header><div className="home-section-list">{data.sections.map((item) => <article key={item.id} draggable onDragStart={() => setDragged(item.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => dropSection(item.id)} className={dragged === item.id ? "dragging" : ""}><i>⋮⋮</i><span>{item.sortOrder + 1}</span><div><b>{item.nameAr}</b><small>{item.key}</small></div><em className={item.isActive ? "status-live" : "status-off"}>{item.isActive ? "ظاهر" : "مخفي"}</em><button onClick={() => setEditor({ kind: "section", item })}>تعديل</button></article>)}</div></div><aside className="panel content-preview"><header><b>معاينة هيكل التطبيق</b><small>ترتيب حي للأقسام النشطة</small></header><div className="phone-preview"><span className="phone-search">ابحث عن المنتجات...</span>{data.sections.filter((x) => x.isActive).map((item) => <div key={item.id}><b>{item.nameAr}</b><span /><span /><span /></div>)}</div></aside></section>}
    {tab === "banners" && <section className="banner-admin-grid">{data.banners.map((item) => <article className="panel banner-admin-card" key={item.id}><div className="banner-image" style={{ backgroundImage: `linear-gradient(110deg,rgba(17,33,54,.72),rgba(17,33,54,.08)),url(${item.imageUrl})` }}><span className={`state-pill state-${item.state.toLowerCase()}`}>{stateLabels[item.state] || item.state}</span><h3>{item.titleAr}</h3><p>{item.subtitleAr}</p></div><dl><div><dt>الجدولة</dt><dd>{displayDate(item.startsAt)} — {displayDate(item.endsAt)}</dd></div><div><dt>الجمهور</dt><dd>{item.targetTenantName || "كل الشركات"}</dd></div></dl><footer><button onClick={() => setEditor({ kind: "banner", item })}>تعديل</button><button className="danger-link" onClick={() => remove("banners", item.id, item.titleAr)}>حذف</button></footer></article>)}</section>}
    {tab === "pages" && <section className="panel content-table-panel"><div className="content-kpis"><div><b>{data.pages.length}</b><span>إجمالي الصفحات</span></div><div><b>{data.pages.filter((x) => x.isPublished).length}</b><span>منشورة</span></div><div><b>{policies.length}</b><span>سياسات رسمية</span></div></div><table className="content-table"><thead><tr><th>الصفحة</th><th>الرابط</th><th>النوع</th><th>الحالة</th><th>آخر تحديث</th><th /></tr></thead><tbody>{data.pages.map((item) => <tr key={item.id}><td><b>{item.titleAr}</b><small>{item.bodyAr.slice(0, 85)}...</small></td><td dir="ltr">/{item.slug}</td><td>{policies.some((x) => x.id === item.id) ? "سياسة" : "صفحة محتوى"}</td><td><em className={item.isPublished ? "status-live" : "status-off"}>{item.isPublished ? "منشورة" : "مسودة"}</em></td><td>{displayDate(item.updatedAt)}</td><td><button onClick={() => setEditor({ kind: "page", item })}>تعديل</button><button className="danger-link" onClick={() => remove("pages", item.id, item.titleAr)}>حذف</button></td></tr>)}</tbody></table></section>}
    {tab === "faq" && <section className="panel faq-admin-list">{data.faq.map((item) => <article key={item.id}><span>{item.sortOrder}</span><div><small>{item.category} · {item.isPublished ? "منشور" : "مسودة"}</small><b>{item.questionAr}</b><p>{item.answerAr}</p></div><button onClick={() => setEditor({ kind: "faq", item })}>تعديل</button><button className="danger-link" onClick={() => remove("faq", item.id, item.questionAr)}>حذف</button></article>)}</section>}
    {tab === "messages" && <section className="panel content-table-panel"><div className="content-kpis"><div><b>{data.dispatches.length}</b><span>إجمالي الحملات</span></div><div><b>{data.dispatches.filter((x) => x.status === "Sent").length}</b><span>تم إرسالها</span></div><div><b>{data.dispatches.reduce((sum, x) => sum + x.recipientCount, 0)}</b><span>إجمالي المستلمين</span></div></div><table className="content-table"><thead><tr><th>الحملة</th><th>القناة</th><th>الجمهور</th><th>الموعد</th><th>الحالة</th><th>المستلمون</th><th /></tr></thead><tbody>{data.dispatches.map((item) => <tr key={item.id}><td><b>{item.titleAr}</b><small>{item.bodyAr.slice(0, 75)}</small></td><td>{item.channel === "InAppMessage" ? "داخل التطبيق" : "إشعار Push"}</td><td>{item.targetTenantName || "كل الشركات"}</td><td>{displayDate(item.scheduledAt || item.sentAt || item.createdAt)}</td><td><em className={item.status === "Sent" ? "status-live" : "status-wait"}>{stateLabels[item.status] || item.status}</em></td><td>{item.recipientCount}</td><td>{item.status !== "Sent" && <button onClick={() => send(item.id)}>إرسال الآن</button>}</td></tr>)}</tbody></table></section>}
    {editor && <EditorModal editor={editor} tenants={data.tenants} saving={saving} onClose={() => setEditor(null)} onSubmit={save} />}
  </>;
}

function EditorModal({ editor, tenants, saving, onClose, onSubmit }: { editor: Editor; tenants: Tenant[]; saving: boolean; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const title = editor.kind === "section" ? (editor.item ? "تعديل قسم الصفحة" : "إضافة قسم للصفحة") : editor.kind === "banner" ? (editor.item ? "تعديل البنر" : "إضافة بنر") : editor.kind === "page" ? (editor.item ? "تعديل الصفحة" : "إضافة صفحة") : editor.kind === "faq" ? (editor.item ? "تعديل السؤال" : "إضافة سؤال") : editor.channel === "InAppMessage" ? "رسالة داخل التطبيق" : "إشعار تطبيق جديد";
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="mini-editor content-editor"><header><h2>{title}</h2><button onClick={onClose}>×</button></header><form onSubmit={onSubmit}>
    {editor.kind === "section" && <><label>المفتاح البرمجي<input name="key" dir="ltr" defaultValue={editor.item?.key || ""} required /></label><label>الاسم الظاهر<input name="nameAr" defaultValue={editor.item?.nameAr || ""} required /></label><label>الترتيب<input name="sortOrder" type="number" min="0" defaultValue={editor.item?.sortOrder || 0} /></label><label>إعدادات JSON<textarea name="settingsJson" dir="ltr" defaultValue={editor.item?.settingsJson || ""} /></label><label className="check-label"><input name="isActive" type="checkbox" defaultChecked={editor.item?.isActive !== false} /> إظهار القسم</label></>}
    {editor.kind === "banner" && <><label>العنوان<input name="titleAr" defaultValue={editor.item?.titleAr || ""} required /></label><label>العنوان الفرعي<input name="subtitleAr" defaultValue={editor.item?.subtitleAr || ""} /></label><label>رابط الصورة<input name="imageUrl" dir="ltr" defaultValue={editor.item?.imageUrl || ""} required /></label><label>رابط الإجراء<input name="actionUrl" dir="ltr" defaultValue={editor.item?.actionUrl || ""} /></label><div className="editor-columns"><label>بداية الظهور<input name="startsAt" type="datetime-local" defaultValue={inputDate(editor.item?.startsAt) || inputDate(new Date().toISOString())} required /></label><label>نهاية الظهور<input name="endsAt" type="datetime-local" defaultValue={inputDate(editor.item?.endsAt)} /></label></div><label>استهداف شركة<select name="targetTenantId" defaultValue={editor.item?.targetTenantId || ""}><option value="">كل الشركات</option>{tenants.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>الترتيب<input name="sortOrder" type="number" min="0" defaultValue={editor.item?.sortOrder || 0} /></label><label className="check-label"><input name="isActive" type="checkbox" defaultChecked={editor.item?.isActive !== false} /> بنر نشط</label></>}
    {editor.kind === "page" && <><label>العنوان<input name="titleAr" defaultValue={editor.item?.titleAr || ""} required /></label><label>الرابط المختصر<input name="slug" dir="ltr" defaultValue={editor.item?.slug || ""} required /></label><label>المحتوى<textarea className="large-textarea" name="bodyAr" defaultValue={editor.item?.bodyAr || ""} required /></label><div className="editor-columns"><label>الهاتف<input name="contactPhone" dir="ltr" defaultValue={editor.item?.contactPhone || ""} /></label><label>واتساب<input name="whatsAppPhone" dir="ltr" defaultValue={editor.item?.whatsAppPhone || ""} /></label></div><label>البريد الإلكتروني<input name="contactEmail" type="email" dir="ltr" defaultValue={editor.item?.contactEmail || ""} /></label><label>العنوان<input name="address" defaultValue={editor.item?.address || ""} /></label><label className="check-label"><input name="isPublished" type="checkbox" defaultChecked={editor.item?.isPublished !== false} /> نشر الصفحة</label></>}
    {editor.kind === "faq" && <><label>السؤال<input name="questionAr" defaultValue={editor.item?.questionAr || ""} required /></label><label>الإجابة<textarea className="large-textarea" name="answerAr" defaultValue={editor.item?.answerAr || ""} required /></label><div className="editor-columns"><label>التصنيف<input name="category" dir="ltr" defaultValue={editor.item?.category || "general"} required /></label><label>الرابط<input name="slug" dir="ltr" defaultValue={editor.item?.slug || ""} required /></label></div><label>الترتيب<input name="sortOrder" type="number" min="0" defaultValue={editor.item?.sortOrder || 0} /></label><label className="check-label"><input name="isPublished" type="checkbox" defaultChecked={editor.item?.isPublished !== false} /> نشر السؤال</label></>}
    {editor.kind === "dispatch" && <><label>العنوان<input name="titleAr" required /></label><label>نص الرسالة<textarea className="large-textarea" name="bodyAr" required /></label><label>رابط الإجراء<input name="actionUrl" dir="ltr" /></label><label>الجمهور<select name="targetTenantId"><option value="">كل الشركات</option>{tenants.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>موعد الإرسال<input name="scheduledAt" type="datetime-local" /></label><label className="check-label"><input name="sendNow" type="checkbox" /> إرسال فوري بعد الحفظ</label></>}
    <footer><button type="button" className="secondary-button" onClick={onClose}>إلغاء</button><button className="primary-button" disabled={saving}>{saving ? "جاري الحفظ..." : editor.kind === "dispatch" ? "حفظ الحملة" : "حفظ"}</button></footer>
  </form></section></div>;
}
