using Microsoft.EntityFrameworkCore;
using Mohandseto.Api.Application.Common;
using Mohandseto.Api.Domain.Entities;
using Mohandseto.Api.Infrastructure;

namespace Mohandseto.Api.Application.AdminCustomerService;

public sealed class AdminCustomerServiceService(AppDbContext db, IWebHostEnvironment env)
{
    public async Task<CustomerServiceDashboardDto> DashboardAsync(CancellationToken ct = default)
    {
        var returns = await db.ReturnRequests.AsNoTracking().AsSplitQuery().Include(x => x.Order).Include(x => x.Items).ThenInclude(x => x.OrderItem).Include(x => x.Attachments).Include(x => x.History).OrderByDescending(x => x.CreatedAt).Take(300).ToListAsync(ct);
        var tickets = await db.SupportTickets.AsNoTracking().Include(x => x.Messages).OrderByDescending(x => x.UpdatedAt ?? x.CreatedAt).Take(300).ToListAsync(ct);
        var userIds = returns.Select(x => x.UserId).Concat(tickets.Select(x => x.UserId)).Concat(tickets.Where(x => x.AssignedStaffUserId.HasValue).Select(x => x.AssignedStaffUserId!.Value)).Concat(tickets.SelectMany(x => x.Messages).Select(x => x.SenderUserId)).Distinct().ToList();
        var users = await db.Users.IgnoreQueryFilters().AsNoTracking().Where(x => userIds.Contains(x.Id) && !x.IsDeleted).ToDictionaryAsync(x => x.Id, x => x.FullName, ct);
        var tenantIds = returns.Select(x => x.TenantId).Concat(tickets.Select(x => x.TenantId)).Distinct().ToList();
        var companies = await db.Companies.IgnoreQueryFilters().AsNoTracking().Where(x => tenantIds.Contains(x.TenantId) && !x.IsDeleted).ToDictionaryAsync(x => x.TenantId, x => x.LegalName, ct);
        var policies = await db.SupportSlaPolicies.AsNoTracking().OrderBy(x => x.Type).ThenBy(x => x.Priority).ToListAsync(ct);
        var templates = await db.SupportReplyTemplates.AsNoTracking().OrderByDescending(x => x.UsageCount).ToListAsync(ct);
        var staffUsers = await db.Users.IgnoreQueryFilters().AsNoTracking().Where(x => x.IsPlatformStaff && x.IsActive && !x.IsDeleted).ToListAsync(ct);
        var now = DateTime.UtcNow;
        bool Breached(SupportTicket x) => x.Status is not (SupportTicketStatus.Resolved or SupportTicketStatus.Closed) && ((x.FirstResponseAt is null && x.FirstResponseDueAt < now) || x.ResolutionDueAt < now);
        var mappedTickets = tickets.Select(x => new AdminSupportTicketDto(x.Id, x.Number, companies.GetValueOrDefault(x.TenantId, "شركة عميلة"), users.GetValueOrDefault(x.UserId, "عميل"), x.Type.ToString(), x.Priority.ToString(), x.Status.ToString(), x.Subject, x.Description, x.OrderId, x.AssignedStaffUserId, x.AssignedStaffUserId is { } sid ? users.GetValueOrDefault(sid, "موظف دعم") : null, x.CreatedAt, x.FirstResponseDueAt, x.ResolutionDueAt, x.FirstResponseAt, x.ResolvedAt, x.EscalatedAt, x.EscalationReason, x.Rating, x.RatingComment, Breached(x), x.Messages.OrderBy(m => m.CreatedAt).Select(m => new AdminSupportMessageDto(m.Id, users.GetValueOrDefault(m.SenderUserId, m.IsStaff ? "فريق الدعم" : "العميل"), m.IsStaff, m.Body, m.CreatedAt)).ToList())).ToList();
        var closed = tickets.Where(x => x.ResolvedAt.HasValue).ToList(); var rated = tickets.Where(x => x.Rating.HasValue).ToList(); var reviewedReturns = returns.Where(x => x.Status is ReturnStatus.Approved or ReturnStatus.Rejected or ReturnStatus.Completed).ToList();
        var staff = staffUsers.Select(s => { var mine = tickets.Where(x => x.AssignedStaffUserId == s.Id).ToList(); var completed = mine.Where(x => x.Status is SupportTicketStatus.Resolved or SupportTicketStatus.Closed).ToList(); var compliance = completed.Count == 0 ? 100 : decimal.Round(completed.Count(x => x.ResolvedAt <= x.ResolutionDueAt) * 100m / completed.Count, 1); return new SupportStaffDto(s.Id, s.FullName, mine.Count(x => x.Status is not (SupportTicketStatus.Resolved or SupportTicketStatus.Closed)), completed.Count, mine.Any(x => x.Rating.HasValue) ? decimal.Round((decimal)mine.Where(x => x.Rating.HasValue).Average(x => x.Rating!.Value), 1) : 0, compliance); }).OrderByDescending(x => x.ResolvedTickets).ToList();
        var issues = tickets.GroupBy(x => x.Type).Select(g => new IssueTypeReportDto(g.Key.ToString(), g.Count(), tickets.Count == 0 ? 0 : decimal.Round(g.Count() * 100m / tickets.Count, 1), g.Any(x => x.ResolvedAt.HasValue) ? decimal.Round((decimal)g.Where(x => x.ResolvedAt.HasValue).Average(x => (x.ResolvedAt!.Value - x.CreatedAt).TotalHours), 1) : 0)).OrderByDescending(x => x.Count).ToList();
        var policyDtos = policies.Select(p => { var matching = tickets.Where(x => x.Type == p.Type && x.Priority == p.Priority && x.Status is SupportTicketStatus.Resolved or SupportTicketStatus.Closed).ToList(); var compliance = matching.Count == 0 ? 100 : decimal.Round(matching.Count(x => x.ResolvedAt <= x.ResolutionDueAt) * 100m / matching.Count, 1); return new SupportSlaDto(p.Id, p.Type.ToString(), p.Priority.ToString(), p.FirstResponseMinutes, p.ResolutionMinutes, p.IsActive, compliance); }).ToList();
        var kpis = new ServiceKpisDto(tickets.Count(x => x.Status is not (SupportTicketStatus.Resolved or SupportTicketStatus.Closed)), tickets.Count(Breached), returns.Count(x => SubmittedOrProcessing(x.Status)), rated.Count == 0 ? 0 : decimal.Round((decimal)rated.Average(x => x.Rating!.Value), 1), closed.Count == 0 ? 0 : decimal.Round((decimal)closed.Average(x => (x.ResolvedAt!.Value - x.CreatedAt).TotalHours), 1), reviewedReturns.Count == 0 ? 0 : decimal.Round(reviewedReturns.Count(x => x.Status != ReturnStatus.Rejected) * 100m / reviewedReturns.Count, 1));
        return new(kpis, returns.Select(x => MapReturn(x, companies, users)).ToList(), mappedTickets, policyDtos, templates.Select(x => new SupportTemplateDto(x.Id, x.Title, x.Type?.ToString(), x.Body, x.UsageCount, x.IsActive)).ToList(), staff, issues, await db.Warehouses.AsNoTracking().Where(x => x.IsActive).Select(x => new WarehouseOptionDto(x.Id, x.NameAr)).ToListAsync(ct));
    }

    public async Task AssignAsync(Guid ticketId, AssignSupportStaffDto dto, CancellationToken ct = default)
    {
        var staff = await db.Users.IgnoreQueryFilters().FirstOrDefaultAsync(x => x.Id == dto.StaffUserId && x.IsPlatformStaff && x.IsActive && !x.IsDeleted, ct) ?? throw ApiException.BadRequest("موظف الدعم غير صالح"); var ticket = await Ticket(ticketId, ct); ticket.AssignedStaffUserId = staff.Id; if (ticket.Status == SupportTicketStatus.Open) ticket.Status = SupportTicketStatus.InProgress; await db.SaveChangesAsync(ct);
    }

    public async Task ReplyAsync(Guid actorId, Guid ticketId, ReplySupportTicketDto dto, CancellationToken ct = default)
    {
        var ticket = await Ticket(ticketId, ct); if (ticket.Status == SupportTicketStatus.Closed) throw ApiException.Conflict("التذكرة مغلقة"); var body = Clean(dto.Body, 3000); SupportReplyTemplate? template = null; if (dto.TemplateId is { } id) { template = await db.SupportReplyTemplates.FirstOrDefaultAsync(x => x.Id == id && x.IsActive, ct) ?? throw ApiException.BadRequest("قالب الرد غير موجود"); if (body is null) body = template.Body; template.UsageCount++; } if (body is null) throw ApiException.BadRequest("اكتب الرد");
        db.SupportMessages.Add(new SupportMessage { TenantId = ticket.TenantId, TicketId = ticket.Id, SenderUserId = actorId, IsStaff = true, Body = body }); var now = DateTime.UtcNow; ticket.FirstResponseAt ??= now; ticket.Status = dto.WaitForCustomer ? SupportTicketStatus.WaitingCustomer : SupportTicketStatus.InProgress; ticket.UpdatedAt = now; db.Notifications.Add(new AppNotification { TenantId = ticket.TenantId, UserId = ticket.UserId, Type = "support.reply", Title = "رد جديد من خدمة العملاء", Body = ticket.Subject, EntityType = nameof(SupportTicket), EntityId = ticket.Id }); await db.SaveChangesAsync(ct);
    }

    public async Task EscalateAsync(Guid actorId, Guid ticketId, EscalateSupportTicketDto dto, CancellationToken ct = default) { var ticket = await Ticket(ticketId, ct); ticket.EscalatedAt = DateTime.UtcNow; ticket.EscalatedBy = actorId; ticket.EscalationReason = Clean(dto.Reason, 500) ?? throw ApiException.BadRequest("سبب التصعيد مطلوب"); ticket.Priority = SupportTicketPriority.Urgent; ticket.Status = SupportTicketStatus.InProgress; await db.SaveChangesAsync(ct); }
    public async Task ChangeStatusAsync(Guid ticketId, ChangeSupportStatusDto dto, CancellationToken ct = default) { if (!Enum.TryParse<SupportTicketStatus>(dto.Status, true, out var status)) throw ApiException.BadRequest("حالة التذكرة غير صالحة"); var ticket = await Ticket(ticketId, ct); ticket.Status = status; var now = DateTime.UtcNow; if (status == SupportTicketStatus.Resolved) ticket.ResolvedAt = now; if (status == SupportTicketStatus.Closed) { ticket.ResolvedAt ??= now; ticket.ClosedAt = now; } ticket.UpdatedAt = now; await db.SaveChangesAsync(ct); }

    public async Task<SupportSlaDto> SaveSlaAsync(Guid? id, SaveSlaPolicyDto dto, CancellationToken ct = default)
    {
        if (!Enum.TryParse<SupportTicketType>(dto.Type, true, out var type) || !Enum.TryParse<SupportTicketPriority>(dto.Priority, true, out var priority) || dto.FirstResponseMinutes <= 0 || dto.ResolutionMinutes < dto.FirstResponseMinutes) throw ApiException.BadRequest("سياسة SLA غير صالحة"); var policy = id is { } value ? await db.SupportSlaPolicies.FirstOrDefaultAsync(x => x.Id == value, ct) ?? throw ApiException.NotFound("السياسة غير موجودة") : new SupportSlaPolicy(); if (id is null && await db.SupportSlaPolicies.AnyAsync(x => x.Type == type && x.Priority == priority, ct)) throw ApiException.Conflict("توجد سياسة لنفس النوع والأولوية"); policy.Type = type; policy.Priority = priority; policy.FirstResponseMinutes = dto.FirstResponseMinutes; policy.ResolutionMinutes = dto.ResolutionMinutes; policy.IsActive = dto.IsActive; if (id is null) db.SupportSlaPolicies.Add(policy); await db.SaveChangesAsync(ct); return new(policy.Id, type.ToString(), priority.ToString(), policy.FirstResponseMinutes, policy.ResolutionMinutes, policy.IsActive, 100);
    }

    public async Task<SupportTemplateDto> SaveTemplateAsync(Guid? id, SaveReplyTemplateDto dto, CancellationToken ct = default) { SupportTicketType? type = null; if (!string.IsNullOrWhiteSpace(dto.Type)) { if (!Enum.TryParse<SupportTicketType>(dto.Type, true, out var parsed)) throw ApiException.BadRequest("نوع القالب غير صالح"); type = parsed; } var template = id is { } value ? await db.SupportReplyTemplates.FirstOrDefaultAsync(x => x.Id == value, ct) ?? throw ApiException.NotFound("القالب غير موجود") : new SupportReplyTemplate(); template.Title = Clean(dto.Title, 150) ?? throw ApiException.BadRequest("اسم القالب مطلوب"); template.Body = Clean(dto.Body, 3000) ?? throw ApiException.BadRequest("نص القالب مطلوب"); template.Type = type; template.IsActive = dto.IsActive; if (id is null) db.SupportReplyTemplates.Add(template); await db.SaveChangesAsync(ct); return new(template.Id, template.Title, template.Type?.ToString(), template.Body, template.UsageCount, template.IsActive); }

    public async Task SetDispositionAsync(Guid actorId, Guid returnId, Guid itemId, ReturnDispositionDto dto, CancellationToken ct = default)
    {
        if (!Enum.TryParse<ReturnDisposition>(dto.Disposition, true, out var disposition)) throw ApiException.BadRequest("إجراء المنتج المرتجع غير صالح"); var request = await db.ReturnRequests.Include(x => x.Items).ThenInclude(x => x.OrderItem).FirstOrDefaultAsync(x => x.Id == returnId, ct) ?? throw ApiException.NotFound("المرتجع غير موجود"); if (request.Status is not (ReturnStatus.RefundApproved or ReturnStatus.ReplacementPreparing or ReturnStatus.Inspecting)) throw ApiException.Conflict("يجب إتمام فحص المرتجع أولاً"); var item = request.Items.FirstOrDefault(x => x.Id == itemId) ?? throw ApiException.NotFound("صنف المرتجع غير موجود"); if (item.DispositionAt.HasValue) throw ApiException.Conflict("تم تنفيذ إجراء هذا الصنف بالفعل");
        item.InspectedCondition = Clean(dto.Condition, 500) ?? throw ApiException.BadRequest("حالة المنتج مطلوبة"); item.Disposition = disposition; item.DispositionAt = DateTime.UtcNow; item.DispositionBy = actorId;
        if (disposition == ReturnDisposition.Restock) { if (dto.WarehouseId is not { } warehouseId) throw ApiException.BadRequest("اختر المخزن"); var warehouse = await db.Warehouses.FirstOrDefaultAsync(x => x.Id == warehouseId && x.IsActive, ct) ?? throw ApiException.BadRequest("المخزن غير صالح"); var stock = await db.WarehouseStocks.FirstOrDefaultAsync(x => x.WarehouseId == warehouse.Id && x.ProductId == item.OrderItem.ProductId, ct); if (stock is null) { stock = new WarehouseStock { WarehouseId = warehouse.Id, ProductId = item.OrderItem.ProductId, Barcode = $"RET-{warehouse.Code}-{item.OrderItem.Sku}" }; db.WarehouseStocks.Add(stock); } stock.OnHandQty += item.Quantity; var product = await db.Products.FirstAsync(x => x.Id == item.OrderItem.ProductId, ct); product.StockQty += item.Quantity; db.InventoryMovements.Add(new InventoryMovement { Number = Number("MOV"), WarehouseId = warehouse.Id, ProductId = item.OrderItem.ProductId, Type = InventoryMovementType.Add, Quantity = item.Quantity, BalanceAfter = stock.OnHandQty, UnitCost = item.UnitRefund, ReferenceType = "customer_return", ReferenceId = request.Id, Reason = Clean(dto.Note, 500) ?? "إعادة منتج مرتجع للمخزون", ActorUserId = actorId }); }
        else if (disposition == ReturnDisposition.Dispose) { if (dto.WarehouseId is not { } warehouseId || !await db.Warehouses.AnyAsync(x => x.Id == warehouseId && x.IsActive, ct)) throw ApiException.BadRequest("اختر مخزن فحص صالح"); db.InventoryMovements.Add(new InventoryMovement { Number = Number("MOV"), WarehouseId = warehouseId, ProductId = item.OrderItem.ProductId, Type = InventoryMovementType.RejectDamaged, Quantity = item.Quantity, UnitCost = item.UnitRefund, ReferenceType = "customer_return", ReferenceId = request.Id, Reason = Clean(dto.Note, 500) ?? "إتلاف منتج مرتجع", ActorUserId = actorId }); }
        else if (disposition == ReturnDisposition.CreditNote) { db.AccountingEntries.Add(new AccountingEntry { Number = Number("CRN"), TenantId = request.TenantId, ReturnRequestId = request.Id, Type = AccountingEntryType.CreditNote, Status = AccountingEntryStatus.Posted, Category = "مرتجعات العملاء", Description = $"إشعار دائن للمرتجع {request.Number} - {item.OrderItem.NameAr}", Amount = item.LineRefund, OccurredAt = DateTime.UtcNow, PostedAt = DateTime.UtcNow, PostedBy = actorId }); }
        await db.SaveChangesAsync(ct);
    }

    public async Task<(string Path, string Type, string Name)> ReturnFileAsync(Guid id, CancellationToken ct = default) { var file = await db.ReturnAttachments.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id, ct) ?? throw ApiException.NotFound("الصورة غير موجودة"); return Physical(file.StoredPath, file.ContentType, file.OriginalName); }
    public async Task<(string Path, string Type, string Name)> SupportFileAsync(Guid id, CancellationToken ct = default) { var file = await db.SupportAttachments.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id, ct) ?? throw ApiException.NotFound("المرفق غير موجود"); return Physical(file.StoredPath, file.ContentType, file.OriginalName); }
    private (string Path, string Type, string Name) Physical(string stored, string type, string name) { var root = Path.GetFullPath(env.ContentRootPath); var path = Path.GetFullPath(Path.Combine(root, stored)); if (!path.StartsWith(root, StringComparison.OrdinalIgnoreCase) || !File.Exists(path)) throw ApiException.NotFound("الملف غير موجود"); return (path, type, name); }
    private async Task<SupportTicket> Ticket(Guid id, CancellationToken ct) => await db.SupportTickets.FirstOrDefaultAsync(x => x.Id == id, ct) ?? throw ApiException.NotFound("التذكرة غير موجودة");
    private static AdminReturnDto MapReturn(ReturnRequest x, IReadOnlyDictionary<Guid, string> companies, IReadOnlyDictionary<Guid, string> users) => new(x.Id, x.Number, x.Order.Number, companies.GetValueOrDefault(x.TenantId, "شركة عميلة"), users.GetValueOrDefault(x.UserId, "عميل"), x.Status.ToString(), x.Resolution.ToString(), x.RequestedTotal, x.ApprovedTotal, x.PickupAddress, x.PickupAt, x.RejectionReason, x.InspectionNotes, x.CreatedAt, x.Items.Select(i => new AdminReturnItemDto(i.Id, i.OrderItem.ProductId, i.OrderItem.Sku, i.OrderItem.NameAr, i.Quantity, i.Reason.ToString(), i.Description, i.LineRefund, i.InspectionPassed, i.InspectedCondition, i.Disposition?.ToString())).ToList(), x.Attachments.Select(a => new AdminReturnAttachmentDto(a.Id, a.ReturnItemId, a.OriginalName, a.ContentType, a.SizeBytes, a.CreatedAt)).ToList(), x.History.OrderBy(h => h.CreatedAt).Select(h => new AdminReturnHistoryDto(h.Status.ToString(), h.Note, h.CreatedAt)).ToList());
    private static bool SubmittedOrProcessing(ReturnStatus status) => status is not (ReturnStatus.Draft or ReturnStatus.Rejected or ReturnStatus.Completed or ReturnStatus.Cancelled);
    private static string Number(string prefix) => $"{prefix}-{DateTime.UtcNow:yyMMdd}-{Guid.NewGuid().ToString("N")[..8].ToUpperInvariant()}";
    private static string? Clean(string? value, int max) { if (string.IsNullOrWhiteSpace(value)) return null; var result = value.Trim(); return result.Length <= max ? result : result[..max]; }
}
