"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
type SupplierProduct={productId:string;sku:string;product:string;supplierSku?:string;unitPrice:number;minimumQuantity:number;leadDays:number;validFrom:string;validUntil?:string;isPreferred:boolean};
type Document={id:string;nameAr:string;type:string;path:string;expiresAt?:string};
type Supplier={id:string;code:string;nameAr:string;nameEn?:string;contactName?:string;phone?:string;email?:string;address?:string;commercialRegistrationNo?:string;taxRegistrationNo?:string;typicalLeadDays:number;paymentTermsDays:number;creditLimit:number;rating:number;isActive:boolean;notes?:string;products:SupplierProduct[];documents:Document[];orderCount:number;payables:number};
type OrderItem={productId:string;sku:string;product:string;orderedQty:number;receivedQty:number;unitPrice:number;lineTotal:number};
type Order={id:string;number:string;supplierId:string;supplier:string;warehouseId:string;warehouse:string;status:string;expectedAt:string;sentAt?:string;subtotal:number;tax:number;shipping:number;total:number;notes?:string;createdAt:string;items:OrderItem[]};
type Invoice={id:string;number:string;supplier:string;purchaseOrder:string;supplierInvoiceNumber:string;amount:number;paidAmount:number;outstanding:number;issuedAt:string;dueAt:string;status:string;varianceAmount:number};
type Performance={supplierId:string;supplier:string;rating:number;onTimeRate:number;acceptanceRate:number;orders:number;totalSpend:number;payables:number};
type Product={id:string;sku:string;name:string;cost:number}; type Warehouse={id:string;name:string};
type Dashboard={suppliers:Supplier[];orders:Order[];invoices:Invoice[];performance:Performance[];products:Product[];warehouses:Warehouse[]};
type Tab="suppliers"|"orders"|"invoices"|"compare"|"performance";
type Editor={kind:"supplier";item?:Supplier}|{kind:"product";supplier:Supplier}|{kind:"rate";supplier:Supplier}|{kind:"document";supplier:Supplier}|{kind:"order"}|{kind:"receive";order:Order}|{kind:"invoice";order?:Order}|{kind:"return";order:Order}|{kind:"detail";supplier:Supplier}|{kind:"orderDetail";order:Order};
const money=new Intl.NumberFormat("ar-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0}); const fmt=(v?:string)=>v?new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium"}).format(new Date(v)):"—";
const status:Record<string,string>={Draft:"مسودة",Sent:"تم الإرسال",Confirmed:"مؤكد",PartiallyReceived:"استلام جزئي",Received:"مستلم بالكامل",Cancelled:"ملغي",Matched:"مطابقة سليمة",Variance:"يوجد فرق",Approved:"معتمدة",Paid:"مدفوعة",PartiallyPaid:"دفع جزئي"};
export function SupplierManager(){
 const[data,setData]=useState<Dashboard|null>(null);const[tab,setTab]=useState<Tab>("suppliers");const[editor,setEditor]=useState<Editor|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/admin/procurement");if(!r.ok)throw new Error("تعذر تحميل بيانات الموردين");return r.json() as Promise<Dashboard>},[]);
 useEffect(()=>{let active=true;load().then(x=>{if(active){setData(x);setLoading(false)}}).catch(e=>{if(active){setError(e.message);setLoading(false)}});return()=>{active=false}},[load]);
 async function api(path:string,body?:unknown,method="POST"){const r=await fetch(`/api/admin/procurement/${path}`,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.title||"تعذر تنفيذ العملية")}}
 async function refresh(message:string){setData(await load());setNotice(message);setTimeout(()=>setNotice(""),3500)}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editor||!data)return;setSaving(true);setError("");const f=new FormData(e.currentTarget);try{
  if(editor.kind==="supplier")await api(editor.item?`suppliers/${editor.item.id}`:"suppliers",{code:f.get("code"),nameAr:f.get("nameAr"),nameEn:f.get("nameEn")||null,contactName:f.get("contactName")||null,phone:f.get("phone")||null,email:f.get("email")||null,address:f.get("address")||null,commercialRegistrationNo:f.get("commercialRegistrationNo")||null,taxRegistrationNo:f.get("taxRegistrationNo")||null,typicalLeadDays:Number(f.get("typicalLeadDays")),paymentTermsDays:Number(f.get("paymentTermsDays")),creditLimit:Number(f.get("creditLimit")),isActive:f.get("isActive")==="on",notes:f.get("notes")||null},editor.item?"PUT":"POST");
  if(editor.kind==="product"){const id=String(f.get("productId"));const next={productId:id,supplierSku:f.get("supplierSku")||null,unitPrice:Number(f.get("unitPrice")),minimumQuantity:Number(f.get("minimumQuantity")),leadDays:Number(f.get("leadDays")),validFrom:new Date(String(f.get("validFrom"))).toISOString(),validUntil:f.get("validUntil")?new Date(String(f.get("validUntil"))).toISOString():null,isPreferred:f.get("isPreferred")==="on"};const old=editor.supplier.products.filter(x=>x.productId!==id).map(x=>({productId:x.productId,supplierSku:x.supplierSku||null,unitPrice:x.unitPrice,minimumQuantity:x.minimumQuantity,leadDays:x.leadDays,validFrom:x.validFrom,validUntil:x.validUntil||null,isPreferred:x.isPreferred}));await api(`suppliers/${editor.supplier.id}/products`,{products:[...old,next]},"PUT")}
  if(editor.kind==="rate")await api(`suppliers/${editor.supplier.id}/ratings`,{quality:Number(f.get("quality")),delivery:Number(f.get("delivery")),price:Number(f.get("price")),communication:Number(f.get("communication")),comment:f.get("comment")||null});
  if(editor.kind==="document")await api(`suppliers/${editor.supplier.id}/documents`,{nameAr:f.get("nameAr"),type:f.get("type"),path:f.get("path"),expiresAt:f.get("expiresAt")?new Date(String(f.get("expiresAt"))).toISOString():null});
  if(editor.kind==="order")await api("orders",{supplierId:f.get("supplierId"),warehouseId:f.get("warehouseId"),expectedAt:new Date(String(f.get("expectedAt"))).toISOString(),tax:Number(f.get("tax")),shipping:Number(f.get("shipping")),notes:f.get("notes")||null,items:[{productId:f.get("productId"),quantity:Number(f.get("quantity")),unitPrice:Number(f.get("unitPrice"))}]});
  if(editor.kind==="receive")await api(`orders/${editor.order.id}/receive`,{supplierReference:f.get("supplierReference"),items:editor.order.items.filter(x=>x.receivedQty<x.orderedQty).map(x=>({productId:x.productId,quantity:Number(f.get(`qty-${x.productId}`)),batchNumber:f.get(`batch-${x.productId}`)||null,expiryAt:f.get(`expiry-${x.productId}`)?new Date(String(f.get(`expiry-${x.productId}`))).toISOString():null})).filter(x=>x.quantity>0)});
  if(editor.kind==="invoice")await api("invoices",{purchaseOrderId:f.get("purchaseOrderId"),supplierInvoiceNumber:f.get("supplierInvoiceNumber"),amount:Number(f.get("amount")),issuedAt:new Date(String(f.get("issuedAt"))).toISOString(),dueAt:new Date(String(f.get("dueAt"))).toISOString()});
  if(editor.kind==="return")await api("returns",{purchaseOrderId:editor.order.id,productId:f.get("productId"),quantity:Number(f.get("quantity")),reason:f.get("reason")});
  setEditor(null);await refresh("تم حفظ عملية المشتريات بنجاح")
 }catch(reason){setError(reason instanceof Error?reason.message:"تعذر الحفظ")}finally{setSaving(false)}}
 async function send(o:Order){if(!confirm(`إرسال أمر الشراء ${o.number} للمورد؟`))return;try{await api(`orders/${o.id}/send`);await refresh("تم إرسال أمر الشراء")}catch(e){setError(e instanceof Error?e.message:"تعذر الإرسال")}}
 const comparison=useMemo(()=>{if(!data)return[];return data.products.map(p=>({product:p,offers:data.suppliers.flatMap(s=>s.products.filter(x=>x.productId===p.id).map(x=>({supplier:s.nameAr,...x}))).sort((a,b)=>a.unitPrice-b.unitPrice)})).filter(x=>x.offers.length)},[data]);
 if(loading)return <div className="admin-loading">جاري تحميل الموردين...</div>;if(!data)return <div className="admin-alert">{error}</div>;
 return <><div className="page-heading catalog-heading"><div><p>العمليات</p><h1>الموردون والمشتريات</h1><span>إدارة الموردين والأسعار وأوامر الشراء والاستلام والمطابقة المالية</span></div><div className="content-heading-actions"><button className="secondary-button" onClick={()=>setEditor({kind:"invoice"})}>فاتورة مورد</button><button className="secondary-button" onClick={()=>setEditor({kind:"order"})}>أمر شراء</button><button className="primary-button" onClick={()=>setEditor({kind:"supplier"})}>+ مورد جديد</button></div></div>{error&&<div className="admin-alert">{error}<button onClick={()=>setError("")}>×</button></div>}{notice&&<div className="admin-success">✓ {notice}</div>}
 <div className="catalog-tabs content-tabs">{([["suppliers","الموردون"],["orders","أوامر الشراء"],["invoices","الفواتير والمستحقات"],["compare","مقارنة الأسعار"],["performance","تقرير الأداء"]] as [Tab,string][]).map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==="suppliers"&&<section className="supplier-admin-grid">{data.suppliers.map(s=><article className="panel supplier-card" key={s.id}><header><span>{s.nameAr.slice(0,1)}</span><em className={s.isActive?"status-live":"status-off"}>{s.isActive?"نشط":"معطل"}</em></header><h2>{s.nameAr}</h2><p>{s.code} · {s.contactName||"بدون مسؤول"}</p><div className="supplier-rating">{"★".repeat(Math.round(s.rating))}<small>{s.rating.toFixed(1)}</small></div><dl><div><dt>المنتجات</dt><dd>{s.products.length}</dd></div><div><dt>أوامر الشراء</dt><dd>{s.orderCount}</dd></div><div><dt>المستحق</dt><dd>{money.format(s.payables)}</dd></div></dl><footer><button onClick={()=>setEditor({kind:"detail",supplier:s})}>التفاصيل</button><button onClick={()=>setEditor({kind:"product",supplier:s})}>قائمة سعر</button><button onClick={()=>setEditor({kind:"document",supplier:s})}>مستند</button><button onClick={()=>setEditor({kind:"rate",supplier:s})}>تقييم</button><button onClick={()=>setEditor({kind:"supplier",item:s})}>تعديل</button></footer></article>)}</section>}
 {tab==="orders"&&<section className="panel content-table-panel"><header className="inventory-panel-head"><div><h2>أوامر الشراء</h2><p>المسودات والإرسال والاستلام الجزئي والكامل</p></div><button onClick={()=>setEditor({kind:"order"})}>+ أمر شراء</button></header><table className="content-table procurement-wide"><thead><tr><th>الأمر</th><th>المورد</th><th>المخزن</th><th>القيمة</th><th>الاستلام</th><th>المتوقع</th><th>الحالة</th><th/></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td><b>{o.number}</b><small>{fmt(o.createdAt)}</small></td><td>{o.supplier}</td><td>{o.warehouse}</td><td>{money.format(o.total)}</td><td>{o.items.reduce((a,x)=>a+x.receivedQty,0)} / {o.items.reduce((a,x)=>a+x.orderedQty,0)}</td><td>{fmt(o.expectedAt)}</td><td><em className={o.status==="Received"?"status-live":o.status==="Draft"?"status-off":"status-wait"}>{status[o.status]||o.status}</em></td><td><button onClick={()=>setEditor({kind:"orderDetail",order:o})}>عرض</button>{o.status==="Draft"&&<button onClick={()=>send(o)}>إرسال</button>}{["Sent","Confirmed","PartiallyReceived"].includes(o.status)&&<button onClick={()=>setEditor({kind:"receive",order:o})}>استلام</button>}{o.status==="Received"&&<button onClick={()=>setEditor({kind:"return",order:o})}>مرتجع</button>}</td></tr>)}</tbody></table></section>}
 {tab==="invoices"&&<section className="panel content-table-panel"><div className="content-kpis"><div><b>{money.format(data.invoices.reduce((a,x)=>a+x.outstanding,0))}</b><span>إجمالي المستحقات</span></div><div><b>{data.invoices.filter(x=>x.status==="Matched").length}</b><span>مطابقة سليمة</span></div><div><b>{data.invoices.filter(x=>x.status==="Variance").length}</b><span>تحتاج مراجعة</span></div></div><table className="content-table"><thead><tr><th>الفاتورة</th><th>المورد</th><th>أمر الشراء</th><th>القيمة</th><th>المستحق</th><th>تاريخ الاستحقاق</th><th>المطابقة</th></tr></thead><tbody>{data.invoices.map(x=><tr key={x.id}><td><b>{x.supplierInvoiceNumber}</b><small>{x.number}</small></td><td>{x.supplier}</td><td>{x.purchaseOrder}</td><td>{money.format(x.amount)}</td><td>{money.format(x.outstanding)}</td><td>{fmt(x.dueAt)}</td><td><em className={x.status==="Matched"?"status-live":"status-wait"}>{status[x.status]||x.status}{x.varianceAmount!==0&&` · فرق ${money.format(x.varianceAmount)}`}</em></td></tr>)}</tbody></table></section>}
 {tab==="compare"&&<section className="panel content-table-panel"><table className="content-table"><thead><tr><th>المنتج</th><th>عدد الموردين</th><th>أفضل مورد</th><th>أفضل سعر</th><th>باقي العروض</th></tr></thead><tbody>{comparison.map(x=><tr key={x.product.id}><td><b>{x.product.name}</b><small>{x.product.sku}</small></td><td>{x.offers.length}</td><td><b>{x.offers[0].supplier}</b></td><td><em className="best-procurement-price">{money.format(x.offers[0].unitPrice)}</em></td><td>{x.offers.slice(1).map(o=><small key={o.supplier}>{o.supplier}: {money.format(o.unitPrice)} </small>)}</td></tr>)}</tbody></table></section>}
 {tab==="performance"&&<section className="performance-grid">{data.performance.map(x=><article className="panel performance-card" key={x.supplierId}><header><div><b>{x.supplier}</b><span>★ {x.rating.toFixed(1)}</span></div><strong>{money.format(x.totalSpend)}</strong></header><div><Metric label="الالتزام بالموعد" value={x.onTimeRate}/><Metric label="نسبة القبول" value={x.acceptanceRate}/></div><footer><span>{x.orders} أوامر شراء</span><span>مستحق {money.format(x.payables)}</span></footer></article>)}</section>}
 {editor&&<ProcurementEditor editor={editor} data={data} saving={saving} onClose={()=>setEditor(null)} onSubmit={save} onSend={send}/>}</>;
}
function Metric({label,value}:{label:string;value:number}){return <label><span>{label}</span><b>{value}%</b><i><em style={{width:`${Math.min(100,value)}%`}}/></i></label>}
function ProcurementEditor({editor,data,saving,onClose,onSubmit,onSend}:{editor:Editor;data:Dashboard;saving:boolean;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onSend:(o:Order)=>void}){const[baseDate]=useState(()=>Date.now());const title=({supplier:"بيانات المورد",product:"منتج وقائمة سعر",rate:"تقييم المورد",document:"مستند أو عقد",order:"إنشاء أمر شراء",receive:"تسجيل استلام",invoice:"فاتورة مورد ومطابقة ثلاثية",return:"مرتجع مورد",detail:"تفاصيل المورد",orderDetail:"مستند أمر الشراء"} as const)[editor.kind];const local=(days=0)=>new Date(baseDate+days*864e5).toISOString().slice(0,10);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className={`mini-editor content-editor procurement-editor ${editor.kind==="detail"||editor.kind==="orderDetail"?"wide":""}`}><header><h2>{title}</h2><button onClick={onClose}>×</button></header>
 {editor.kind==="detail"?<SupplierDetail supplier={editor.supplier}/>:editor.kind==="orderDetail"?<OrderDocument order={editor.order} onSend={()=>onSend(editor.order)}/>:<form onSubmit={onSubmit}>
 {editor.kind==="supplier"&&<><div className="editor-columns"><label>كود المورد<input name="code" dir="ltr" defaultValue={editor.item?.code||""} required/></label><label>الحالة<select name="active-display" disabled><option>{editor.item?.isActive===false?"معطل":"نشط"}</option></select></label></div><label>الاسم بالعربية<input name="nameAr" defaultValue={editor.item?.nameAr||""} required/></label><label>الاسم بالإنجليزية<input name="nameEn" dir="ltr" defaultValue={editor.item?.nameEn||""}/></label><div className="editor-columns"><label>مسؤول التواصل<input name="contactName" defaultValue={editor.item?.contactName||""}/></label><label>الهاتف<input name="phone" dir="ltr" defaultValue={editor.item?.phone||""}/></label></div><label>البريد<input name="email" type="email" dir="ltr" defaultValue={editor.item?.email||""}/></label><label>العنوان<input name="address" defaultValue={editor.item?.address||""}/></label><div className="editor-columns"><label>السجل التجاري<input name="commercialRegistrationNo" dir="ltr" defaultValue={editor.item?.commercialRegistrationNo||""}/></label><label>الرقم الضريبي<input name="taxRegistrationNo" dir="ltr" defaultValue={editor.item?.taxRegistrationNo||""}/></label></div><div className="editor-columns"><label>مدة التوريد بالأيام<input name="typicalLeadDays" type="number" min="0" defaultValue={editor.item?.typicalLeadDays||3}/></label><label>آجل الدفع بالأيام<input name="paymentTermsDays" type="number" min="0" defaultValue={editor.item?.paymentTermsDays||30}/></label></div><label>حد الائتمان<input name="creditLimit" type="number" min="0" defaultValue={editor.item?.creditLimit||0}/></label><label>ملاحظات<textarea name="notes" defaultValue={editor.item?.notes||""}/></label><label className="check-label"><input name="isActive" type="checkbox" defaultChecked={editor.item?.isActive!==false}/> مورد نشط</label></>}
 {editor.kind==="product"&&<><div className="selected-stock"><b>{editor.supplier.nameAr}</b><span>{editor.supplier.products.length} منتج مسجل</span></div><label>المنتج<select name="productId" required><option value="">اختر</option>{data.products.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name}</option>)}</select></label><div className="editor-columns"><label>كود المورد<input name="supplierSku" dir="ltr"/></label><label>سعر الوحدة<input name="unitPrice" type="number" min=".01" step=".01" required/></label></div><div className="editor-columns"><label>أقل كمية<input name="minimumQuantity" type="number" min="1" defaultValue="1"/></label><label>مدة التوريد<input name="leadDays" type="number" min="0" defaultValue={editor.supplier.typicalLeadDays}/></label></div><div className="editor-columns"><label>صالح من<input name="validFrom" type="date" defaultValue={local()} required/></label><label>صالح حتى<input name="validUntil" type="date" defaultValue={local(90)}/></label></div><label className="check-label"><input name="isPreferred" type="checkbox"/> مورد مفضل لهذا المنتج</label></>}
 {editor.kind==="rate"&&<>{["quality","delivery","price","communication"].map((x,i)=><label key={x}>{["الجودة","الالتزام بالتسليم","الأسعار","التواصل"][i]}<input name={x} type="range" min="1" max="5" defaultValue="5"/></label>)}<label>تعليق<textarea name="comment"/></label></>}
 {editor.kind==="document"&&<><label>اسم المستند<input name="nameAr" required/></label><label>النوع<select name="type"><option value="Contract">عقد</option><option value="CommercialRecord">سجل تجاري</option><option value="TaxCard">بطاقة ضريبية</option><option value="Other">أخرى</option></select></label><label>مسار الملف<input name="path" dir="ltr" placeholder="/uploads/supplier/document.pdf" required/></label><label>تاريخ الانتهاء<input name="expiresAt" type="date"/></label></>}
 {editor.kind==="order"&&<><div className="editor-columns"><label>المورد<select name="supplierId" required><option value="">اختر</option>{data.suppliers.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.nameAr}</option>)}</select></label><label>مخزن الاستلام<select name="warehouseId" required><option value="">اختر</option>{data.warehouses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><label>المنتج<select name="productId" required><option value="">اختر</option>{data.products.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name}</option>)}</select></label><div className="editor-columns"><label>الكمية<input name="quantity" type="number" min="1" required/></label><label>سعر الوحدة<input name="unitPrice" type="number" min=".01" step=".01" required/></label></div><div className="editor-columns"><label>الضريبة<input name="tax" type="number" min="0" defaultValue="0"/></label><label>الشحن<input name="shipping" type="number" min="0" defaultValue="0"/></label></div><label>التسليم المتوقع<input name="expectedAt" type="date" defaultValue={local(7)} required/></label><label>ملاحظات<textarea name="notes"/></label></>}
 {editor.kind==="receive"&&<><div className="selected-stock"><b>{editor.order.number} · {editor.order.supplier}</b><span>إلى {editor.order.warehouse}</span></div><label>مرجع إذن المورد<input name="supplierReference" dir="ltr" required/></label><div className="receipt-order-lines">{editor.order.items.filter(x=>x.receivedQty<x.orderedQty).map(x=><article key={x.productId}><div><b>{x.product}</b><small>متبقي {x.orderedQty-x.receivedQty}</small></div><input name={`qty-${x.productId}`} type="number" min="0" max={x.orderedQty-x.receivedQty} defaultValue={x.orderedQty-x.receivedQty}/><input name={`batch-${x.productId}`} placeholder="Batch" dir="ltr"/><input name={`expiry-${x.productId}`} type="date"/></article>)}</div></>}
 {editor.kind==="invoice"&&<><label>أمر الشراء<select name="purchaseOrderId" defaultValue={editor.order?.id||""} required><option value="">اختر</option>{data.orders.filter(x=>x.status==="Received").map(x=><option key={x.id} value={x.id}>{x.number} · {x.supplier} · {money.format(x.total)}</option>)}</select></label><label>رقم فاتورة المورد<input name="supplierInvoiceNumber" dir="ltr" required/></label><label>قيمة الفاتورة<input name="amount" type="number" min="0" step=".01" defaultValue={editor.order?.total} required/></label><div className="editor-columns"><label>تاريخ الإصدار<input name="issuedAt" type="date" defaultValue={local()} required/></label><label>الاستحقاق<input name="dueAt" type="date" defaultValue={local(30)} required/></label></div></>}
 {editor.kind==="return"&&<><div className="selected-stock"><b>{editor.order.number}</b><span>{editor.order.supplier}</span></div><label>الصنف<select name="productId" required>{editor.order.items.filter(x=>x.receivedQty>0).map(x=><option key={x.productId} value={x.productId}>{x.product} · مستلم {x.receivedQty}</option>)}</select></label><label>الكمية<input name="quantity" type="number" min="1" required/></label><label>سبب المرتجع<textarea name="reason" required/></label></>}
 <footer><button type="button" className="secondary-button" onClick={onClose}>إلغاء</button><button className="primary-button" disabled={saving}>{saving?"جاري الحفظ...":"تأكيد"}</button></footer></form>}
 </section></div>}
function SupplierDetail({supplier}:{supplier:Supplier}){return <div className="supplier-detail"><section><h3>بيانات التواصل والتعاقد</h3><dl><div><dt>المسؤول</dt><dd>{supplier.contactName||"—"}</dd></div><div><dt>الهاتف</dt><dd>{supplier.phone||"—"}</dd></div><div><dt>البريد</dt><dd>{supplier.email||"—"}</dd></div><div><dt>السجل / الضريبة</dt><dd>{supplier.commercialRegistrationNo||"—"} / {supplier.taxRegistrationNo||"—"}</dd></div><div><dt>شروط الدفع</dt><dd>{supplier.paymentTermsDays} يوم</dd></div><div><dt>العنوان</dt><dd>{supplier.address||"—"}</dd></div></dl></section><section><h3>المنتجات وقوائم الأسعار</h3>{supplier.products.map(x=><article key={x.productId}><div><b>{x.product}</b><small>{x.sku} · {x.supplierSku}</small></div><strong>{money.format(x.unitPrice)}</strong><span>{x.leadDays} أيام · حد أدنى {x.minimumQuantity}</span></article>)}</section><section><h3>المستندات والعقود</h3>{supplier.documents.map(x=><article key={x.id}><div><b>{x.nameAr}</b><small>{x.type}</small></div><a href={x.path} target="_blank">فتح</a><span>{fmt(x.expiresAt)}</span></article>)}</section></div>}
function OrderDocument({order,onSend}:{order:Order;onSend:()=>void}){return <div className="po-document"><header><div><b>مهندسيتو توريدات</b><span>Purchase Order</span></div><div><strong>{order.number}</strong><small>{fmt(order.createdAt)}</small></div></header><section><div><span>المورد</span><b>{order.supplier}</b></div><div><span>مخزن التسليم</span><b>{order.warehouse}</b></div><div><span>التاريخ المتوقع</span><b>{fmt(order.expectedAt)}</b></div></section><table><thead><tr><th>الصنف</th><th>الكمية</th><th>سعر الوحدة</th><th>الإجمالي</th></tr></thead><tbody>{order.items.map(x=><tr key={x.productId}><td>{x.product}<small>{x.sku}</small></td><td>{x.orderedQty}</td><td>{money.format(x.unitPrice)}</td><td>{money.format(x.lineTotal)}</td></tr>)}</tbody></table><dl><div><dt>قبل الضريبة</dt><dd>{money.format(order.subtotal)}</dd></div><div><dt>الضريبة</dt><dd>{money.format(order.tax)}</dd></div><div><dt>الشحن</dt><dd>{money.format(order.shipping)}</dd></div><div><dt>الإجمالي</dt><dd>{money.format(order.total)}</dd></div></dl><footer><button onClick={()=>window.print()}>طباعة / PDF</button>{order.status==="Draft"&&<button onClick={onSend}>إرسال للمورد</button>}</footer></div>}
