"use client";

import {type FormEvent,useEffect,useMemo,useState} from "react";
import base from "../operations.module.css";
import styles from "./settings.module.css";
import type {ApiKey,BankAccount,DeliveryZone,SettingSection,SettingsDashboard,Translation,Webhook} from "./settings-types";

type Resource="delivery-zones"|"bank-accounts"|"api-keys"|"webhooks"|"integrations-log"|"translations";
type NavItem={code:string;label:string;icon:string;category:string};
const nav:NavItem[]=[
 {code:"general",label:"الإعدادات العامة",icon:"⚙",category:"عام"},{code:"owner-company",label:"بيانات الشركة المالكة",icon:"▦",category:"عام"},
 {code:"tax",label:"إعدادات الضرائب",icon:"%",category:"الضرائب والعملة"},{code:"currency",label:"إعدادات العملة",icon:"ج.م",category:"الضرائب والعملة"},
 {code:"shipping",label:"إعدادات الشحن",icon:"⌖",category:"الشحن والتوصيل"},{code:"delivery-zones",label:"مناطق التوصيل",icon:"◎",category:"الشحن والتوصيل"},{code:"delivery-cost",label:"تكلفة التوصيل",icon:"₤",category:"الشحن والتوصيل"},
 {code:"payment-methods",label:"طرق الدفع",icon:"▣",category:"الدفع والبنوك"},{code:"bank-accounts",label:"الحسابات البنكية",icon:"▤",category:"الدفع والبنوك"},
 {code:"invoice",label:"إعدادات الفواتير",icon:"▤",category:"الفواتير والترقيم"},{code:"numbering",label:"الترقيم",icon:"#",category:"الفواتير والترقيم"},
 {code:"inventory",label:"إعدادات المخزون",icon:"▥",category:"المنتجات والمخزون"},{code:"products",label:"إعدادات المنتجات",icon:"◇",category:"المنتجات والمخزون"},
 {code:"printing",label:"إعدادات الطباعة",icon:"✎",category:"الطباعة والعروض"},{code:"quotes",label:"إعدادات عروض الأسعار",icon:"◫",category:"الطباعة والعروض"},
 {code:"approvals",label:"إعدادات الموافقات",icon:"✓",category:"الحوكمة"},{code:"contracts",label:"إعدادات العقود",icon:"▱",category:"الحوكمة"},
 {code:"notifications",label:"إعدادات الإشعارات",icon:"♢",category:"الإشعارات"},{code:"email",label:"إعدادات البريد",icon:"@",category:"الإشعارات"},{code:"whatsapp",label:"إعدادات WhatsApp",icon:"◉",category:"الإشعارات"},{code:"sms",label:"إعدادات SMS",icon:"SMS",category:"الإشعارات"},
 {code:"payment-gateway",label:"بوابة الدفع",icon:"▣",category:"التكاملات"},{code:"maps",label:"إعدادات الخرائط",icon:"⌖",category:"التكاملات"},
 {code:"backup",label:"النسخ الاحتياطي",icon:"▰",category:"النظام والأمان"},{code:"security",label:"إعدادات الأمان",icon:"♢",category:"النظام والأمان"},{code:"password-policy",label:"سياسة كلمة المرور",icon:"●",category:"النظام والأمان"},{code:"two-factor",label:"المصادقة الثنائية",icon:"2FA",category:"النظام والأمان"},{code:"api-keys",label:"مفاتيح API",icon:"⌘",category:"النظام والأمان"},{code:"webhooks",label:"Webhooks",icon:"↗",category:"النظام والأمان"},{code:"integrations-log",label:"سجل التكاملات",icon:"≡",category:"النظام والأمان"},
 {code:"language",label:"إعدادات اللغة",icon:"ع",category:"اللغة والتطبيق"},{code:"translations",label:"إدارة الترجمات",icon:"文",category:"اللغة والتطبيق"},{code:"maintenance",label:"وضع الصيانة",icon:"⚒",category:"اللغة والتطبيق"},{code:"app-version",label:"إصدار التطبيق المطلوب",icon:"v",category:"اللغة والتطبيق"},{code:"app-links",label:"روابط التطبيق",icon:"↗",category:"اللغة والتطبيق"}
];
const resourceCodes=new Set<Resource>(["delivery-zones","bank-accounts","api-keys","webhooks","integrations-log","translations"]);
async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,cache:"no-store"});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.title||body.message||"تعذر تنفيذ العملية")}return response.status===204?undefined as T:response.json()}
const send=(method:string,body?:unknown):RequestInit=>({method,headers:body===undefined?undefined:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});

export function SettingsManager(){
 const[data,setData]=useState<SettingsDashboard|null>(null),[active,setActive]=useState("general"),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>setData(await api<SettingsDashboard>("/api/admin/system-settings"));
 useEffect(()=>{let live=true;api<SettingsDashboard>("/api/admin/system-settings").then(x=>live&&setData(x)).catch(e=>live&&setError((e as Error).message));return()=>{live=false}},[]);
 const filtered=useMemo(()=>nav.filter(x=>!search||x.label.toLowerCase().includes(search.toLowerCase())),[search]);
 const selected=data?.sections.find(x=>x.code===active);
 async function action(run:()=>Promise<unknown>,message="تم حفظ الإعدادات بنجاح"){setBusy(true);setError("");try{await run();await load();setNotice(message);setTimeout(()=>setNotice(""),2500)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!data)return <p className={base.empty}>{error||"جاري تحميل إعدادات النظام..."}</p>;
 return <section className={styles.page}>
  <header className={styles.hero}><div><span>إدارة النظام</span><h1>إعدادات المنصة</h1><p>تحكم مركزي وآمن في التشغيل والدفع والأمان والتطبيق.</p></div><div className={styles.health}><i/> النظام يعمل بصورة طبيعية</div></header>
  <div className={styles.shell}>
   <aside className={styles.sidebar}><label className={styles.search}>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث في الإعدادات..."/></label><nav>{[...new Set(filtered.map(x=>x.category))].map(category=><section key={category}><b>{category}</b>{filtered.filter(x=>x.category===category).map(x=><button key={x.code} className={active===x.code?styles.active:""} onClick={()=>setActive(x.code)}><i>{x.icon}</i><span>{x.label}</span><em>‹</em></button>)}</section>)}</nav></aside>
   <main className={styles.content}>
    {selected&&<GenericSection key={selected.code} section={selected} busy={busy} save={values=>action(()=>api(`/api/admin/system-settings/sections/${selected.code}`,send("PUT",{values})))}/>} 
    {resourceCodes.has(active as Resource)&&<ResourceView code={active as Resource} data={data} busy={busy} action={action}/>} 
    {active==="backup"&&<BackupHistory data={data} busy={busy} run={()=>action(()=>api("/api/admin/system-settings/backups",send("POST")),"اكتمل إنشاء النسخة الاحتياطية")}/>} 
   </main>
  </div>
  {error&&<div className={base.alert} onClick={()=>setError("")}>{error}</div>}{notice&&<div className={styles.notice}>✓ {notice}</div>}
 </section>
}

function GenericSection({section,busy,save}:{section:SettingSection;busy:boolean;save:(x:Record<string,string>)=>void}){
 const[values,setValues]=useState({...section.values});const set=(key:string,value:string)=>setValues(x=>({...x,[key]:value}));
 return <section className={styles.panel}><header><div className={styles.titleIcon}>{section.icon}</div><div><small>{section.nameEn}</small><h2>{section.nameAr}</h2><p>{section.descriptionAr}</p></div></header><form onSubmit={e=>{e.preventDefault();save(values)}}><div className={styles.formGrid}>{section.fields.map(field=><label key={field.code} className={field.type==="textarea"?styles.wide:""}><span>{field.labelAr}{field.required&&<em> *</em>}</span>{field.type==="boolean"?<button type="button" role="switch" aria-checked={values[field.code]==="true"} className={`${styles.switch} ${values[field.code]==="true"?styles.on:""}`} onClick={()=>set(field.code,values[field.code]==="true"?"false":"true")}><i/><b>{values[field.code]==="true"?"مفعّل":"غير مفعّل"}</b></button>:field.type==="select"?<select value={values[field.code]||""} onChange={e=>set(field.code,e.target.value)} required={field.required}>{field.options.map(x=><option key={x}>{x}</option>)}</select>:field.type==="textarea"?<textarea rows={4} value={values[field.code]||""} onChange={e=>set(field.code,e.target.value)} required={field.required}/>:<input dir={["email","url","password","version","time","number"].includes(field.type)?"ltr":undefined} type={field.type==="password"?"password":field.type==="url"?"url":field.type==="email"?"email":field.type==="number"?"number":field.type==="time"?"time":"text"} step={field.type==="number"?"any":undefined} value={values[field.code]||""} onChange={e=>set(field.code,e.target.value)} required={field.required}/>} {field.help&&<small>{field.help}</small>}</label>)}</div><footer><span>آخر التعديلات تُسجل تلقائيًا في سجل المراجعة.</span><button className={base.primary} disabled={busy}>{busy?"جاري الحفظ...":"حفظ التغييرات"}</button></footer></form></section>
}

function ResourceView({code,data,busy,action}:{code:Resource;data:SettingsDashboard;busy:boolean;action:(x:()=>Promise<unknown>,m?:string)=>void}){
 if(code==="delivery-zones")return <Zones data={data} busy={busy} action={action}/>;
 if(code==="bank-accounts")return <Banks data={data} busy={busy} action={action}/>;
 if(code==="api-keys")return <Keys data={data} busy={busy} action={action}/>;
 if(code==="webhooks")return <Hooks data={data} busy={busy} action={action}/>;
 if(code==="translations")return <Translations data={data} busy={busy} action={action}/>;
 return <Logs data={data}/>;
}
function ResourcePanel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className={styles.panel}><header><div className={styles.titleIcon}>▦</div><div><h2>{title}</h2><p>{subtitle}</p></div></header>{children}</section>}
function Zones({data,busy,action}:{data:SettingsDashboard;busy:boolean;action:(x:()=>Promise<unknown>)=>void}){const[edit,setEdit]=useState<DeliveryZone>();function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={name:f.get("name"),governorate:f.get("governorate"),cities:f.get("cities")||null,baseFee:Number(f.get("baseFee")),feePerKg:Number(f.get("feePerKg")),feePerKm:Number(f.get("feePerKm")),estimatedDays:Number(f.get("estimatedDays")),isActive:f.get("isActive")==="on"};action(()=>api(`/api/admin/system-settings/delivery-zones${edit?`/${edit.id}`:""}`,send(edit?"PUT":"POST",body)));setEdit(undefined);e.currentTarget.reset()}return <ResourcePanel title="مناطق التوصيل" subtitle="إدارة التغطية والتكلفة والمدة المقدرة لكل منطقة"><form className={styles.inlineForm} onSubmit={submit}><input name="name" placeholder="اسم المنطقة" required defaultValue={edit?.name}/><input name="governorate" placeholder="المحافظة" required defaultValue={edit?.governorate}/><input name="cities" placeholder="المدن" defaultValue={edit?.cities}/><input name="baseFee" type="number" min="0" step=".01" placeholder="التكلفة الأساسية" required defaultValue={edit?.baseFee}/><input name="feePerKg" type="number" min="0" step=".01" placeholder="لكل كجم" required defaultValue={edit?.feePerKg}/><input name="feePerKm" type="number" min="0" step=".01" placeholder="لكل كم" required defaultValue={edit?.feePerKm}/><input name="estimatedDays" type="number" min="1" placeholder="الأيام" required defaultValue={edit?.estimatedDays||2}/><label><input name="isActive" type="checkbox" defaultChecked={edit?.isActive??true}/> نشطة</label><button className={base.primary} disabled={busy}>{edit?"تحديث":"إضافة"}</button></form><Table headers={["المنطقة","المحافظة","التكلفة","المدة","الحالة","الإجراء"]}>{data.deliveryZones.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.cities}</small></td><td>{x.governorate}</td><td>{x.baseFee} ج.م + {x.feePerKg}/كجم</td><td>{x.estimatedDays} يوم</td><td>{x.isActive?"نشطة":"متوقفة"}</td><td><button className={base.secondary} onClick={()=>setEdit(x)}>تعديل</button> <button className={base.danger} onClick={()=>confirm("حذف المنطقة؟")&&action(()=>api(`/api/admin/system-settings/delivery-zones/${x.id}`,send("DELETE")))}>حذف</button></td></tr>)}</Table></ResourcePanel>}
function Banks({data,busy,action}:{data:SettingsDashboard;busy:boolean;action:(x:()=>Promise<unknown>)=>void}){const[edit,setEdit]=useState<BankAccount>();function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={bankName:f.get("bankName"),accountName:f.get("accountName"),accountNumber:f.get("accountNumber"),iban:f.get("iban")||null,currency:f.get("currency"),isPrimary:f.get("isPrimary")==="on",isActive:f.get("isActive")==="on"};action(()=>api(`/api/admin/system-settings/bank-accounts${edit?`/${edit.id}`:""}`,send(edit?"PUT":"POST",body)));setEdit(undefined);e.currentTarget.reset()}return <ResourcePanel title="الحسابات البنكية" subtitle="الحسابات التي تظهر في التحويلات البنكية والفواتير"><form className={styles.inlineForm} onSubmit={submit}><input name="bankName" placeholder="اسم البنك" required defaultValue={edit?.bankName}/><input name="accountName" placeholder="اسم الحساب" required defaultValue={edit?.accountName}/><input name="accountNumber" dir="ltr" placeholder="رقم الحساب" required defaultValue={edit?.accountNumber}/><input name="iban" dir="ltr" placeholder="IBAN" defaultValue={edit?.iban}/><select name="currency" defaultValue={edit?.currency||"EGP"}><option>EGP</option><option>USD</option><option>SAR</option></select><label><input name="isPrimary" type="checkbox" defaultChecked={edit?.isPrimary}/> رئيسي</label><label><input name="isActive" type="checkbox" defaultChecked={edit?.isActive??true}/> نشط</label><button className={base.primary} disabled={busy}>{edit?"تحديث":"إضافة"}</button></form><Table headers={["البنك","الحساب","العملة","النوع","الحالة","الإجراء"]}>{data.bankAccounts.map(x=><tr key={x.id}><td>{x.bankName}</td><td><b>{x.accountName}</b><small dir="ltr">{x.accountNumber} · {x.iban}</small></td><td>{x.currency}</td><td>{x.isPrimary?"رئيسي":"إضافي"}</td><td>{x.isActive?"نشط":"متوقف"}</td><td><button className={base.secondary} onClick={()=>setEdit(x)}>تعديل</button> <button className={base.danger} onClick={()=>confirm("حذف الحساب؟")&&action(()=>api(`/api/admin/system-settings/bank-accounts/${x.id}`,send("DELETE")))}>حذف</button></td></tr>)}</Table></ResourcePanel>}
function Keys({data,busy,action}:{data:SettingsDashboard;busy:boolean;action:(x:()=>Promise<unknown>,m?:string)=>void}){const[secret,setSecret]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{const x=await api<ApiKey>("/api/admin/system-settings/api-keys",send("POST",{name:f.get("name"),scopes:f.getAll("scopes"),expiresAt:f.get("expiresAt")||null}));setSecret(x.secret||"")},"تم إنشاء المفتاح — انسخه الآن")}return <ResourcePanel title="مفاتيح API" subtitle="مفاتيح وصول مشفرة للتطبيقات الخارجية — تُعرض القيمة مرة واحدة"><form className={styles.inlineForm} onSubmit={submit}><input name="name" required placeholder="اسم المفتاح"/><input name="expiresAt" type="datetime-local" required/><fieldset>{["orders.read","orders.write","catalog.read","inventory.read","reports.read","webhooks.manage"].map(x=><label key={x}><input name="scopes" value={x} type="checkbox"/> {x}</label>)}</fieldset><button className={base.primary} disabled={busy}>إنشاء مفتاح</button></form>{secret&&<div className={styles.secret}><b>انسخ المفتاح الآن، لن يظهر مرة أخرى</b><code dir="ltr">{secret}</code><button onClick={()=>navigator.clipboard.writeText(secret)}>نسخ</button></div>}<Table headers={["الاسم","المفتاح","الصلاحيات","آخر استخدام","الحالة","الإجراء"]}>{data.apiKeys.map(x=><tr key={x.id}><td>{x.name}</td><td dir="ltr">{x.maskedKey}</td><td>{x.scopes.join("، ")}</td><td>{x.lastUsedAt?new Date(x.lastUsedAt).toLocaleString("ar-EG"):"لم يستخدم"}</td><td>{x.isActive?"نشط":"ملغي"}</td><td>{x.isActive&&<button className={base.danger} onClick={()=>confirm("إلغاء المفتاح؟")&&action(()=>api(`/api/admin/system-settings/api-keys/${x.id}`,send("DELETE")))}>إلغاء</button>}</td></tr>)}</Table></ResourcePanel>}
function Hooks({data,busy,action}:{data:SettingsDashboard;busy:boolean;action:(x:()=>Promise<unknown>,m?:string)=>void}){const[edit,setEdit]=useState<Webhook>(),[secret,setSecret]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{const x=await api<Webhook>(`/api/admin/system-settings/webhooks${edit?`/${edit.id}`:""}`,send(edit?"PUT":"POST",{event:f.get("event"),url:f.get("url"),isActive:f.get("isActive")==="on"}));if(x.secret)setSecret(x.secret)},edit?"تم تحديث Webhook":"تم إنشاء Webhook");setEdit(undefined)}return <ResourcePanel title="Webhooks" subtitle="إرسال أحداث المنصة آمنًا إلى الأنظمة الخارجية"><form className={styles.inlineForm} onSubmit={submit}><select name="event" defaultValue={edit?.event}>{["order.created","order.updated","invoice.issued","payment.completed","shipment.updated","product.updated"].map(x=><option key={x}>{x}</option>)}</select><input name="url" type="url" dir="ltr" required placeholder="https://example.com/webhook" defaultValue={edit?.url}/><label><input name="isActive" type="checkbox" defaultChecked={edit?.isActive??true}/> نشط</label><button className={base.primary} disabled={busy}>{edit?"تحديث":"إضافة"}</button></form>{secret&&<div className={styles.secret}><b>سر التوقيع — انسخه الآن</b><code dir="ltr">{secret}</code><button onClick={()=>navigator.clipboard.writeText(secret)}>نسخ</button></div>}<Table headers={["الحدث","الرابط","آخر تشغيل","الإخفاقات","الحالة","الإجراء"]}>{data.webhooks.map(x=><tr key={x.id}><td>{x.event}</td><td dir="ltr">{x.url}</td><td>{x.lastTriggeredAt?new Date(x.lastTriggeredAt).toLocaleString("ar-EG"):"—"}</td><td>{x.failureCount}</td><td>{x.isActive?"نشط":"متوقف"}</td><td><button className={base.secondary} onClick={()=>setEdit(x)}>تعديل</button> <button className={base.danger} onClick={()=>confirm("حذف Webhook؟")&&action(()=>api(`/api/admin/system-settings/webhooks/${x.id}`,send("DELETE")))}>حذف</button></td></tr>)}</Table></ResourcePanel>}
function Translations({data,busy,action}:{data:SettingsDashboard;busy:boolean;action:(x:()=>Promise<unknown>)=>void}){const[edit,setEdit]=useState<Translation>();function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);action(()=>api("/api/admin/system-settings/translations",send("POST",{id:edit?.id||null,key:f.get("key"),arabic:f.get("arabic"),english:f.get("english"),french:f.get("french")||null})));setEdit(undefined)}return <ResourcePanel title="إدارة الترجمات" subtitle="إدارة نصوص الواجهة بالعربية والإنجليزية والفرنسية"><form className={styles.inlineForm} onSubmit={submit}><input name="key" dir="ltr" required placeholder="settings.save" defaultValue={edit?.key}/><input name="arabic" required placeholder="النص العربي" defaultValue={edit?.arabic}/><input name="english" dir="ltr" required placeholder="English text" defaultValue={edit?.english}/><input name="french" dir="ltr" placeholder="Texte français" defaultValue={edit?.french}/><button className={base.primary} disabled={busy}>{edit?"تحديث":"إضافة"}</button></form><Table headers={["المفتاح","العربية","English","Français","الإجراء"]}>{data.translations.map(x=><tr key={x.id}><td dir="ltr">{x.key}</td><td>{x.arabic}</td><td dir="ltr">{x.english}</td><td dir="ltr">{x.french||"—"}</td><td><button className={base.secondary} onClick={()=>setEdit(x)}>تعديل</button></td></tr>)}</Table></ResourcePanel>}
function Logs({data}:{data:SettingsDashboard}){return <ResourcePanel title="سجل التكاملات" subtitle="سجل عمليات الربط والنتائج ومحاولات إعادة التشغيل"><Table headers={["التكامل","العملية","المرجع","الحالة","المحاولة","المدة","وقت البدء"]}>{data.integrationLogs.map(x=><tr key={x.id}><td>{x.integration}</td><td>{x.operation}<small>{x.error}</small></td><td>{x.reference||"—"}</td><td>{x.status}</td><td>{x.attempt}</td><td>{x.durationMs} ms</td><td>{new Date(x.startedAt).toLocaleString("ar-EG")}</td></tr>)}</Table></ResourcePanel>}
function BackupHistory({data,busy,run}:{data:SettingsDashboard;busy:boolean;run:()=>void}){return <section className={styles.panel}><header><div className={styles.titleIcon}>▰</div><div><h2>سجل النسخ الاحتياطي</h2><p>نسخ SQLite متسقة مع بصمة SHA-256 وسياسة احتفاظ تلقائية.</p></div><button className={base.primary} disabled={busy} onClick={run}>{busy?"جاري النسخ...":"إنشاء نسخة الآن"}</button></header><Table headers={["الملف","الحجم","النوع","الحالة","تاريخ البدء","النتيجة"]}>{data.backups.map(x=><tr key={x.id}><td dir="ltr">{x.fileName}</td><td>{(x.sizeBytes/1048576).toFixed(2)} MB</td><td>{x.isAutomatic?"تلقائية":"يدوية"}</td><td>{x.status}</td><td>{new Date(x.startedAt).toLocaleString("ar-EG")}</td><td>{x.error||"مكتملة"}</td></tr>)}</Table></section>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className={base.table}><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
