"use client";

import {type FormEvent,useEffect,useMemo,useState} from "react";
import base from "../operations.module.css";
import styles from "./users.module.css";
import type {AccessDashboard,AuditDetail,Permission,SystemRole,SystemUser,UserScope} from "./system-access-types";

type View="users"|"roles"|"permissions"|"scopes"|"logins"|"sessions"|"audit";
type Modal={kind:"user";value?:SystemUser}|{kind:"role";value?:SystemRole}|{kind:"suspend";value:SystemUser}|{kind:"password";value:SystemUser}|{kind:"audit";value:AuditDetail}|null;
const nf=new Intl.NumberFormat("ar-EG"),df=new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium",timeStyle:"short"});
const when=(v?:string)=>v?df.format(new Date(v)):"—";
const actionLabels:Record<string,string>={view:"عرض",create:"إنشاء",update:"تعديل",delete:"حذف",approve:"اعتماد",manage:"إدارة",export:"تصدير",assign:"تعيين"};
const moduleLabels:Record<string,string>={admin:"الإدارة",catalog:"الكتالوج",orders:"الطلبات",quotes:"عروض الأسعار",inventory:"المخزون",procurement:"المشتريات",crm:"الشركات وCRM",marketing:"التسويق",shipping:"الشحن",accounting:"الحسابات",content:"المحتوى",users:"المستخدمون",reports:"التقارير",settings:"الإعدادات"};
async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,cache:"no-store"});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.title||"تعذر تنفيذ العملية")}return r.status===204?undefined as T:r.json()}

export function SystemAccessManager(){
 const[data,setData]=useState<AccessDashboard|null>(null),[view,setView]=useState<View>("users"),[modal,setModal]=useState<Modal>(null),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>setData(await api("/api/admin/system-access"));
 useEffect(()=>{let active=true;api<AccessDashboard>("/api/admin/system-access").then(x=>active&&setData(x)).catch(e=>active&&setError((e as Error).message));return()=>{active=false}},[]);
 async function mutate(url:string,init:RequestInit={method:"POST"}){setBusy(true);setError("");try{await api(url,init);setModal(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function openAudit(id:number){setBusy(true);try{setModal({kind:"audit",value:await api(`/api/admin/system-access/audit/${id}`)})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!data)return <p className={base.empty}>{error||"جاري تحميل المستخدمين والصلاحيات..."}</p>;
 const tabs:[View,string][]=[["users","المستخدمون"],["roles","الأدوار"],["permissions","مصفوفة الصلاحيات"],["scopes","الفروع والمخازن"],["logins","سجل الدخول"],["sessions","الجلسات النشطة"],["audit","سجل التدقيق"]];
 return <section className={base.page}>
  <header className={styles.hero}><div><span className={base.eyebrow}>إدارة النظام والأمان</span><h1>المستخدمون والصلاحيات</h1><p>تحكم مركزي في حسابات الإدارة والأدوار ونطاق الوصول والجلسات، مع سجل تدقيق كامل.</p></div><div className={base.actions}><button className={base.secondary} onClick={()=>setView("audit")}>سجل التدقيق</button><button className={base.primary} onClick={()=>setModal({kind:"user"})}>+ إضافة مستخدم</button></div></header>
  <div className={styles.kpis}><Kpi icon="♙" label="مستخدمون نشطون" value={data.kpis.activeUsers} note={`${data.users.length} إجمالي الحسابات`}/><Kpi icon="◇" label="الأدوار" value={data.kpis.roles} note={`${data.permissions.length} صلاحية معرفة`}/><Kpi icon="◉" label="جلسات نشطة" value={data.kpis.activeSessions} note="متصلة الآن"/><Kpi icon="⊘" label="حسابات معلقة" value={data.kpis.suspendedUsers} note="ممنوعة من الدخول"/></div>
  <nav className={base.tabs}>{tabs.map(([id,label])=><button key={id} className={view===id?base.active:""} onClick={()=>setView(id)}>{label}</button>)}</nav>
  {view==="users"&&<UsersView data={data} query={query} setQuery={setQuery} edit={x=>setModal({kind:"user",value:x})} suspend={x=>setModal({kind:"suspend",value:x})} password={x=>setModal({kind:"password",value:x})} resume={x=>void mutate(`/api/admin/system-access/users/${x.id}/resume`)}/>}
  {view==="roles"&&<RolesView data={data} edit={x=>setModal({kind:"role",value:x})} create={()=>setModal({kind:"role"})}/>}
  {view==="permissions"&&<PermissionsView data={data}/>}
  {view==="scopes"&&<ScopesView data={data} busy={busy} save={(id,scope)=>void mutate(`/api/admin/system-access/users/${id}/scopes`,json("PUT",{branchIds:scope.branchIds,warehouseIds:scope.warehouseIds}))}/>}
  {view==="logins"&&<LoginView data={data}/>}
  {view==="sessions"&&<SessionsView data={data} revoke={id=>void mutate(`/api/admin/system-access/sessions/${id}`,{method:"DELETE"})}/>}
  {view==="audit"&&<AuditView data={data} open={id=>void openAudit(id)}/>}
  {modal?.kind==="user"&&<UserModal data={data} value={modal.value} busy={busy} close={()=>setModal(null)} save={(id,body)=>void mutate(`/api/admin/system-access/users${id?`/${id}`:""}`,json(id?"PUT":"POST",body))}/>}
  {modal?.kind==="role"&&<RoleModal data={data} value={modal.value} busy={busy} close={()=>setModal(null)} save={(id,body)=>void mutate(`/api/admin/system-access/roles${id?`/${id}`:""}`,json(id?"PUT":"POST",body))}/>}
  {modal?.kind==="suspend"&&<SuspendModal user={modal.value} busy={busy} close={()=>setModal(null)} save={body=>void mutate(`/api/admin/system-access/users/${modal.value.id}/suspend`,json("POST",body))}/>}
  {modal?.kind==="password"&&<PasswordModal user={modal.value} busy={busy} close={()=>setModal(null)} save={body=>void mutate(`/api/admin/system-access/users/${modal.value.id}/reset-password`,json("POST",body))}/>}
  {modal?.kind==="audit"&&<AuditModal detail={modal.value} close={()=>setModal(null)}/>}
  {error&&<div className={base.alert}>{error}</div>}
 </section>
}
function json(method:string,body:unknown):RequestInit{return{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}}
function Kpi({icon,label,value,note}:{icon:string;label:string;value:number;note:string}){return <article className={base.kpi}><i>{icon}</i><span>{label}</span><b>{nf.format(value)}</b><small>{note}</small></article>}

function UsersView({data,query,setQuery,edit,suspend,password,resume}:{data:AccessDashboard;query:string;setQuery:(x:string)=>void;edit:(x:SystemUser)=>void;suspend:(x:SystemUser)=>void;password:(x:SystemUser)=>void;resume:(x:SystemUser)=>void}){const users=data.users.filter(x=>!query||`${x.fullName} ${x.email} ${x.phone} ${x.roles}`.toLowerCase().includes(query.toLowerCase()));return <section className={base.panel}><div className={base.panelHead}><div><h2>مستخدمو لوحة الإدارة</h2><span>{users.length} مستخدم مطابق</span></div><input className={styles.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالاسم أو البريد أو الدور..."/></div><div className={base.table}><table><thead><tr><th>المستخدم</th><th>القسم</th><th>الدور</th><th>الحماية</th><th>الجلسات</th><th>الحالة</th><th>آخر إجراء</th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td><div className={styles.person}><i>{x.fullName.at(0)}</i><div><b>{x.fullName}</b><small>{x.email} · {x.phone}</small></div></div></td><td>{x.department||"—"}<small>{x.jobTitle}</small></td><td><div className={styles.tags}>{x.roles.map(r=><u key={r}>{r}</u>)}</div></td><td>{x.twoFactorEnabled?<span className={styles.good}>✓ تحقق بخطوتين</span>:<span className={styles.warn}>بدون 2FA</span>}</td><td>{nf.format(x.activeSessions)}</td><td><u className={`${base.status} ${x.isActive?base.completed:base.rejected}`}>{x.isActive?"نشط":"معلق"}</u>{x.suspendedUntil&&<small>حتى {when(x.suspendedUntil)}</small>}</td><td><div className={base.actions}><button className={base.secondary} onClick={()=>edit(x)}>تعديل</button><button className={base.secondary} onClick={()=>password(x)}>كلمة المرور</button>{x.isActive?<button className={base.danger} onClick={()=>suspend(x)}>تعليق</button>:<button className={base.primary} onClick={()=>resume(x)}>إعادة تفعيل</button>}</div></td></tr>)}</tbody></table></div></section>}

function RolesView({data,edit,create}:{data:AccessDashboard;edit:(x:SystemRole)=>void;create:()=>void}){return <><section className={base.panel}><div className={base.panelHead}><div><h2>الأدوار</h2><span>مجموعات صلاحيات قابلة لإعادة الاستخدام</span></div><button className={base.primary} onClick={create}>+ إنشاء دور</button></div><div className={styles.roleGrid}>{data.roles.map(x=><article key={x.id}><header><i>◇</i><u className={`${base.status} ${x.isSystem?base.issued:""}`}>{x.isSystem?"دور نظام":"مخصص"}</u></header><h3>{x.nameAr}</h3><p>{x.nameEn} · <code>{x.code}</code></p><div><span>{x.userCount} مستخدم</span><span>{x.permissionIds.length} صلاحية</span></div><button className={base.secondary} disabled={x.code==="super_admin"} onClick={()=>edit(x)}>إدارة الصلاحيات</button></article>)}</div></section></>}

function PermissionsView({data}:{data:AccessDashboard}){const[mode,setMode]=useState<"matrix"|"module"|"action">("matrix"),modules=useMemo(()=>[...new Set(data.permissions.map(x=>x.module))],[data]);return <section className={base.panel}><div className={base.panelHead}><div><h2>مصفوفة الصلاحيات</h2><span>عرض الصلاحيات حسب الدور أو الوحدة أو الإجراء</span></div><div className={base.actions}><button className={mode==="matrix"?base.primary:base.secondary} onClick={()=>setMode("matrix")}>المصفوفة</button><button className={mode==="module"?base.primary:base.secondary} onClick={()=>setMode("module")}>حسب الوحدة</button><button className={mode==="action"?base.primary:base.secondary} onClick={()=>setMode("action")}>حسب الإجراء</button></div></div>{mode==="matrix"?<div className={`${base.table} ${styles.matrix}`}><table><thead><tr><th>الوحدة</th>{data.roles.map(r=><th key={r.id}>{r.nameAr}</th>)}</tr></thead><tbody>{modules.map(m=><tr key={m}><td><b>{moduleLabels[m.toLowerCase()]||m}</b><small>{data.permissions.filter(p=>p.module===m).length} صلاحيات</small></td>{data.roles.map(r=>{const ids=data.permissions.filter(p=>p.module===m).map(p=>p.id),count=ids.filter(id=>r.permissionIds.includes(id)).length;return <td key={r.id}><span className={count===ids.length?styles.all:count?styles.some:styles.none}>{count===ids.length?"✓ كامل":count?`${count}/${ids.length}`:"—"}</span></td>})}</tr>)}</tbody></table></div>:mode==="module"?<PermissionGroups groups={modules.map(x=>[moduleLabels[x.toLowerCase()]||x,data.permissions.filter(p=>p.module===x)] as [string,Permission[]])}/>:<PermissionGroups groups={[...new Set(data.permissions.map(x=>x.action))].map(x=>[actionLabels[x]||x,data.permissions.filter(p=>p.action===x)] as [string,Permission[]])}/>}</section>}
function PermissionGroups({groups}:{groups:[string,Permission[]][]}){return <div className={styles.permissionGroups}>{groups.map(([name,items])=><article key={name}><header><i>▦</i><div><h3>{name}</h3><small>{items.length} صلاحية</small></div></header>{items.map(x=><p key={x.id}><b>{x.descriptionAr||x.code}</b><code>{x.code}</code></p>)}</article>)}</div>}

function ScopesView({data,busy,save}:{data:AccessDashboard;busy:boolean;save:(id:string,scope:UserScope)=>void}){const initialId=data.users[0]?.id||"",scopeFor=(id:string)=>data.scopes.find(x=>x.userId===id)||{userId:id,branchIds:[],warehouseIds:[]};const[userId,setUserId]=useState(initialId),[kind,setKind]=useState<"branch"|"warehouse">("branch"),[draft,setDraft]=useState<UserScope>(scopeFor(initialId));const options=kind==="branch"?data.branches:data.warehouses,key=kind==="branch"?"branchIds":"warehouseIds";function choose(id:string){setUserId(id);setDraft(scopeFor(id))}function toggle(id:string){setDraft(x=>({...x,[key]:x[key].includes(id)?x[key].filter(y=>y!==id):[...x[key],id]}))}return <div className={styles.scopeLayout}><aside className={base.panel}><div className={base.panelHead}><h3>المستخدمون</h3></div>{data.users.map(x=><button key={x.id} className={userId===x.id?styles.selectedUser:""} onClick={()=>choose(x.id)}><i>{x.fullName.at(0)}</i><span><b>{x.fullName}</b><small>{x.roles.join("، ")}</small></span></button>)}</aside><section className={base.panel}><div className={base.panelHead}><div><h2>نطاق الوصول</h2><span>اترك كل الخيارات فارغة للسماح بالوصول العام</span></div><button className={base.primary} disabled={busy} onClick={()=>save(userId,draft)}>حفظ النطاق</button></div><nav className={styles.scopeTabs}><button className={kind==="branch"?styles.active:""} onClick={()=>setKind("branch")}>الفروع ({draft.branchIds.length})</button><button className={kind==="warehouse"?styles.active:""} onClick={()=>setKind("warehouse")}>المخازن ({draft.warehouseIds.length})</button></nav><div className={styles.scopeOptions}>{options.map(x=><label key={x.id}><input type="checkbox" checked={draft[key].includes(x.id)} onChange={()=>toggle(x.id)}/><i>{kind==="branch"?"⌂":"▥"}</i><span><b>{x.name}</b><small>{x.context}</small></span></label>)}{!options.length&&<p className={base.empty}>لا توجد خيارات متاحة.</p>}</div></section></div>}

function LoginView({data}:{data:AccessDashboard}){const[status,setStatus]=useState("all"),rows=data.loginAudits.filter(x=>status==="all"||String(x.succeeded)===status);return <section className={base.panel}><div className={base.panelHead}><div><h2>سجل تسجيل الدخول</h2><span>المحاولات الناجحة والفاشلة</span></div><div className={base.actions}><select className={styles.select} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">كل الحالات</option><option value="true">ناجحة</option><option value="false">فاشلة</option></select><button className={base.secondary} onClick={()=>exportCsv("login-audit.csv",rows)}>تصدير CSV</button></div></div><div className={base.table}><table><thead><tr><th>المستخدم</th><th>الوقت</th><th>الجهاز</th><th>عنوان IP</th><th>الموقع</th><th>الحالة</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.userName||x.identifier}</b><small>{x.identifier}</small></td><td>{when(x.at)}</td><td className={styles.device}>{x.device||"غير معروف"}</td><td dir="ltr">{x.ipAddress||"—"}</td><td>{x.location||"—"}</td><td><u className={`${base.status} ${x.succeeded?base.completed:base.rejected}`}>{x.succeeded?"ناجحة":"فاشلة"}</u><small>{x.failureReason}</small></td></tr>)}</tbody></table>{!rows.length&&<p className={base.empty}>لا توجد محاولات مسجلة بعد.</p>}</div></section>}
function SessionsView({data,revoke}:{data:AccessDashboard;revoke:(id:string)=>void}){return <section className={base.panel}><div className={base.panelHead}><div><h2>الجلسات النشطة</h2><span>{data.sessions.length} جلسة يمكن إلغاؤها فورًا</span></div></div><div className={styles.sessions}>{data.sessions.map(x=><article key={x.id}><i>{x.device?.includes("Mobile")?"▯":"▰"}</i><div><h3>{x.userName}{x.isCurrent&&<u>الحساب الحالي</u>}</h3><p>{x.device||"جهاز غير معروف"} · <span dir="ltr">{x.ipAddress||"IP غير متاح"}</span></p><small>آخر نشاط {when(x.lastSeenAt)} · تنتهي {when(x.expiresAt)}</small></div><button className={base.danger} onClick={()=>revoke(x.id)}>إنهاء الجلسة</button></article>)}{!data.sessions.length&&<p className={base.empty}>لا توجد جلسات نشطة.</p>}</div></section>}
function AuditView({data,open}:{data:AccessDashboard;open:(id:number)=>void}){const[q,setQ]=useState(""),rows=data.auditLogs.filter(x=>!q||`${x.actorName} ${x.action} ${x.entityType} ${x.entityId}`.toLowerCase().includes(q.toLowerCase()));return <section className={base.panel}><div className={base.panelHead}><div><h2>سجل التدقيق</h2><span>سجل غير قابل للتعديل لكل العمليات الحساسة</span></div><div className={base.actions}><input className={styles.search} value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالمستخدم أو الإجراء..."/><button className={base.secondary} onClick={()=>exportCsv("system-audit.csv",rows)}>تصدير CSV</button></div></div><div className={base.table}><table><thead><tr><th>الوقت</th><th>المستخدم</th><th>الإجراء</th><th>الكيان</th><th>عنوان IP</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id} onClick={()=>open(x.id)}><td>{when(x.at)}</td><td>{x.actorName||"النظام"}</td><td><code>{x.action}</code></td><td>{x.entityType}<small>{x.entityId}</small></td><td dir="ltr">{x.ip||"—"}</td><td><button className={base.secondary}>التفاصيل</button></td></tr>)}</tbody></table></div></section>}

function UserModal({data,value,busy,close,save}:{data:AccessDashboard;value?:SystemUser;busy:boolean;close:()=>void;save:(id:string|undefined,body:unknown)=>void}){const roleIds=data.roles.filter(r=>value?.roles.includes(r.code)).map(r=>r.id),scope=data.scopes.find(x=>x.userId===value?.id);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);save(value?.id,{fullName:f.get("fullName"),phone:f.get("phone"),email:f.get("email"),password:f.get("password")||null,jobTitle:f.get("jobTitle")||null,department:f.get("department")||null,isActive:f.get("isActive")==="on",twoFactorEnabled:f.get("twoFactorEnabled")==="on",roleIds:f.getAll("roleIds"),branchIds:scope?.branchIds||[],warehouseIds:scope?.warehouseIds||[]})}return <ModalFrame title={value?"تعديل المستخدم":"إضافة مستخدم إداري"} subtitle="بيانات الحساب والدور وإعدادات الحماية" close={close}><form className={base.form} onSubmit={submit}><div className={base.cols}><label>الاسم الكامل<input name="fullName" required defaultValue={value?.fullName}/></label><label>رقم الهاتف<input name="phone" dir="ltr" required defaultValue={value?.phone}/></label></div><div className={base.cols}><label>البريد الإلكتروني<input name="email" type="email" dir="ltr" required defaultValue={value?.email}/></label><label>{value?"كلمة مرور جديدة (اختياري)":"كلمة المرور"}<input name="password" type="password" minLength={8} required={!value}/></label></div><div className={base.cols}><label>المسمى الوظيفي<input name="jobTitle" defaultValue={value?.jobTitle}/></label><label>القسم<input name="department" defaultValue={value?.department}/></label></div><div><b className={styles.fieldTitle}>الأدوار</b><div className={styles.checkGrid}>{data.roles.map(x=><label key={x.id}><input name="roleIds" value={x.id} type="checkbox" defaultChecked={roleIds.includes(x.id)}/><span><b>{x.nameAr}</b><small>{x.code}</small></span></label>)}</div></div><div className={styles.switches}><label><span><b>الحساب نشط</b><small>يسمح بتسجيل الدخول</small></span><input name="isActive" type="checkbox" defaultChecked={value?.isActive??true}/></label><label><span><b>التحقق بخطوتين</b><small>رمز إضافي عند الدخول</small></span><input name="twoFactorEnabled" type="checkbox" defaultChecked={value?.twoFactorEnabled}/></label></div><footer><button type="button" className={base.secondary} onClick={close}>إلغاء</button><button className={base.primary} disabled={busy}>{busy?"جاري الحفظ...":"حفظ المستخدم"}</button></footer></form></ModalFrame>}
function RoleModal({data,value,busy,close,save}:{data:AccessDashboard;value?:SystemRole;busy:boolean;close:()=>void;save:(id:string|undefined,body:unknown)=>void}){const[selected,setSelected]=useState<number[]>(value?.permissionIds||[]),modules=[...new Set(data.permissions.map(x=>x.module))];function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);save(value?.id,{code:f.get("code"),nameAr:f.get("nameAr"),nameEn:f.get("nameEn"),permissionIds:selected})}function module(id:string,on:boolean){const ids=data.permissions.filter(x=>x.module===id).map(x=>x.id);setSelected(x=>on?[...new Set([...x,...ids])]:x.filter(y=>!ids.includes(y)))}return <ModalFrame title={value?"تعديل الدور":"إنشاء دور"} subtitle="حدد هوية الدور وصلاحياته بدقة" close={close} wide><form className={base.form} onSubmit={submit}><div className={styles.roleFields}><label>كود الدور<input name="code" dir="ltr" required defaultValue={value?.code}/></label><label>الاسم بالعربية<input name="nameAr" required defaultValue={value?.nameAr}/></label><label>الاسم بالإنجليزية<input name="nameEn" dir="ltr" required defaultValue={value?.nameEn}/></label></div><div className={styles.permissionEditor}>{modules.map(m=>{const items=data.permissions.filter(x=>x.module===m),all=items.every(x=>selected.includes(x.id));return <article key={m}><header><label><input type="checkbox" checked={all} onChange={e=>module(m,e.target.checked)}/><b>{moduleLabels[m.toLowerCase()]||m}</b></label><small>{items.filter(x=>selected.includes(x.id)).length}/{items.length}</small></header>{items.map(x=><label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(y=>e.target.checked?[...y,x.id]:y.filter(z=>z!==x.id))}/><span>{x.descriptionAr||x.code}<code>{x.code}</code></span></label>)}</article>})}</div><footer><button type="button" className={base.secondary} onClick={close}>إلغاء</button><button className={base.primary} disabled={busy||!selected.length}>حفظ الدور</button></footer></form></ModalFrame>}
function SuspendModal({user,busy,close,save}:{user:SystemUser;busy:boolean;close:()=>void;save:(body:unknown)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),duration=String(f.get("duration")),until=duration==="permanent"?null:new Date(Date.now()+Number(duration)*86400000).toISOString();save({reason:f.get("reason"),until})}return <ModalFrame title={`تعليق حساب ${user.fullName}`} subtitle="سيتم إنهاء جميع جلساته النشطة ومنع أي دخول جديد" close={close}><form className={base.form} onSubmit={submit}><div className={styles.warningBox}>⚠ هذا الإجراء فوري ومسجل في سجل التدقيق.</div><label>سبب التعليق<select name="reason" required><option value="">اختر السبب</option><option>مخالفة سياسات الأمان</option><option>إجازة أو توقف مؤقت</option><option>انتهاء علاقة العمل</option><option>طلب من الإدارة</option></select></label><label>المدة<select name="duration"><option value="1">يوم واحد</option><option value="7">7 أيام</option><option value="30">30 يومًا</option><option value="permanent">حتى إعادة التفعيل يدويًا</option></select></label><footer><button type="button" className={base.secondary} onClick={close}>إلغاء</button><button className={base.danger} disabled={busy}>تعليق وإنهاء الجلسات</button></footer></form></ModalFrame>}
function PasswordModal({user,busy,close,save}:{user:SystemUser;busy:boolean;close:()=>void;save:(body:unknown)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),a=String(f.get("password")),b=String(f.get("confirm"));if(a!==b)return;save({newPassword:a})}return <ModalFrame title="إعادة تعيين كلمة المرور" subtitle={`${user.fullName} · سيتم إنهاء كل الجلسات الحالية`} close={close}><form className={base.form} onSubmit={submit}><label>كلمة المرور الجديدة<input name="password" type="password" minLength={8} required/></label><label>تأكيد كلمة المرور<input name="confirm" type="password" minLength={8} required/></label><footer><button type="button" className={base.secondary} onClick={close}>إلغاء</button><button className={base.primary} disabled={busy}>تعيين كلمة المرور</button></footer></form></ModalFrame>}
function AuditModal({detail,close}:{detail:AuditDetail;close:()=>void}){let parsed:unknown=detail.dataJson;try{parsed=detail.dataJson?JSON.parse(detail.dataJson):null}catch{}return <ModalFrame title="تفاصيل سجل التدقيق" subtitle={`السجل #${detail.id}`} close={close} wide><div className={styles.auditMeta}><div><span>التاريخ والوقت</span><b>{when(detail.at)}</b></div><div><span>المستخدم</span><b>{detail.actorName||"النظام"}</b></div><div><span>الإجراء</span><code>{detail.action}</code></div><div><span>الكيان</span><b>{detail.entityType} · {detail.entityId}</b></div><div><span>عنوان IP</span><b dir="ltr">{detail.ip||"—"}</b></div></div><h3 className={styles.changeTitle}>القيم قبل وبعد التغيير</h3><pre className={styles.json}>{JSON.stringify(parsed,null,2)||"لا توجد بيانات إضافية"}</pre></ModalFrame>}
function ModalFrame({title,subtitle,close,wide,children}:{title:string;subtitle:string;close:()=>void;wide?:boolean;children:React.ReactNode}){return <div className={base.modalBack}><section className={`${base.modal} ${wide?styles.wideModal:""}`}><header><div><h2>{title}</h2><small>{subtitle}</small></div><button onClick={close}>×</button></header>{children}</section></div>}
function exportCsv(name:string,rows:unknown[]){if(!rows.length)return;const objects=rows as Record<string,unknown>[],keys=Object.keys(objects[0]),cell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`,csv="\uFEFF"+[keys.join(","),...objects.map(x=>keys.map(k=>cell(x[k])).join(","))].join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
