"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { money, QuotePage, quoteStatus, QuoteTemplate } from "./quote-types";

type View="all"|"review"|"suppliers"|"drafts"|"negotiating"|"accepted"|"expired"|"templates";
const viewStatus:Record<View,string>={all:"",review:"NeedsReview,UnderReview",suppliers:"UnderReview",drafts:"UnderReview",negotiating:"Negotiating",accepted:"Accepted",expired:"Expired",templates:""};

export function QuoteManager(){
  const [view,setView]=useState<View>("all");const [data,setData]=useState<QuotePage|null>(null);const [templates,setTemplates]=useState<QuoteTemplate[]>([]);
  const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [page,setPage]=useState(1);const [editor,setEditor]=useState(false);
  const load=useCallback(async(signal?:AbortSignal)=>{if(view==="templates"){const r=await fetch("/api/admin/quotes/templates",{signal});if(!r.ok)throw new Error("تعذر تحميل القوالب");setTemplates(await r.json());return}const p=new URLSearchParams({search:query,statuses:viewStatus[view],page:String(page),pageSize:"20"});const r=await fetch(`/api/admin/quotes?${p}`,{signal});if(!r.ok)throw new Error("تعذر تحميل عروض الأسعار");const value:QuotePage=await r.json();if(view==="suppliers")value.items=value.items.filter(x=>x.status==="UnderReview");if(view==="drafts")value.items=value.items.filter(x=>x.status==="UnderReview"&&x.versionCount>0);setData(value)},[view,query,page]);
  useEffect(()=>{const c=new AbortController();const request=view==="templates"?fetch("/api/admin/quotes/templates",{signal:c.signal}):fetch(`/api/admin/quotes?${new URLSearchParams({search:query,statuses:viewStatus[view],page:String(page),pageSize:"20"})}`,{signal:c.signal});request.then(async r=>{if(!r.ok)throw new Error(view==="templates"?"تعذر تحميل القوالب":"تعذر تحميل عروض الأسعار");const value=await r.json();if(view==="templates")setTemplates(value);else{const pageValue=value as QuotePage;if(view==="suppliers")pageValue.items=pageValue.items.filter(x=>x.status==="UnderReview");if(view==="drafts")pageValue.items=pageValue.items.filter(x=>x.status==="UnderReview"&&x.versionCount>0);setData(pageValue)}}).catch(e=>{if(e.name!=="AbortError")setError(e.message)}).finally(()=>setLoading(false));return()=>c.abort()},[view,query,page]);
  async function refresh(){setLoading(true);try{await load()}catch(e){setError(e instanceof Error?e.message:"تعذر التحميل")}finally{setLoading(false)}}
  function change(next:View){setLoading(true);setError("");setView(next);setPage(1)}
  function search(e:FormEvent){e.preventDefault();setPage(1);refresh()}
  function exportCsv(){if(!data)return;const rows=[["رقم الطلب","الشركة","العميل","الحالة","الإجمالي","الموعد"],...data.items.map(x=>[x.number,x.company,x.customer,quoteStatus[x.status]??x.status,String(x.latestTotal??0),x.deadline])];const csv="\uFEFF"+rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="quotes.csv";a.click();URL.revokeObjectURL(a.href)}
  async function saveTemplate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/quotes/templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),description:f.get("description"),validDays:Number(f.get("validDays")),deliveryDays:Number(f.get("deliveryDays")),terms:f.get("terms"),discountType:f.get("discountType"),discountValue:Number(f.get("discountValue")),isActive:true})});if(r.ok){setEditor(false);refresh()}else setError("تعذر حفظ القالب")}
  const s=data?.summary;
  return <>
    <div className="page-heading"><div><p>المبيعات / عروض الأسعار</p><h1>إدارة عروض الأسعار</h1><span>من استلام الطلب حتى القبول والتحويل لأمر شراء</span></div><div className="heading-actions"><button className="secondary-button" onClick={exportCsv} disabled={view==="templates"}>تصدير</button>{view==="templates"&&<button className="primary-button" onClick={()=>setEditor(true)}>+ قالب جديد</button>}</div></div>
    <div className="quote-view-tabs">{([['all','كل الطلبات'],['review','تحتاج مراجعة'],['suppliers','بانتظار الموردين'],['drafts','المسودات'],['negotiating','التفاوض'],['accepted','المقبولة'],['expired','المنتهية'],['templates','القوالب']] as const).map(([k,l])=><button key={k} className={view===k?"active":""} onClick={()=>change(k)}>{l}{s&&k!=="all"&&k!=="templates"?<em>{{review:s.needsReview,suppliers:s.awaitingSuppliers,drafts:s.drafts,negotiating:s.negotiating,accepted:s.accepted,expired:s.expired}[k]}</em>:null}</button>)}</div>
    {view!=="templates"&&s&&<section className="quote-kpis"><article><span>إجمالي الطلبات</span><b>{s.total}</b></article><article><span>تحتاج مراجعة</span><b>{s.needsReview}</b></article><article><span>بانتظار الموردين</span><b>{s.awaitingSuppliers}</b></article><article><span>قيد التفاوض</span><b>{s.negotiating}</b></article><article className="success"><span>تم قبولها</span><b>{s.accepted}</b></article></section>}
    {view!=="templates"&&<form className="panel order-toolbar" onSubmit={search}><div className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="رقم RFQ، اسم الشركة أو العميل"/></div><button className="secondary-button">بحث</button><span>{data?.total??0} نتيجة</span></form>}
    {error&&<div className="admin-alert"><span>{error}</span><button onClick={refresh}>إعادة المحاولة</button></div>}
    {loading?<div className="admin-loading"><span className="loading-ring"/>جاري تحميل عروض الأسعار...</div>:view==="templates"?<section className="quote-template-grid">{templates.map(t=><article className="panel" key={t.id}><header><span>QT</span><div><b>{t.name}</b><small>{t.description??"قالب عرض سعر جاهز"}</small></div><em>{t.isActive?"نشط":"متوقف"}</em></header><dl><div><dt>الصلاحية</dt><dd>{t.validDays} يوم</dd></div><div><dt>التوريد</dt><dd>{t.deliveryDays} يوم</dd></div><div><dt>الخصم</dt><dd>{t.discountType==="None"?"بدون":`${t.discountValue}${t.discountType==="Percent"?"%":" ج.م"}`}</dd></div></dl><p>{t.terms??"لا توجد شروط إضافية"}</p></article>)}{!templates.length&&<div className="admin-empty">لا توجد قوالب بعد</div>}</section>:<section className="panel quotes-table-panel"><div className="table-wrap"><table><thead><tr><th>طلب التسعير</th><th>الشركة / العميل</th><th>الأصناف</th><th>آخر قيمة</th><th>الموعد النهائي</th><th>الحالة</th><th>النسخ</th><th/></tr></thead><tbody>{data?.items.map(q=><tr key={q.id}><td><Link href={`/dashboard/quotes/${q.id}`}><b>{q.number}</b><small>{q.title}</small></Link></td><td><b>{q.company}</b><small>{q.customer}</small></td><td>{q.itemCount}</td><td>{q.latestTotal==null?"—":money.format(q.latestTotal)}</td><td className={new Date(q.deadline)<new Date()?"late-date":""}>{new Date(q.deadline).toLocaleDateString("ar-EG")}</td><td><span className={`status-chip status-${q.status.toLowerCase()}`}>{quoteStatus[q.status]??q.status}</span></td><td>V{q.versionCount||"—"}</td><td><Link className="row-open" href={`/dashboard/quotes/${q.id}`}>إدارة ←</Link></td></tr>)}</tbody></table></div>{!data?.items.length&&<div className="admin-empty compact">لا توجد طلبات مطابقة</div>}<div className="admin-pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>السابق</button><span>صفحة {page}</span><button disabled={page*20>=(data?.total??0)} onClick={()=>setPage(page+1)}>التالي</button></div></section>}
    {editor&&<div className="modal-backdrop"><section className="mini-editor"><header><h2>إنشاء قالب عرض سعر</h2><button onClick={()=>setEditor(false)}>×</button></header><form onSubmit={saveTemplate}><label>اسم القالب<input name="name" required/></label><label>وصف مختصر<input name="description"/></label><div className="form-grid"><label>مدة الصلاحية<input name="validDays" type="number" min="1" defaultValue="14" required/></label><label>مدة التوريد<input name="deliveryDays" type="number" min="1" defaultValue="5" required/></label><label>نوع الخصم<select name="discountType"><option value="None">بدون</option><option value="Percent">نسبة</option><option value="Fixed">مبلغ</option></select></label><label>قيمة الخصم<input name="discountValue" type="number" min="0" defaultValue="0"/></label></div><label>الشروط<textarea name="terms" rows={4}/></label><footer><button type="button" className="secondary-button" onClick={()=>setEditor(false)}>إلغاء</button><button className="primary-button">حفظ القالب</button></footer></form></section></div>}
  </>
}
